import { EvidenceClass, GoalStatus, PHYSICAL_FIELDS } from '../enums.js';
import {
  clone, finalizeWithHash, invariant, rejectKeysDeep, rejectUnknown, requireArray,
  requireEnum, requireObject, requireString, verifyHash,
} from '../primitives.js';
import { createGoalInstance, validateGoalInstance } from '../contracts.js';
import { validateEvidenceRecordV2 } from '../execution/contracts.js';

const TIMESTAMP=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
const SUFFICIENCY_STATUS=['SATISFIED','PENDING','NOT_EVALUABLE'];
const PROOF_OPERATORS=['ALL','ANY','OBLIGATION_REF'];
const FORBIDDEN=new Set([...PHYSICAL_FIELDS,'question_family','decision_plan','response_payload','context_payload','raw','raw_payload','motor_payload','sql']);

function integer(value,path,minimum=0){invariant(Number.isInteger(value)&&value>=minimum,'INVALID_INTEGER',path);}
function instant(value,path){invariant(TIMESTAMP.test(value||''),'INVALID_TIMESTAMP',path);}
function strings(value,path,{nonEmpty=false}={}){requireArray(value,path,{nonEmpty});value.forEach((item,index)=>requireString(item,`${path}[${index}]`));invariant(new Set(value).size===value.length,'DUPLICATE_VALUE',path);}
function number(value,path){invariant(typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=1,'INVALID_COVERAGE',path);}
function semanticBinding(value,path){requireObject(value,path);const direct=clone(value),comparison=direct.comparison,explicit_constraints=direct.explicit_constraints;delete direct.comparison;delete direct.explicit_constraints;createGoalInstance({contract_version:'goal_instance.v1',goal_id:'obligation_validation',question_contract_ref:'obligation_validation',universe_resolution_ref:'obligation_validation',goal_type:'OBSERVED_RESULT',evidence_class:'REQUIRED',origin:'SYSTEM_DERIVED',status:'PENDING',bindings:direct,comparison,explicit_constraints});}

export function validateProofExpression(value,path='$.proof.expression'){
  rejectUnknown(value,value?.operator==='OBLIGATION_REF'?['operator','obligation_id']:['operator','operands'],path);requireEnum(value.operator,PROOF_OPERATORS,`${path}.operator`);
  if(value.operator==='OBLIGATION_REF')requireString(value.obligation_id,`${path}.obligation_id`);
  else {requireArray(value.operands,`${path}.operands`,{nonEmpty:true});value.operands.forEach((item,index)=>validateProofExpression(item,`${path}.operands[${index}]`));}
  return true;
}
function evaluateProof(expression,obligations){if(expression.operator==='OBLIGATION_REF'){const obligation=obligations.get(expression.obligation_id);invariant(obligation,'UNKNOWN_OBLIGATION_REF','$.proof.expression');return obligation.status==='SATISFIED';}const values=expression.operands.map(item=>evaluateProof(item,obligations));return expression.operator==='ALL'?values.every(Boolean):values.some(Boolean);}

export function validateEvidenceObligation(value,path='$'){
  rejectUnknown(value,['contract_version','obligation_id','goal_id','goal_fingerprint','required_claim_type','semantic_binding','authority_requirements','coverage_requirements','comparability_requirements','status','obligation_fingerprint'],path);
  requireEnum(value.contract_version,['evidence_obligation.v1'],`${path}.contract_version`);for(const key of ['obligation_id','goal_id','goal_fingerprint'])requireString(value[key],`${path}.${key}`);requireEnum(value.required_claim_type,['OBSERVED_VALUE'],`${path}.required_claim_type`);semanticBinding(value.semantic_binding,`${path}.semantic_binding`);
  rejectUnknown(value.authority_requirements,['required_refs'],`${path}.authority_requirements`);strings(value.authority_requirements.required_refs,`${path}.authority_requirements.required_refs`,{nonEmpty:true});
  rejectUnknown(value.coverage_requirements,['accepted_statuses','minimum_ratio','threshold_met_required'],`${path}.coverage_requirements`);strings(value.coverage_requirements.accepted_statuses,`${path}.coverage_requirements.accepted_statuses`,{nonEmpty:true});value.coverage_requirements.accepted_statuses.forEach((item,index)=>requireEnum(item,['CERTIFIED','LIMITED'],`${path}.coverage_requirements.accepted_statuses[${index}]`));number(value.coverage_requirements.minimum_ratio,`${path}.coverage_requirements.minimum_ratio`);invariant(value.coverage_requirements.threshold_met_required===true,'INVALID_COVERAGE_REQUIREMENT',`${path}.coverage_requirements.threshold_met_required`);
  rejectUnknown(value.comparability_requirements,['status','mode'],`${path}.comparability_requirements`);requireEnum(value.comparability_requirements.status,['NOT_REQUIRED','CERTIFIED'],`${path}.comparability_requirements.status`);requireString(value.comparability_requirements.mode,`${path}.comparability_requirements.mode`);requireEnum(value.status,SUFFICIENCY_STATUS,`${path}.status`);rejectKeysDeep(value,FORBIDDEN,path);verifyHash(value,'obligation_fingerprint',['obligation_id','goal_id']);return true;
}
export function createEvidenceObligation(draft){const value=finalizeWithHash(draft,'obligation_fingerprint',['obligation_id','goal_id']);validateEvidenceObligation(value);return value;}

export function validateSufficiencyEvaluationV2(value){
  rejectUnknown(value,['contract_version','evaluation_id','protocol_id','state_version','goal_id','goal_fingerprint','proof','status','satisfied_obligations','pending_obligations','blocking_reasons','supporting_evidence_refs','evaluation_fingerprint','evaluated_at'],'$');requireEnum(value.contract_version,['sufficiency_evaluation.v2'],'$.contract_version');for(const key of ['evaluation_id','protocol_id','goal_id','goal_fingerprint'])requireString(value[key],`$.${key}`);integer(value.state_version,'$.state_version',1);
  rejectUnknown(value.proof,['expression','obligations'],'$.proof');validateProofExpression(value.proof.expression);requireArray(value.proof.obligations,'$.proof.obligations',{nonEmpty:true});value.proof.obligations.forEach((item,index)=>validateEvidenceObligation(item,`$.proof.obligations[${index}]`));invariant(new Set(value.proof.obligations.map(item=>item.obligation_id)).size===value.proof.obligations.length,'DUPLICATE_OBLIGATION','$.proof.obligations');
  requireEnum(value.status,SUFFICIENCY_STATUS,'$.status');strings(value.satisfied_obligations,'$.satisfied_obligations');strings(value.pending_obligations,'$.pending_obligations');strings(value.blocking_reasons,'$.blocking_reasons');strings(value.supporting_evidence_refs,'$.supporting_evidence_refs');const obligations=new Map(value.proof.obligations.map(item=>[item.obligation_id,item])),satisfied=[...obligations.values()].filter(item=>item.status==='SATISFIED').map(item=>item.obligation_id).sort(),pending=[...obligations.values()].filter(item=>item.status!=='SATISFIED').map(item=>item.obligation_id).sort(),proofSatisfied=evaluateProof(value.proof.expression,obligations);invariant(JSON.stringify([...value.satisfied_obligations].sort())===JSON.stringify(satisfied)&&JSON.stringify([...value.pending_obligations].sort())===JSON.stringify(pending),'OBLIGATION_STATUS_MISMATCH','$');invariant((value.status==='SATISFIED')===proofSatisfied,'PROOF_STATUS_MISMATCH','$.status');invariant(value.status==='SATISFIED'?value.supporting_evidence_refs.length>0:value.pending_obligations.length>0,'INVALID_SUFFICIENCY_OUTCOME','$');invariant(value.status==='SATISFIED'?value.blocking_reasons.length===0:value.blocking_reasons.length>0,'INVALID_BLOCKING_REASONS','$.blocking_reasons');instant(value.evaluated_at,'$.evaluated_at');rejectKeysDeep(value,FORBIDDEN,'$');verifyHash(value,'evaluation_fingerprint',['evaluation_id','protocol_id','goal_id','evaluated_at']);return true;
}
export function createSufficiencyEvaluationV2(draft){const value=finalizeWithHash(draft,'evaluation_fingerprint',['evaluation_id','protocol_id','goal_id','evaluated_at']);validateSufficiencyEvaluationV2(value);return value;}

export function validateClosureEvaluation(value){rejectUnknown(value,['contract_version','protocol_id','source_state_version','status','reason_codes','blocking_goal_ids','closure_fingerprint'],'$');requireEnum(value.contract_version,['closure_evaluation.v1'],'$.contract_version');requireString(value.protocol_id,'$.protocol_id');integer(value.source_state_version,'$.source_state_version',1);requireEnum(value.status,['COMPLETE','PENDING','TERMINAL_PARTIAL'],'$.status');strings(value.reason_codes,'$.reason_codes');strings(value.blocking_goal_ids,'$.blocking_goal_ids');invariant(value.status==='COMPLETE'?value.reason_codes.length===0&&value.blocking_goal_ids.length===0:value.reason_codes.length>0,'INVALID_CLOSURE_OUTCOME','$');rejectKeysDeep(value,FORBIDDEN,'$');verifyHash(value,'closure_fingerprint',['protocol_id']);return true;}
export function createClosureEvaluation(draft){const value=finalizeWithHash(draft,'closure_fingerprint',['protocol_id']);validateClosureEvaluation(value);return value;}

function validatePublicClaim(value,path){rejectUnknown(value,['claim_type','subject','measure','value','period','commercial_universe','organization_scope','grain','comparison','authority_refs','claim_fingerprint'],path);requireEnum(value.claim_type,['OBSERVED_VALUE'],`${path}.claim_type`);rejectUnknown(value.subject,['canonical_id','entity_type'],`${path}.subject`);requireString(value.subject.canonical_id,`${path}.subject.canonical_id`);requireEnum(value.subject.entity_type,['BRAND'],`${path}.subject.entity_type`);requireString(value.measure,`${path}.measure`);rejectUnknown(value.value,['amount','unit'],`${path}.value`);invariant(typeof value.value.amount==='number'&&Number.isFinite(value.value.amount),'INVALID_CLAIM_VALUE',`${path}.value.amount`);requireEnum(value.value.unit,['VIN'],`${path}.value.unit`);rejectUnknown(value.period,['date_from','date_to','period_status','alignment'],`${path}.period`);for(const key of ['date_from','date_to'])requireString(value.period[key],`${path}.period.${key}`);requireEnum(value.period.period_status,['CLOSED'],`${path}.period.period_status`);requireEnum(value.period.alignment,['CALENDAR'],`${path}.period.alignment`);for(const key of ['commercial_universe','organization_scope','grain','comparison','claim_fingerprint'])requireString(value[key],`${path}.${key}`);strings(value.authority_refs,`${path}.authority_refs`,{nonEmpty:true});}
function validatePacketPeriod(value,path,{binding=false}={}){const keys=['date_from','date_to','period_status','alignment',...(binding?['timezone','anchor_timestamp','temporal_policy_ref','quantity','unit']:[])];rejectUnknown(value,keys,path);for(const key of ['date_from','date_to'])requireString(value[key],`${path}.${key}`);requireEnum(value.period_status,['CLOSED'],`${path}.period_status`);requireEnum(value.alignment,['CALENDAR'],`${path}.alignment`);if(binding){for(const key of ['timezone','anchor_timestamp','temporal_policy_ref'])requireString(value[key],`${path}.${key}`);integer(value.quantity,`${path}.quantity`,1);requireEnum(value.unit,['MONTH'],`${path}.unit`);}}
function validatePacketQuestion(value,path){rejectUnknown(value,['operation','concepts','subject','period','scope','grain','comparison','explicit_constraints'],path);requireEnum(value.operation,['OBSERVE','ASSESS'],`${path}.operation`);strings(value.concepts,`${path}.concepts`,{nonEmpty:true});value.concepts.forEach((item,index)=>requireEnum(item,['RESULT','SIGNAL'],`${path}.concepts[${index}]`));invariant((value.operation==='OBSERVE'&&value.concepts.includes('RESULT'))||(value.operation==='ASSESS'&&value.concepts.includes('SIGNAL')),'QUESTION_SEMANTICS_MISMATCH',path);rejectUnknown(value.subject,['entity_type','canonical_id','canonical_label','resolution_status','authority_ref'],`${path}.subject`);requireEnum(value.subject.entity_type,['BRAND'],`${path}.subject.entity_type`);for(const key of ['canonical_id','canonical_label','authority_ref'])requireString(value.subject[key],`${path}.subject.${key}`);requireEnum(value.subject.resolution_status,['RESOLVED'],`${path}.subject.resolution_status`);validatePacketPeriod(value.period,`${path}.period`,{binding:true});rejectUnknown(value.scope,['commercial_universe','organization_scope'],`${path}.scope`);requireEnum(value.scope.commercial_universe,['COMPANY'],`${path}.scope.commercial_universe`);requireEnum(value.scope.organization_scope,['CIDEF'],`${path}.scope.organization_scope`);requireEnum(value.grain,['BRAND'],`${path}.grain`);requireEnum(value.comparison,['NONE'],`${path}.comparison`);requireArray(value.explicit_constraints,`${path}.explicit_constraints`);}
function validateLimitation(value,path){rejectUnknown(value,['code','details'],path);requireEnum(value.code,['SCOPE_EXACT','PERIOD_EXACT','DATA_COVERAGE','COMPARISON_NONE','CLAIM_BOUNDARY'],`${path}.code`);if(value.code==='SCOPE_EXACT'){rejectUnknown(value.details,['commercial_universe','organization_scope'],`${path}.details`);requireEnum(value.details.commercial_universe,['COMPANY'],`${path}.details.commercial_universe`);requireEnum(value.details.organization_scope,['CIDEF'],`${path}.details.organization_scope`);}else if(value.code==='PERIOD_EXACT')validatePacketPeriod(value.details,`${path}.details`,{binding:true});else if(value.code==='DATA_COVERAGE'){rejectUnknown(value.details,['status','ratio'],`${path}.details`);requireEnum(value.details.status,['CERTIFIED'],`${path}.details.status`);number(value.details.ratio,`${path}.details.ratio`);}else if(value.code==='COMPARISON_NONE'){rejectUnknown(value.details,['comparison'],`${path}.details`);requireEnum(value.details.comparison,['NONE'],`${path}.details.comparison`);}else{rejectUnknown(value.details,['authorized_claim_types'],`${path}.details`);strings(value.details.authorized_claim_types,`${path}.details.authorized_claim_types`,{nonEmpty:true});value.details.authorized_claim_types.forEach((item,index)=>requireEnum(item,['OBSERVED_VALUE'],`${path}.details.authorized_claim_types[${index}]`));}}
function validatePacketProvenance(value,path){rejectUnknown(value,['protocol_trace_ref','question_contract_ref','goal_refs','evidence_refs','data_snapshot_refs','authority_refs'],path);requireString(value.protocol_trace_ref,`${path}.protocol_trace_ref`);requireString(value.question_contract_ref,`${path}.question_contract_ref`);for(const key of ['goal_refs','evidence_refs','data_snapshot_refs','authority_refs'])strings(value[key],`${path}.${key}`,{nonEmpty:true});}

export function validateSynthesisPacketV2(value){
  rejectUnknown(value,['packet_version','protocol_id','question','status','satisfied_goals','authorized_claims','limitations','forbidden_inferences','evidence_refs','authority_refs','coverage','provenance','packet_fingerprint','created_at'],'$');requireEnum(value.packet_version,['synthesis_packet.v2'],'$.packet_version');requireString(value.protocol_id,'$.protocol_id');validatePacketQuestion(value.question,'$.question');requireEnum(value.status,['COMPLETE'],'$.status');requireArray(value.satisfied_goals,'$.satisfied_goals',{nonEmpty:true});value.satisfied_goals.forEach((item,index)=>{rejectUnknown(item,['goal_id','goal_fingerprint','goal_type','evidence_class'],`$.satisfied_goals[${index}]`);for(const key of ['goal_id','goal_fingerprint'])requireString(item[key],`$.satisfied_goals[${index}].${key}`);requireEnum(item.goal_type,['OBSERVED_RESULT'],`$.satisfied_goals[${index}].goal_type`);requireEnum(item.evidence_class,Object.values(EvidenceClass),`$.satisfied_goals[${index}].evidence_class`);});requireArray(value.authorized_claims,'$.authorized_claims',{nonEmpty:true});value.authorized_claims.forEach((item,index)=>validatePublicClaim(item,`$.authorized_claims[${index}]`));requireArray(value.limitations,'$.limitations',{nonEmpty:true});value.limitations.forEach((item,index)=>validateLimitation(item,`$.limitations[${index}]`));strings(value.forbidden_inferences,'$.forbidden_inferences',{nonEmpty:true});strings(value.evidence_refs,'$.evidence_refs',{nonEmpty:true});strings(value.authority_refs,'$.authority_refs',{nonEmpty:true});requireArray(value.coverage,'$.coverage',{nonEmpty:true});value.coverage.forEach((item,index)=>{rejectUnknown(item,['evidence_ref','status','ratio'],`$.coverage[${index}]`);requireString(item.evidence_ref,`$.coverage[${index}].evidence_ref`);requireEnum(item.status,['CERTIFIED'],`$.coverage[${index}].status`);number(item.ratio,`$.coverage[${index}].ratio`);});validatePacketProvenance(value.provenance,'$.provenance');instant(value.created_at,'$.created_at');rejectKeysDeep(value,FORBIDDEN,'$');verifyHash(value,'packet_fingerprint',['protocol_id','created_at']);return true;
}
export function createSynthesisPacketV2(draft){const value=finalizeWithHash(draft,'packet_fingerprint',['protocol_id','created_at']);validateSynthesisPacketV2(value);return value;}

export function validatePacketEvidenceBoundary(packet,evidenceRecords){validateSynthesisPacketV2(packet);const selected=evidenceRecords.filter(record=>packet.evidence_refs.includes(record.evidence_fingerprint));invariant(selected.length===packet.evidence_refs.length&&selected.every(record=>packet.evidence_refs.includes(record.evidence_fingerprint)),'PACKET_EVIDENCE_REF_MISMATCH','$.evidence_refs');const evidence=new Map();for(const record of selected){validateEvidenceRecordV2(record);for(const claim of record.claims)evidence.set(claim.claim_fingerprint,claim);}for(const claim of packet.authorized_claims){const source=evidence.get(claim.claim_fingerprint);invariant(source,'CLAIM_NOT_BACKED_BY_EVIDENCE','$.authorized_claims');const publicSource=clone(source);delete publicSource.contract_version;delete publicSource.source_execution_ref;invariant(JSON.stringify(publicSource)===JSON.stringify(claim),'SYNTHESIS_CLAIM_WIDENED','$.authorized_claims');}invariant(packet.authorized_claims.length<=evidence.size,'SYNTHESIS_CLAIM_SET_WIDENED','$.authorized_claims');const authority=[...new Set(selected.flatMap(record=>record.authority_refs))].sort();invariant(JSON.stringify(authority)===JSON.stringify([...packet.authority_refs].sort()),'PACKET_AUTHORITY_WIDENED','$.authority_refs');return true;}

export function validateGoalForSufficiency(goal){validateGoalInstance(goal);invariant(goal.goal_type==='OBSERVED_RESULT','UNSUPPORTED_GOAL_SLICE','$.goal_type');invariant(goal.status===GoalStatus.PENDING,'GOAL_NOT_PENDING','$.status');return true;}
