import { EvidenceClass, GoalStatus, ProtocolStatus } from '../enums.js';
import { clone, invariant } from '../primitives.js';
import { createGoalInstance } from '../contracts.js';
import { createProtocolState, validateProtocolState } from '../runtime/contracts.js';
import { createClosureEvaluation, validateClosureEvaluation, validateSufficiencyEvaluationV2 } from './contracts.js';

function now(clock){const value=typeof clock==='function'?clock():clock;invariant(typeof value==='string','CLOCK_REQUIRED','$.clock');return value;}
function blocking(goal){return [EvidenceClass.REQUIRED,EvidenceClass.CONDITIONAL].includes(goal.evidence_class);}

export function applySufficiencyEvaluation(state,evaluation,{clock}={}){validateProtocolState(state);validateSufficiencyEvaluationV2(evaluation);invariant(state.status===ProtocolStatus.ASSESSING,'INVALID_STATE_TRANSITION','$.status');invariant(evaluation.protocol_id===state.protocol_id&&evaluation.state_version===state.state_version,'STALE_SUFFICIENCY_EVALUATION','$.evaluation');const target=state.goals.find(item=>item.goal_id===evaluation.goal_id);invariant(target&&target.goal_fingerprint===evaluation.goal_fingerprint,'EVALUATION_GOAL_MISMATCH','$.evaluation.goal_fingerprint');invariant(evaluation.status==='SATISFIED','SUFFICIENCY_NOT_SATISFIED','$.evaluation.status');const goals=state.goals.map(goal=>goal.goal_id===target.goal_id?createGoalInstance({...clone(goal),status:GoalStatus.SATISFIED,goal_fingerprint:undefined}):goal);return createProtocolState({...clone(state),state_version:state.state_version+1,status:ProtocolStatus.ASSESSING,goals,open_obligations:goals.filter(goal=>goal.status===GoalStatus.PENDING&&blocking(goal)).map(goal=>goal.goal_id),pending_execution_objective:{status:'OMITTED'},sufficiency_evaluation_refs:[...(state.sufficiency_evaluation_refs??[]),evaluation.evaluation_fingerprint],previous_state_hash:state.state_hash,updated_at:now(clock),state_hash:undefined});}

export function evaluateProtocolClosure({state,sufficiencyEvaluations=[],activeExecutionRefs=[],conflicts=[],blockingSemanticSelection=false}){validateProtocolState(state);sufficiencyEvaluations.forEach(validateSufficiencyEvaluationV2);const refs=new Set(state.sufficiency_evaluation_refs??[]),evaluated=new Set(sufficiencyEvaluations.filter(item=>item.protocol_id===state.protocol_id&&item.status==='SATISFIED'&&refs.has(item.evaluation_fingerprint)).map(item=>item.goal_id));const blockers=[];for(const goal of state.goals.filter(blocking))if(goal.status!==GoalStatus.SATISFIED||!evaluated.has(goal.goal_id))blockers.push(goal.goal_id);const reasons=[];if(blockers.length)reasons.push('BLOCKING_GOAL_PENDING');if(conflicts.length)reasons.push('CRITICAL_EVIDENCE_CONFLICT');if(activeExecutionRefs.length)reasons.push('ACTIVE_EXECUTION');if(blockingSemanticSelection)reasons.push('BLOCKING_SEMANTIC_SELECTION');const complete=state.goals.some(blocking)&&reasons.length===0;if(!complete&&reasons.length===0)reasons.push('NO_BLOCKING_GOAL');return createClosureEvaluation({contract_version:'closure_evaluation.v1',protocol_id:state.protocol_id,source_state_version:state.state_version,status:complete?'COMPLETE':'PENDING',reason_codes:reasons.sort(),blocking_goal_ids:blockers.sort()});}

export function applyProtocolClosure(state,closure,{clock}={}){validateProtocolState(state);validateClosureEvaluation(closure);invariant(closure.protocol_id===state.protocol_id&&closure.source_state_version===state.state_version,'STALE_CLOSURE_EVALUATION','$.closure');invariant(closure.status==='COMPLETE','PROTOCOL_NOT_COMPLETE','$.closure.status');return createProtocolState({...clone(state),state_version:state.state_version+1,status:ProtocolStatus.COMPLETE,open_obligations:[],actions:[],initial_goal_candidates:[],pending_execution_objective:{status:'OMITTED'},terminal:{status:'TERMINAL',reason_codes:[]},previous_state_hash:state.state_hash,updated_at:now(clock),state_hash:undefined});}
