import { EvidenceClass, GoalStatus, ProtocolStatus } from '../enums.js';
import { clone, invariant } from '../primitives.js';
import { validateQuestionContract, validateUniverseResolution, validateAvailabilitySnapshot } from '../contracts.js';
import { validateProtocolState } from '../runtime/contracts.js';
import { validateEvidenceRecordV2 } from '../execution/contracts.js';
import { createSynthesisPacketV2, validatePacketEvidenceBoundary, validateSufficiencyEvaluationV2 } from './contracts.js';

const FORBIDDEN_INFERENCES=['NO_GROWTH_INFERENCE','NO_TREND_INFERENCE','NO_RISK_INFERENCE','NO_MARKET_POSITION_INFERENCE','NO_EXPECTATION_INFERENCE','NO_CAUSAL_INFERENCE','NO_COMPARISON_INFERENCE'];
function publicClaim(claim){const value=clone(claim);delete value.contract_version;delete value.source_execution_ref;return value;}
function satisfied(goal){return goal.status===GoalStatus.SATISFIED&&[EvidenceClass.REQUIRED,EvidenceClass.CONDITIONAL,EvidenceClass.SUPPLEMENTAL,EvidenceClass.OPTIONAL].includes(goal.evidence_class);}

export function buildSynthesisPacketV2({questionContract,protocolState,sufficiencyEvaluations,evidenceRecords,universeResolution,availabilitySnapshot,created_at}){validateQuestionContract(questionContract);validateProtocolState(protocolState);validateUniverseResolution(universeResolution);validateAvailabilitySnapshot(availabilitySnapshot);sufficiencyEvaluations.forEach(validateSufficiencyEvaluationV2);evidenceRecords.forEach(validateEvidenceRecordV2);invariant(protocolState.status===ProtocolStatus.COMPLETE&&protocolState.terminal.status==='TERMINAL','SYNTHESIS_REQUIRES_COMPLETE_PROTOCOL','$.protocolState.status');invariant(protocolState.question_contract_hash===questionContract.question_contract_hash&&protocolState.universe_resolution_fingerprint===universeResolution.resolution_fingerprint&&protocolState.availability_snapshot_fingerprint===availabilitySnapshot.snapshot_fingerprint,'SYNTHESIS_CONTEXT_MISMATCH','$.protocolState');const goals=protocolState.goals.filter(satisfied),evaluationRefs=new Set(protocolState.sufficiency_evaluation_refs??[]),evaluations=sufficiencyEvaluations.filter(item=>item.status==='SATISFIED'&&evaluationRefs.has(item.evaluation_fingerprint)&&goals.some(goal=>goal.goal_id===item.goal_id));invariant(goals.length>0&&evaluations.length===goals.filter(goal=>[EvidenceClass.REQUIRED,EvidenceClass.CONDITIONAL].includes(goal.evidence_class)).length,'SYNTHESIS_REQUIRES_SATISFIED_EVALUATIONS','$.sufficiencyEvaluations');const refs=[...new Set(evaluations.flatMap(item=>item.supporting_evidence_refs))].sort(),records=evidenceRecords.filter(item=>refs.includes(item.evidence_fingerprint));invariant(records.length===refs.length,'SUPPORTING_EVIDENCE_MISSING','$.evidenceRecords');const claims=[];for(const record of records)for(const claim of record.claims){invariant(claim.claim_type==='OBSERVED_VALUE','UNSUPPORTED_SYNTHESIS_CLAIM','$.authorized_claims');claims.push(publicClaim(claim));}claims.sort((a,b)=>a.claim_fingerprint.localeCompare(b.claim_fingerprint));const authority=[...new Set(records.flatMap(item=>item.authority_refs))].sort(),binding=records[0].semantic_binding;
  const packet=createSynthesisPacketV2({packet_version:'synthesis_packet.v2',protocol_id:protocolState.protocol_id,question:{operation:questionContract.semantic_intent.operation,concepts:clone(questionContract.semantic_intent.expressed_concepts),subject:clone(binding.subject),period:clone(binding.period),scope:{commercial_universe:binding.commercial_universe,organization_scope:binding.organization_scope},grain:binding.grain,comparison:binding.comparison,explicit_constraints:clone(binding.explicit_constraints)},status:'COMPLETE',satisfied_goals:goals.map(goal=>({goal_id:goal.goal_id,goal_fingerprint:goal.goal_fingerprint,goal_type:goal.goal_type,evidence_class:goal.evidence_class})),authorized_claims:claims,limitations:[{code:'SCOPE_EXACT',details:{commercial_universe:binding.commercial_universe,organization_scope:binding.organization_scope}},{code:'PERIOD_EXACT',details:clone(binding.period)},{code:'DATA_COVERAGE',details:{status:records[0].coverage.status,ratio:records[0].coverage.ratio}},{code:'COMPARISON_NONE',details:{comparison:'NONE'}},{code:'CLAIM_BOUNDARY',details:{authorized_claim_types:['OBSERVED_VALUE']}}],forbidden_inferences:FORBIDDEN_INFERENCES,evidence_refs:refs,authority_refs:authority,coverage:records.map(record=>({evidence_ref:record.evidence_fingerprint,status:record.coverage.status,ratio:record.coverage.ratio})),provenance:{protocol_trace_ref:protocolState.protocol_id,question_contract_ref:questionContract.question_contract_hash,goal_refs:goals.map(goal=>goal.goal_id),evidence_refs:refs,data_snapshot_refs:[availabilitySnapshot.snapshot_fingerprint],authority_refs:authority},created_at});validatePacketEvidenceBoundary(packet,records);return packet;}

export { FORBIDDEN_INFERENCES };
