import { createAvailabilitySnapshot, validateAuthorityRef, validateQuestionContract } from '../contracts.js';
import { clone, invariant } from '../primitives.js';

const DAY=86400000;
function epoch(date){return Date.parse(`${date}T00:00:00.000Z`);}
export function coverageForPeriod(requested,{available_from,available_to}={}){if(!available_from||!available_to||available_to<requested.date_from||available_from>requested.date_to)return {status:'NONE',ratio:0};const start=Math.max(epoch(requested.date_from),epoch(available_from));const end=Math.min(epoch(requested.date_to),epoch(available_to));const ratio=(end-start+DAY)/(epoch(requested.date_to)-epoch(requested.date_from)+DAY);return {status:ratio===1?'FULL':'PARTIAL',ratio};}

export function salesAvailabilityObservation(input){return {...clone(input),source_domain:'SALES',data_status:input.data_status??'AVAILABLE',temporal_semantics:'PERIOD_COVERAGE'};}
export function rvmAvailabilityObservation(input){invariant(['CONSOLIDATED','PRELIMINARY'].includes(input.data_status),'INVALID_RVM_DATA_STATUS','$.data_status');return {...clone(input),source_domain:'RVM',temporal_semantics:'PERIOD_COVERAGE'};}
export function crmAvailabilityObservation(input){return {...clone(input),source_domain:'CRM',data_status:'CURRENT',temporal_semantics:'CURRENT_STATE'};}
export function pricingAvailabilityObservation(input){return {...clone(input),source_domain:'PRICING',data_status:input.data_status??'AVAILABLE',temporal_semantics:'VALIDITY_COVERAGE'};}

function normalizeSource(source,requested,observedAt){validateAuthorityRef(source.authority_ref,'$.authority_ref');let coverage=coverageForPeriod(requested,source);const limitations=[...(source.limitations??[])];if(source.source_domain==='CRM'&&source.temporal_semantics==='CURRENT_STATE'){const observationDate=observedAt.slice(0,10);const currentRequested=requested.date_from<=observationDate&&requested.date_to>=observationDate;if(!currentRequested){coverage={status:'NONE',ratio:0};limitations.push('HISTORICAL_CRM_SNAPSHOT_UNAVAILABLE');}}
  return {source_domain:source.source_domain,authority_ref:clone(source.authority_ref),data_status:source.data_status,temporal_semantics:source.temporal_semantics,...(source.available_from&&source.available_to?{available_from:source.available_from,available_to:source.available_to}:{}),...(source.snapshot_date?{snapshot_date:source.snapshot_date}:{}),coverage,limitations};}

export function createAvailabilitySnapshotFromQuestionContract(question,{snapshot_id='availability_fixture',observed_at,source_observations=[]}={}){validateQuestionContract(question);invariant(question.period?.materialized,'QUESTION_PERIOD_NOT_AVAILABILITY_READY','$.period');const instant=new Date(observed_at);invariant(Number.isFinite(instant.getTime()),'OBSERVED_AT_REQUIRED','$.observed_at');const observed=instant.toISOString();const requested={date_from:question.period.materialized.date_from,date_to:question.period.materialized.date_to,period_status:question.period.materialized.period_status};const hash=question.question_contract_hash;const snapshot=createAvailabilitySnapshot({contract_version:'availability_snapshot.v1',snapshot_id,observed_at:observed,question_contract_ref:hash,requested_period:requested,sources:source_observations.map(item=>normalizeSource(item,requested,observed))});invariant(question.question_contract_hash===hash,'QUESTION_CONTRACT_MUTATED','$');return snapshot;}
