import { buildObservedResultFixture } from '../fixtures/observedResult.js';
import { createAuthorityRef } from '../contracts.js';
import { createUniverseResolutionRequestFromQuestionContract } from './contracts.js';
import { createCertifiedMembershipAdapter, createLegacyEntityAuthorityAdapter } from './authorityAdapters.js';
import { resolveUniverseBoundary } from './resolveUniverse.js';
import { createAvailabilitySnapshotFromQuestionContract, crmAvailabilityObservation, rvmAvailabilityObservation, salesAvailabilityObservation } from './availability.js';

export const WP04_OBSERVED_AT='2026-09-14T12:00:00.000Z';
const descriptor=(authority_type,authority_name,authority_version,snapshot_ref)=>({authority_type,authority_name,authority_version,snapshot_ref});
export const PRODUCT_AUTHORITY=descriptor('PRODUCT_MASTER','canonical_product_identity','entityResolver.v1','product-master-fixture-2026-09-14');
export const SALES_AUTHORITY=descriptor('SALES_UNIVERSE','ventas_universe_v01','0.1','ventas-universe-fixture-2026-09-14');
export const RVM_AUTHORITY=descriptor('RVM_UNIVERSE','rvm_universe_v01','0.1','rvm-fixture-2026-09-14');
export const CRM_AUTHORITY=descriptor('CRM_AUTHORITY','crm_universe_v01','0.1','crm-current-fixture-2026-09-14');

function ref(descriptor,date_from,date_to){return createAuthorityRef({...descriptor,effective_period:{date_from,date_to}});}
export async function buildWp04Fixture(){const question=buildObservedResultFixture().question;const request=createUniverseResolutionRequestFromQuestionContract(question,{request_id:'universe_request_foton_august'});const identity_adapter=createLegacyEntityAuthorityAdapter({authority_descriptor:PRODUCT_AUTHORITY,resolver:async()=>({status:'UNIQUE',resolved:true,type:'BRAND',display_name:'Foton',canonical_id:'brand_fixture_foton'})});const membership_adapter=createCertifiedMembershipAdapter({provider:async()=>({status:'RESOLVED',commercial_universe:'COMPANY',organization_scope:{status:'BOUND',value:'CIDEF',authority_required:true},market_universe:{status:'NOT_APPLICABLE'},geography:{status:'BOUND',value:'CHILE',authority_required:true},authority_descriptors:[SALES_AUTHORITY],effective_from:'2026-01-01',effective_to:'2026-09-14'})});const resolution=await resolveUniverseBoundary(request,{resolution_id:'resolution_wp04_foton_august',identity_adapter,membership_adapter});const availability=createAvailabilitySnapshotFromQuestionContract(question,{snapshot_id:'availability_wp04_foton_august',observed_at:WP04_OBSERVED_AT,source_observations:[salesAvailabilityObservation({authority_ref:ref(SALES_AUTHORITY,'2026-01-01','2026-09-14'),available_from:'2026-01-01',available_to:'2026-09-14'}),rvmAvailabilityObservation({authority_ref:ref(RVM_AUTHORITY,'2026-01-01','2026-08-31'),data_status:'CONSOLIDATED',available_from:'2026-01-01',available_to:'2026-08-31'}),rvmAvailabilityObservation({authority_ref:ref(RVM_AUTHORITY,'2026-09-01','2026-09-14'),data_status:'PRELIMINARY',snapshot_date:'2026-09-14',available_from:'2026-09-01',available_to:'2026-09-14'}),crmAvailabilityObservation({authority_ref:ref(CRM_AUTHORITY,'2026-09-14','2026-09-14'),available_from:'2026-09-14',available_to:'2026-09-14'})]});return {question,request,resolution,availability};}
