import { createAuthorityRef, createUniverseResolution } from '../contracts.js';
import { clone, invariant } from '../primitives.js';
import { validateUniverseResolutionRequest } from './contracts.js';

function temporalAuthority(request){const period=request.requested_period;return createAuthorityRef({authority_type:'TEMPORAL_POLICY',authority_name:period.temporal_policy_ref,authority_version:'question_contract.v1',snapshot_ref:period.anchor_timestamp,effective_period:{date_from:period.date_from,date_to:period.date_to}});}
function covered(result,request){return result.status==='RESOLVED'&&result.effective_from<=request.requested_period.date_from&&result.effective_to>=request.requested_period.date_to;}

export async function resolveUniverseBoundary(request,{resolution_id='resolution_fixture',identity_adapter,membership_adapter}={}){
  validateUniverseResolutionRequest(request);invariant(typeof identity_adapter==='function','IDENTITY_ADAPTER_REQUIRED','$');invariant(typeof membership_adapter==='function','MEMBERSHIP_ADAPTER_REQUIRED','$');const before=request.request_fingerprint;const [identity,membership]=await Promise.all([identity_adapter(request),membership_adapter(request)]);invariant(request.request_fingerprint===before,'RESOLUTION_REQUEST_MUTATED','$');const temporal_ref=temporalAuthority(request);const temporalCovered=covered(membership,request);
  return createUniverseResolution({contract_version:'universe_resolution.v1',resolution_id,question_contract_ref:request.question_contract_ref,request_fingerprint:request.request_fingerprint,subject:{expression:request.subject.expression,entity_type:request.subject.type_constraints[0],resolution_status:identity.status,authority_ref:identity.authority_ref,candidates:clone(identity.candidates??[]),...(identity.status==='RESOLVED'?{canonical_id:identity.canonical_id,canonical_label:identity.canonical_label}:{})},membership:{commercial_universe:request.requested_scope.commercial_universe,organization_scope:clone(request.requested_scope.organization_scope),market_universe:clone(request.requested_scope.market_universe),geography:clone(request.requested_scope.geography),membership_status:membership.status,membership_authority_refs:clone(membership.authority_refs??[])},temporal:{date_from:request.requested_period.date_from,date_to:request.requested_period.date_to,effective_from:membership.effective_from??request.requested_period.date_from,effective_to:membership.effective_to??request.requested_period.date_to,period_status:request.requested_period.period_status,temporal_status:temporalCovered?'PRESERVED':membership.status==='RESOLVED'?'PARTIAL':'UNSUPPORTED'},grain:{requested:request.requested_grain,resolved:request.requested_grain},coverage:{identity:identity.status==='RESOLVED'?'CERTIFIED':'UNCERTIFIED',membership:membership.status==='RESOLVED'?'CERTIFIED':'UNCERTIFIED',temporal:temporalCovered?'CERTIFIED':'UNCERTIFIED'},authority:{identity_ref:identity.authority_ref,membership_refs:clone(membership.authority_refs??[]),temporal_ref},limitations:[...(identity.limitations??[]),...(membership.limitations??[])]});
}
