import test from 'node:test'; import assert from 'node:assert/strict';
import { decideIntent } from '../lib/decide/decideIntent.js';
import { projectEvidence } from '../lib/analyze/evidenceProjection.js';
import { executeDecisionPlan } from '../lib/analyze/executeDecisionPlan.js';
import { containsForbiddenArchitecture } from '../lib/analyze/publicSanitizer.js';

function intent(over={}){return {version:'intent.v1',question_type:'RISK',entity:{type:'BRAND',value:'FOTON'},period:{type:'LAST_CLOSED_QUARTER',date_from:'2026-04-01',date_to:'2026-06-30'},comparison:'YOY',scope:{organization_scope:'CIDEF',commercial_universe:'COMPANY'},depth:'DEEP',semantic_provenance:{},...over};}
function authority(period={}){return {entity:{type:'BRAND',display_name:'FOTON'},period:{type:'LAST_CLOSED_QUARTER',date_from:'2026-04-01',date_to:'2026-06-30',period_status:'CLOSED',cutoff_mode:'FULL_PERIOD',...period},defaults:{scope:{commercial_universe:'COMPANY'}}};}
function raw(values,warnings=[]){return {metric:'VIN_SALES',grain:'BRAND',series:Object.entries(values).map(([period,value])=>({period,value})),temporalSemantics:{cutoffMode:'FULL_PERIOD',lastPeriodComplete:true},coverage:{dimensionCoverage:[{dimension:'BRAND',unresolved:0,ambiguous:0,total:1}]},commercial_scope:{universe:'COMPANY'},commercial_validation:{valid:true,violations:[]},commercial_coverage:{status:'OK'},warnings,motor:'ventas_longitudinal_context_v01',target_model_ids:[1]};}
const vals={}; for(let m=4;m<=12;m++) vals[`2025-${String(m).padStart(2,'0')}`]=50; for(let m=1;m<=6;m++) vals[`2026-${String(m).padStart(2,'0')}`]=50;

test('DECIDE attaches comparative temporal support for closed quarter',()=>{const p=decideIntent(intent(),authority());const r=p.evidence_requirements.find(x=>x.type==='HISTORICAL_REFERENCE');assert.equal(r.proposition.type,'COMPARATIVE_TEMPORAL_SUPPORT');assert.equal(r.proposition.evaluation.mode,'AGGREGATE_AND_MONTHLY_SUPPORT');assert.equal(r.proposition.reference.type,'SAME_PERIOD_PREVIOUS_YEAR');assert.deepEqual(p.sufficiency_contract.required_evidence,['CURRENT_RESULT','HISTORICAL_REFERENCE']);});
test('one closed month uses aggregate only',()=>{const i=intent({period:{type:'LAST_CLOSED_MONTH',date_from:'2026-06-01',date_to:'2026-06-30'}});const a=authority({type:'LAST_CLOSED_MONTH',date_from:'2026-06-01',date_to:'2026-06-30'});const r=decideIntent(i,a).evidence_requirements.find(x=>x.type==='HISTORICAL_REFERENCE');assert.equal(r.proposition.evaluation.mode,'AGGREGATE_ONLY');});
test('proposition absent outside v0.1 scope',()=>{for(const comparison of ['PREVIOUS_PERIOD','MARKET']){const r=decideIntent(intent({comparison}),authority()).evidence_requirements.find(x=>x.type==='HISTORICAL_REFERENCE');assert.equal(r.proposition,undefined);}const open=authority({period_status:'PARTIAL'});assert.equal(decideIntent(intent(),open).evidence_requirements.find(x=>x.type==='HISTORICAL_REFERENCE').proposition,undefined);});
test('projects Q2 aggregate and monthly support from wide series',()=>{const p=decideIntent(intent(),authority());const req=p.evidence_requirements.find(x=>x.type==='HISTORICAL_REFERENCE');const values={...vals,'2025-04':110,'2025-05':110,'2025-06':110,'2026-04':100,'2026-05':100,'2026-06':100};const out=projectEvidence({investigation:{requirements:[req]},plan:p,raw:raw(values)});assert.equal(out.status,'AVAILABLE');assert.deepEqual(out.evidence.aggregate,{target_value:300,reference_value:330,absolute_change:-30,pct_change:-30/330});assert.equal(out.evidence.monthly_support.length,3);assert.deepEqual(out.evidence.direction_counts,{negative_count:3,positive_count:0,unchanged_count:0});const text=JSON.stringify(out.evidence);for(const m of ['2025-07','2025-08','2025-09','2025-10','2025-11','2025-12','2026-01','2026-02','2026-03']) assert.equal(text.includes(m),false,m);});
test('mixed months retain magnitude and mathematical counts only',()=>{const p=decideIntent(intent(),authority()),req=p.evidence_requirements.find(x=>x.type==='HISTORICAL_REFERENCE');const values={...vals,'2025-04':100,'2025-05':100,'2025-06':100,'2026-04':130,'2026-05':120,'2026-06':45};const out=projectEvidence({investigation:{requirements:[req]},plan:p,raw:raw(values)});assert.equal(out.evidence.aggregate.absolute_change,-5);assert.deepEqual(out.evidence.direction_counts,{negative_count:1,positive_count:2,unchanged_count:0});const text=JSON.stringify(out.evidence).toLowerCase();for(const forbidden of ['deterioration','risk','materiality','adverse'])assert.equal(text.includes(forbidden),false);});
test('missing reference month is not evaluable',()=>{const p=decideIntent(intent(),authority()),req=p.evidence_requirements.find(x=>x.type==='HISTORICAL_REFERENCE');const values={...vals};delete values['2025-05'];const out=projectEvidence({investigation:{requirements:[req]},plan:p,raw:raw(values)});assert.equal(out.status,'NOT_EVALUABLE');assert.equal(out.reason_code,'REFERENCE_PERIOD_DATA_MISSING');});
test('execute sanitizes projected public evidence and preserves warnings',async()=>{const p=decideIntent(intent(),authority());const values={...vals,'2025-04':110,'2025-05':110,'2025-06':110,'2026-04':100,'2026-05':100,'2026-06':100};const executor=async spec=>spec.capability==='VENTAS'?raw(values,['MATERIAL_WARNING']):{};let out=await executeDecisionPlan(p,authority(),intent(),{executor});assert.equal(out.analysis_iteration.response_payload.kinds[0],'current_result');out=await executeDecisionPlan(p,authority(),intent(),{executor,continuationState:out._continuation_state});assert.equal(out.analysis_iteration.response_payload.kinds[0],'historical_reference');assert.equal(out.analysis_iteration.response_payload.data.proposition_type,'COMPARATIVE_TEMPORAL_SUPPORT');assert.ok(out.analysis_iteration.response_payload.data.warnings.includes('MATERIAL_WARNING'));assert.equal(containsForbiddenArchitecture(out.analysis_iteration),false);});
