import test from 'node:test';
import assert from 'node:assert/strict';
import { ActivityTransition, DiagnosticRelation, Direction, PctStatus, assembleVinGrowthDiagnostic, diagnosticRelation, vinGrowthDiagnosticV01 } from '../lib/motors/vin-growth-diagnostic-v01.js';
const periods={currentMonth:'2026-08',previousMonth:'2026-07'}; const scope={brandId:71,brandName:'DONGFENG',storeId:7,storeName:'BELLAVISTA'};
function ventas(sp=15,sc=27,tp=127,tc=187,extra={}){return{commercial_scope:{universe:'OWN_STORES'},temporalSemantics:{lastPeriodComplete:true},warnings:[],series:[{period:'2026-07',value:tp},{period:'2026-08',value:tc}],seriesByBreakdown:[{key:'7',series:[{period:'2026-07',value:sp},{period:'2026-08',value:sc}]}],...extra};}
function rvm(p=232,c=335,extra={}){return{warnings:[],series:[{period:'2026-07',value:p},{period:'2026-08',value:c}],...extra};}
function conversion(pn=0,pd=10,cn=1,cd=20,extra={}){return{commercial_scope:{universe:'OWN_STORES'},warnings:['CRM_NO_HISTORICAL_STATE_SNAPSHOTS'],series:[{period:'2026-07',numerator:pn,denominator:pd,value:pd>0?pn/pd:null},{period:'2026-08',numerator:cn,denominator:cd,value:cd>0?cn/cd:null}],...extra};}
function sold(p=0,c=1,extra={}){return{commercial_scope:{universe:'OWN_STORES'},warnings:['CRM_NO_HISTORICAL_STATE_SNAPSHOTS'],series:[{period:'2026-07',value:p},{period:'2026-08',value:c}],...extra};}
function build(o={}){return assembleVinGrowthDiagnostic({scope,periods,ventas:o.ventas??ventas(),rvm:o.rvm??rvm(),crmConversion:o.crmConversion??conversion(),crmSold:o.crmSold??sold()});}
test('A complete evaluable',()=>{const x=build();assert.equal(x.status,'COMPLETE');assert.equal(x.store_result.store_vin_delta,12);assert.equal(x.store_result.store_vin_delta_pct,80);assert.equal(x.crm_context.conversion.crm_conversion_numerator_t,1);assert.equal(x.crm_context.conversion.crm_conversion_denominator_t,20);});
test('B STORE↑ RVM↑ SHARE↑',()=>{const x=build();assert.deepEqual([x.store_result.direction,x.rvm_context.direction,x.internal_position.direction],['POSITIVE','POSITIVE','POSITIVE']);});
test('C STORE↑ RVM↑ SHARE↓',()=>{const x=build({ventas:ventas(15,20,100,200)});assert.deepEqual([x.store_result.direction,x.rvm_context.direction,x.internal_position.direction],['POSITIVE','POSITIVE','NEGATIVE']);});
test('D STORE↓ RVM↑',()=>assert.equal(build({ventas:ventas(20,10,100,100)}).diagnostic_relations.store_vs_rvm.relation,'OPPOSITE_DIRECTION'));
test('E STORE↑ RVM↓',()=>assert.equal(build({rvm:rvm(335,232)}).diagnostic_relations.store_vs_rvm.relation,'OPPOSITE_DIRECTION'));
test('F NEW_ACTIVITY zero base',()=>{const x=build({ventas:ventas(0,5,100,100)}).store_result;assert.equal(x.activity_transition,ActivityTransition.NEW_ACTIVITY);assert.equal(x.direction,Direction.POSITIVE);assert.equal(x.store_vin_delta_pct,null);assert.equal(x.store_vin_delta_pct_status,PctStatus.NOT_EVALUABLE_ZERO_BASE);});
test('G CEASED_ACTIVITY',()=>{const x=build({ventas:ventas(5,0,100,100)}).store_result;assert.equal(x.activity_transition,ActivityTransition.CEASED_ACTIVITY);assert.equal(x.direction,Direction.NEGATIVE);});
test('H internal denominator zero',()=>{const x=build({ventas:ventas(0,0,100,0)});assert.equal(x.internal_position.evaluable,false);assert.equal(x.diagnostic_relations.store_vs_internal_share.relation,'NOT_EVALUABLE');assert.equal(x.status,'PARTIAL');});
test('I conversion 1/1 retained',()=>{const x=build({crmConversion:conversion(1,2,1,1)}).crm_context.conversion;assert.deepEqual([x.crm_conversion_t,x.crm_conversion_numerator_t,x.crm_conversion_denominator_t,x.evaluable],[1,1,1,true]);});
test('J conversion unavailable',()=>{const x=build({crmConversion:conversion(0,0,0,0,{warnings:['NO_OBSERVED_EVIDENCE_IN_RANGE','CRM_NO_HISTORICAL_STATE_SNAPSHOTS']})});assert.equal(x.status,'PARTIAL');assert.equal(x.crm_context.conversion.direction,'NOT_EVALUABLE');assert.equal(x.diagnostic_relations.store_vs_crm_conversion.relation,'NOT_EVALUABLE');});
test('K SOLD zero retained',()=>{const x=build({crmSold:sold(0,0)}).crm_context.sold;assert.equal(x.evaluable,true);assert.equal(x.crm_sold_t,0);assert.equal(x.direction,'FLAT');});
test('L CRM fully unavailable',()=>{const no={commercial_scope:{universe:'OWN_STORES'},warnings:['NO_OBSERVED_EVIDENCE_IN_RANGE','CRM_NO_HISTORICAL_STATE_SNAPSHOTS'],series:[]};assert.equal(build({crmConversion:no,crmSold:no}).status,'PARTIAL');});
test('M RVM unavailable',()=>{const x=build({rvm:rvm(0,0,{warnings:['NO_OBSERVED_EVIDENCE_IN_RANGE']})});assert.equal(x.rvm_context.evaluable,false);assert.equal(x.status,'PARTIAL');});
function deps({brand=true,store='CIDEF',vu='OWN_STORES',complete=true}={}){return{db:{query:async sql=>sql.includes('marcas_master')?(brand?[{marca_id:71,nombre_canonico:'DONGFENG'}]:[]):(store==null?[]:[{sucursal_id:7,nombre_canonico:'BELLAVISTA',tipo_canal:store}])},ventas:async()=>ventas(15,27,127,187,{commercial_scope:{universe:vu},temporalSemantics:{lastPeriodComplete:complete}}),rvm:async()=>rvm(),crm:async input=>input.metric==='CONVERSION_RATE'?conversion():sold()};}
test('N store not OWN_STORE',async()=>assert.rejects(()=>vinGrowthDiagnosticV01({brand_id:71,store_id:7,current_month:'2026-08'},deps({store:'DEALER'})),{code:'STORE_NOT_OWN_STORE'}));
test('O domain mismatch',async()=>assert.rejects(()=>vinGrowthDiagnosticV01({brand_id:71,store_id:7,current_month:'2026-08'},deps({vu:'COMPANY'})),{code:'DOMAIN_MISMATCH'}));
test('P invalid/unclosed period',async()=>{await assert.rejects(()=>vinGrowthDiagnosticV01({brand_id:71,store_id:7,current_month:'2026-13'},deps()),{code:'INVALID_PERIOD'});await assert.rejects(()=>vinGrowthDiagnosticV01({brand_id:71,store_id:7,current_month:'2026-08'},deps({complete:false})),{code:'INVALID_PERIOD'});});
test('Q 0→0 NO_ACTIVITY',()=>{const x=build({ventas:ventas(0,0,100,100)}).store_result;assert.deepEqual([x.activity_transition,x.store_vin_delta,x.direction,x.store_vin_delta_pct],['NO_ACTIVITY',0,'FLAT',null]);});
test('R previous internal denominator zero',()=>{const x=build({ventas:ventas(0,10,0,100)}).internal_position;assert.equal(x.internal_share_delta,null);assert.equal(x.direction,'NOT_EVALUABLE');});
test('S RVM zero base',()=>{const x=build({rvm:rvm(0,10)}).rvm_context;assert.equal(x.brand_rvm_vin_delta,10);assert.equal(x.direction,'POSITIVE');assert.equal(x.brand_rvm_vin_delta_pct,null);assert.equal(x.brand_rvm_vin_delta_pct_status,'NOT_EVALUABLE_ZERO_BASE');});
test('T CRM denominator_t=0',()=>assert.equal(build({crmConversion:conversion(1,10,0,0)}).crm_context.conversion.evaluable,false));
test('U CRM denominator_previous=0',()=>{const x=build({crmConversion:conversion(0,0,1,10)}).crm_context.conversion;assert.equal(x.crm_conversion_delta,null);assert.equal(x.direction,'NOT_EVALUABLE');});
test('V NO_COVERAGE',()=>assert.equal(build({crmSold:sold(0,0,{warnings:['NO_OBSERVED_EVIDENCE_IN_RANGE','CRM_NO_HISTORICAL_STATE_SNAPSHOTS']})}).crm_context.sold.direction,'NOT_EVALUABLE'));
test('W ZERO_OBSERVED',()=>{const x=build({crmSold:sold(0,0)}).crm_context.sold;assert.deepEqual([x.crm_sold_t,x.crm_sold_t_minus_1],[0,0]);});
test('X conversion evaluable SOLD unavailable',()=>{const x=build({crmSold:sold(0,0,{warnings:['NO_OBSERVED_EVIDENCE_IN_RANGE','CRM_NO_HISTORICAL_STATE_SNAPSHOTS']})});assert.equal(x.crm_context.conversion.evaluable,true);assert.equal(x.crm_context.sold.evaluable,false);assert.equal(x.status,'PARTIAL');});
test('Y RVM available CRM unavailable',()=>{const no={commercial_scope:{universe:'OWN_STORES'},warnings:['NO_OBSERVED_EVIDENCE_IN_RANGE','CRM_NO_HISTORICAL_STATE_SNAPSHOTS'],series:[]};const x=build({crmConversion:no,crmSold:no});assert.equal(x.rvm_context.evaluable,true);assert.equal(x.status,'PARTIAL');});
test('Z deterministic',()=>assert.deepEqual(build(),build()));
test('truth table',()=>{const P='POSITIVE',N='NEGATIVE',F='FLAT',X='NOT_EVALUABLE';assert.equal(diagnosticRelation(P,P),'SAME_DIRECTION');assert.equal(diagnosticRelation(N,N),'SAME_DIRECTION');assert.equal(diagnosticRelation(P,N),'OPPOSITE_DIRECTION');assert.equal(diagnosticRelation(N,P),'OPPOSITE_DIRECTION');assert.equal(diagnosticRelation(P,F),'STORE_MOVED_CONTEXT_FLAT');assert.equal(diagnosticRelation(F,P),'STORE_FLAT_CONTEXT_MOVED');assert.equal(diagnosticRelation(F,F),'BOTH_FLAT');assert.equal(diagnosticRelation(X,P),'NOT_EVALUABLE');});
test('reconciliations fail closed',()=>{assert.throws(()=>build({ventas:ventas(15,200,127,187)}),/INSUFFICIENT_CORE_DATA/);assert.throws(()=>build({crmConversion:conversion(0,10,2,1)}),/INSUFFICIENT_CORE_DATA/);});
