export const GoalType = Object.freeze({
  OBSERVED_RESULT: 'OBSERVED_RESULT',
  TEMPORAL_TRAJECTORY: 'TEMPORAL_TRAJECTORY',
  RELATIVE_PERFORMANCE: 'RELATIVE_PERFORMANCE',
  MARKET_POSITION: 'MARKET_POSITION',
});
export const EvidenceClass = Object.freeze({
  REQUIRED: 'REQUIRED', CONDITIONAL: 'CONDITIONAL', SUPPLEMENTAL: 'SUPPLEMENTAL', OPTIONAL: 'OPTIONAL',
});
export const ClaimType = Object.freeze({ OBSERVED_VALUE: 'OBSERVED_VALUE' });
export const ApplicabilityStatus = Object.freeze({
  APPLICABLE: 'APPLICABLE',
  APPLICABLE_WITH_LIMITED_COVERAGE: 'APPLICABLE_WITH_LIMITED_COVERAGE',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});
export const GoalStatus = Object.freeze({ PENDING: 'PENDING', SATISFIED: 'SATISFIED', NOT_EVALUABLE: 'NOT_EVALUABLE' });
export const GoalOrigin = Object.freeze({
  USER_EXPRESSED: 'USER_EXPRESSED', USER_SELECTED: 'USER_SELECTED',
  INITIAL_CANDIDATE: 'INITIAL_CANDIDATE', SYSTEM_DERIVED: 'SYSTEM_DERIVED', TRANSITION_RULE: 'TRANSITION_RULE',
});
export const SignalType = Object.freeze({
  DEVIATION_STATUS:'DEVIATION_STATUS', RULE_STATUS:'RULE_STATUS',
  ATTRIBUTION_STATUS:'ATTRIBUTION_STATUS', FLOW_EXCEPTION_STATUS:'FLOW_EXCEPTION_STATUS',
});
export const BindingOperator = Object.freeze({
  INHERIT_EXACT:'INHERIT_EXACT', FROM_SIGNAL:'FROM_SIGNAL',
  FROM_QUESTION_CONTRACT:'FROM_QUESTION_CONTRACT', REGISTERED_CONSTANT:'REGISTERED_CONSTANT',
});
export const ProgressType = Object.freeze({
  RESOLVE_OBJECTIVE:'RESOLVE_OBJECTIVE', ADD_REQUIRED_CLAIM:'ADD_REQUIRED_CLAIM', TEST_PERSISTENCE:'TEST_PERSISTENCE',
  ESTABLISH_COMPARISON:'ESTABLISH_COMPARISON', DECOMPOSE_DEVIATION:'DECOMPOSE_DEVIATION',
  VERIFY_POLICY_CONDITION:'VERIFY_POLICY_CONDITION', LOCALIZE_EXCEPTION:'LOCALIZE_EXCEPTION', REDUCE_RESIDUAL:'REDUCE_RESIDUAL',
});
export const ProtocolStatus = Object.freeze({
  GROUNDING: 'GROUNDING', AWAITING_SELECTION: 'AWAITING_SELECTION', EXECUTING: 'EXECUTING',
  ASSESSING: 'ASSESSING', COMPLETE: 'COMPLETE', TERMINAL_PARTIAL: 'TERMINAL_PARTIAL',
});
export const ExecutionAttemptStatus = Object.freeze({
  AUTHORIZED: 'AUTHORIZED', RUNNING: 'RUNNING', SUCCEEDED: 'SUCCEEDED',
  FAILED_RETRYABLE: 'FAILED_RETRYABLE', FAILED_FINAL: 'FAILED_FINAL',
  TIMED_OUT: 'TIMED_OUT', CANCELLED: 'CANCELLED',
});
export const TechnicalErrorClass = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR', EXECUTOR_ERROR: 'EXECUTOR_ERROR',
  MOTOR_ERROR: 'MOTOR_ERROR', TIMEOUT: 'TIMEOUT', CANCELLED: 'CANCELLED',
  UNEXPECTED_RESULT_SHAPE: 'UNEXPECTED_RESULT_SHAPE',
});
export const EvidenceAdmissionStatus = Object.freeze({ ADMITTED: 'ADMITTED', REJECTED: 'REJECTED' });
export const EvidenceAdmissionPredicate = Object.freeze([
  'EXECUTION_SUCCEEDED','AUTHORIZATION_VALID','CAPABILITY_EXACT','EXECUTION_FINGERPRINT_EXACT',
  'PROTOCOL_EXACT','GOAL_VALID','ACTION_PROVENANCE_VALID','SUBJECT_EXACT','MEASURE_EXACT',
  'COMMERCIAL_UNIVERSE_EXACT','ORGANIZATION_SCOPE_EXACT','PERIOD_EXACT','GRAIN_EXACT',
  'COMPARISON_EXACT','CONSTRAINTS_PRESERVED','AUTHORITY_REFS_VALID','AVAILABILITY_EXACT',
  'COVERAGE_SUFFICIENT','COMPARABILITY_SUFFICIENT','CLAIMS_AUTHORIZED','CLAIM_SCHEMA_VALID',
  'RAW_PAYLOAD_ABSENT','SUPPORTED_INFERENCE_ONLY','EVIDENCE_UNIQUE','EVIDENCE_CURRENT',
]);
export const EvidenceAdmissionReason = Object.freeze([
  'EXECUTION_NOT_SUCCEEDED','AUTHORIZATION_INVALID','CAPABILITY_MISMATCH',
  'EXECUTION_FINGERPRINT_MISMATCH','PROTOCOL_MISMATCH','GOAL_MISMATCH',
  'ACTION_PROVENANCE_INVALID','SUBJECT_MISMATCH','MEASURE_MISMATCH','UNIVERSE_MISMATCH',
  'ORGANIZATION_SCOPE_MISMATCH','PERIOD_MISMATCH','GRAIN_MISMATCH','COMPARISON_MISMATCH',
  'CONSTRAINT_MISMATCH','AUTHORITY_MISMATCH','AVAILABILITY_MISMATCH','COVERAGE_INSUFFICIENT',
  'COMPARABILITY_INSUFFICIENT','CLAIM_NOT_AUTHORIZED','CLAIM_SCHEMA_INVALID',
  'RAW_PAYLOAD_FORBIDDEN','UNSUPPORTED_INFERENCE','DUPLICATE_EVIDENCE','STALE_EVIDENCE',
  'SUPERSEDED_EVIDENCE','CONFLICTING_EVIDENCE',
]);
export const ApplicabilityPredicate = Object.freeze([
  'GOAL_TYPE_SUPPORTED','CLAIM_INTERSECTION','ENTITY_TYPE_SUPPORTED','IDENTITY_RESOLVED',
  'IDENTITY_AUTHORITY_VALID','COMMERCIAL_UNIVERSE_EXACT','MEMBERSHIP_CERTIFIED',
  'ORGANIZATION_SCOPE_EXACT','ORGANIZATION_AUTHORITY_VALID','MEASURE_SUPPORTED',
  'PERIOD_SUPPORTED','REQUESTED_PERIOD_PRESERVED','TEMPORAL_AUTHORITY_VALID','GRAIN_SUPPORTED',
  'COMPARISON_SUPPORTED','REQUIRED_SOURCE_AVAILABLE','DATA_STATUS_ACCEPTABLE',
  'TEMPORAL_COVERAGE_MET','MINIMUM_COVERAGE_MET','COMPARABILITY_MET',
  'EXPLICIT_CONSTRAINTS_SUPPORTED','NO_SEMANTIC_SUBSTITUTION',
]);
export const ApplicabilityReason = Object.freeze([
  'GOAL_UNSUPPORTED','CLAIM_UNSUPPORTED','ENTITY_TYPE_UNSUPPORTED','IDENTITY_UNRESOLVED',
  'IDENTITY_AUTHORITY_MISSING','UNIVERSE_UNSUPPORTED','MEMBERSHIP_UNCERTIFIED',
  'ORGANIZATION_SCOPE_UNSUPPORTED','ORGANIZATION_AUTHORITY_MISSING','MEASURE_UNSUPPORTED',
  'PERIOD_UNSUPPORTED','TEMPORAL_AUTHORITY_MISSING','GRAIN_UNSUPPORTED',
  'COMPARISON_UNSUPPORTED','SOURCE_UNAVAILABLE','DATA_STATUS_UNSUPPORTED','COVERAGE_INSUFFICIENT',
  'COMPARABILITY_INSUFFICIENT','CONSTRAINT_UNSUPPORTED','SEMANTIC_SUBSTITUTION_REQUIRED',
]);
export const ResolutionStatus = Object.freeze({
  RESOLVED: 'RESOLVED', UNRESOLVED: 'UNRESOLVED', AMBIGUOUS: 'AMBIGUOUS',
  NOT_FOUND: 'NOT_FOUND', NOT_AUTHORIZED: 'NOT_AUTHORIZED', UNSUPPORTED: 'UNSUPPORTED',
});
export const Certification = Object.freeze({ CERTIFIED: 'CERTIFIED', UNCERTIFIED: 'UNCERTIFIED' });

export const AuthorityType = Object.freeze({
  PRODUCT_MASTER: 'PRODUCT_MASTER', PERSON_MASTER: 'PERSON_MASTER', STORE_MASTER: 'STORE_MASTER',
  SALES_UNIVERSE: 'SALES_UNIVERSE', RVM_UNIVERSE: 'RVM_UNIVERSE', CRM_AUTHORITY: 'CRM_AUTHORITY',
  TEMPORAL_POLICY: 'TEMPORAL_POLICY',
});

export const PHYSICAL_FIELDS = new Set([
  'capability', 'capability_id', 'capability_name', 'capability_contract_ref', 'motor', 'engine',
  'table', 'table_name', 'sql', 'physical_request', 'request_projector', 'request_projector_ref',
  'private_request', 'execution_input', 'physical_input', 'executor', 'physical_executor_ref',
  'execution_authorization', 'applicability_reasoning',
]);

export const SYNTHESIS_FORBIDDEN_FIELDS = new Set([
  ...PHYSICAL_FIELDS, 'raw', 'raw_payload', 'motor_payload', 'evidence_ledger', 'rejected_evidence',
  'applicability_decision', 'applicability_decision_ref', 'proof', 'proof_steps', 'execution_fingerprint',
]);
