BEGIN;

ALTER TABLE personas_master ADD COLUMN IF NOT EXISTS rut_normalizado text;
ALTER TABLE personas_master ADD COLUMN IF NOT EXISTS rut_dv text;
ALTER TABLE personas_master ADD COLUMN IF NOT EXISTS email_corporativo text;
CREATE UNIQUE INDEX IF NOT EXISTS uq_personas_master_rut ON personas_master(rut_normalizado) WHERE rut_normalizado IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_personas_master_email ON personas_master(lower(email_corporativo)) WHERE email_corporativo IS NOT NULL;

CREATE TABLE IF NOT EXISTS persona_roles (
 persona_role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 persona_id bigint NOT NULL REFERENCES personas_master(persona_id),
 rol text NOT NULL CHECK (rol IN ('VENDEDOR_TIENDA','SUPERVISOR_TIENDA','SUPERVISOR_DEALER')),
 vigente boolean NOT NULL DEFAULT true,
 valid_from date,
 valid_to date,
 fuente text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_persona_role_vigente ON persona_roles(persona_id,rol) WHERE vigente;

CREATE TABLE IF NOT EXISTS persona_sucursal (
 persona_sucursal_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 persona_id bigint NOT NULL REFERENCES personas_master(persona_id),
 sucursal_id bigint NOT NULL REFERENCES sucursales_master(sucursal_id),
 rol text NOT NULL CHECK (rol IN ('VENDEDOR_TIENDA','SUPERVISOR_TIENDA')),
 vigente boolean NOT NULL DEFAULT true,
 valid_from date,
 valid_to date,
 fuente text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_persona_sucursal_vigente ON persona_sucursal(persona_id,sucursal_id,rol) WHERE vigente;

CREATE TABLE IF NOT EXISTS persona_estado_comercial (
 persona_id bigint PRIMARY KEY REFERENCES personas_master(persona_id),
 vigente_fuerza_venta boolean NOT NULL,
 as_of_date date NOT NULL,
 fuente text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);

-- La nómina corporativa recibida en 2026-08-28 es la autoridad para la fuerza de venta directa vigente.
-- No se infiere rol organizacional desde la existencia de ventas en RAW.
-- Supervisores dealer se obtienen de dealer_supervisor.
-- Personas históricas permanecen en personas_master aunque no estén vigentes.
-- JENIFFER/Antofagasta se excluye de la nómina canónica: sin RUT, correo ni identidad asociable.
-- AMORENO es una sola persona. Plaza Sur queda histórica hasta 2026-06-30 y Plaza Norte vigente.

INSERT INTO persona_roles(persona_id,rol,vigente,fuente)
SELECT DISTINCT persona_id,'SUPERVISOR_DEALER',true,'dealer_supervisor'
FROM dealer_supervisor WHERE vigente
ON CONFLICT DO NOTHING;

INSERT INTO persona_sucursal(persona_id,sucursal_id,rol,vigente,valid_to,fuente)
SELECT p.persona_id,s.sucursal_id,'VENDEDOR_TIENDA',false,DATE '2026-06-30','nomina_cidef_2026_06 + vehiculos_raw'
FROM personas_master p CROSS JOIN sucursales_master s
WHERE p.usuario_canonico='AMORENO' AND s.id_sucursal_vta='33'
AND NOT EXISTS (SELECT 1 FROM persona_sucursal x WHERE x.persona_id=p.persona_id AND x.sucursal_id=s.sucursal_id AND x.rol='VENDEDOR_TIENDA' AND NOT x.vigente);

INSERT INTO master_conflicts(dominio,natural_key,conflict_type,evidence,status)
VALUES ('persona','JENIFFER|ANTOFAGASTA','roster_identity_unresolved',jsonb_build_object('source','Listado vendedores canal directo CIDEF-Junio 2026','reason','sin RUT, sin correo y sin evidencia asociable en RAW'),'rejected')
ON CONFLICT(dominio,natural_key,conflict_type) DO UPDATE SET evidence=excluded.evidence,status='rejected',updated_at=now();

COMMIT;
