BEGIN;

CREATE TABLE IF NOT EXISTS marcas_master_v01 (
  marca_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_canonico text NOT NULL,
  nombre_normalizado text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS modelos_master_v01 (
  modelo_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marca_id bigint NOT NULL REFERENCES marcas_master_v01(marca_id),
  nombre_canonico text NOT NULL,
  nombre_normalizado text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (marca_id, nombre_normalizado)
);

CREATE TABLE IF NOT EXISTS versiones_master_v01 (
  version_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modelo_id bigint NOT NULL REFERENCES modelos_master_v01(modelo_id),
  nombre_canonico text NOT NULL,
  nombre_normalizado text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (modelo_id, nombre_normalizado)
);

CREATE TABLE IF NOT EXISTS producto_aliases_v01 (
  alias_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nivel text NOT NULL CHECK (nivel IN ('MARCA','MODELO','VERSION')),
  fuente text NOT NULL,
  valor_raw text NOT NULL,
  valor_normalizado text NOT NULL,
  contexto_marca_raw text,
  contexto_modelo_raw text,
  marca_id bigint REFERENCES marcas_master_v01(marca_id),
  modelo_id bigint REFERENCES modelos_master_v01(modelo_id),
  version_id bigint REFERENCES versiones_master_v01(version_id),
  evidencia_tipo text,
  evidencia_count bigint,
  primera_observacion date,
  ultima_observacion date,
  estado text NOT NULL CHECK (estado IN ('RESUELTO','AMBIGUO','RECHAZADO')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_producto_alias_v01 ON producto_aliases_v01 (
  nivel, fuente, coalesce(contexto_marca_raw,''), coalesce(contexto_modelo_raw,''),
  valor_normalizado, coalesce(marca_id,0), coalesce(modelo_id,0), coalesce(version_id,0)
);

CREATE TABLE IF NOT EXISTS producto_clasificacion_v01 (
  clasificacion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marca_id bigint REFERENCES marcas_master_v01(marca_id),
  modelo_id bigint REFERENCES modelos_master_v01(modelo_id),
  version_id bigint REFERENCES versiones_master_v01(version_id),
  taxonomia text NOT NULL,
  valor text NOT NULL,
  fuente text NOT NULL,
  valid_from date,
  valid_to date,
  estado text NOT NULL CHECK (estado IN ('OBSERVADO','CERTIFICADO','AMBIGUO','RECHAZADO')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS producto_portafolio_v01 (
  portafolio_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marca_id bigint NOT NULL REFERENCES marcas_master_v01(marca_id),
  modelo_id bigint NOT NULL REFERENCES modelos_master_v01(modelo_id),
  version_id bigint NOT NULL REFERENCES versiones_master_v01(version_id),
  organizacion text NOT NULL,
  valid_from date NOT NULL,
  valid_to date,
  vigente boolean NOT NULL,
  fuente text NOT NULL,
  documento_origen text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_producto_portafolio_v01_vigente
  ON producto_portafolio_v01(organizacion, version_id)
  WHERE vigente;

COMMIT;
