BEGIN;

CREATE TABLE IF NOT EXISTS generaciones_master_v01 (
  generation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id bigint NOT NULL REFERENCES modelos_master_v01(modelo_id),
  nombre_canonico text NOT NULL,
  nombre_normalizado text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (model_id, nombre_normalizado)
);

CREATE TABLE IF NOT EXISTS version_generation_v01 (
  version_id bigint PRIMARY KEY REFERENCES versiones_master_v01(version_id) ON DELETE CASCADE,
  generation_id bigint REFERENCES generaciones_master_v01(generation_id) ON DELETE RESTRICT,
  status text NOT NULL CHECK (status IN ('RESOLVED','UNRESOLVED','CONFLICT')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (status = 'RESOLVED' AND generation_id IS NOT NULL)
    OR (status IN ('UNRESOLVED','CONFLICT') AND generation_id IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS generation_evidence_v01 (
  evidence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  source_external_generation_id text NOT NULL,
  source_external_modification_id text,
  generation_id bigint REFERENCES generaciones_master_v01(generation_id) ON DELETE CASCADE,
  version_id bigint REFERENCES versiones_master_v01(version_id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (generation_id IS NOT NULL OR version_id IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_generation_evidence_v01
  ON generation_evidence_v01 (
    source,
    source_external_generation_id,
    coalesce(source_external_modification_id, ''),
    coalesce(generation_id, 0),
    coalesce(version_id, 0)
  );

CREATE OR REPLACE FUNCTION validate_version_generation_model_v01()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  version_model_id bigint;
  generation_model_id bigint;
BEGIN
  IF NEW.status <> 'RESOLVED' THEN RETURN NEW; END IF;

  SELECT modelo_id INTO version_model_id
  FROM versiones_master_v01 WHERE version_id = NEW.version_id;

  SELECT model_id INTO generation_model_id
  FROM generaciones_master_v01 WHERE generation_id = NEW.generation_id;

  IF version_model_id IS DISTINCT FROM generation_model_id THEN
    RAISE EXCEPTION 'VERSION and GENERATION must belong to the same MODEL';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_version_generation_model_v01 ON version_generation_v01;
CREATE TRIGGER trg_validate_version_generation_model_v01
BEFORE INSERT OR UPDATE ON version_generation_v01
FOR EACH ROW EXECUTE FUNCTION validate_version_generation_model_v01();

CREATE OR REPLACE FUNCTION ensure_version_generation_state_v01()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO version_generation_v01(version_id, generation_id, status)
  VALUES (NEW.version_id, NULL, 'UNRESOLVED')
  ON CONFLICT (version_id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ensure_version_generation_state_v01 ON versiones_master_v01;
CREATE TRIGGER trg_ensure_version_generation_state_v01
AFTER INSERT ON versiones_master_v01
FOR EACH ROW EXECUTE FUNCTION ensure_version_generation_state_v01();

INSERT INTO version_generation_v01(version_id, generation_id, status)
SELECT version_id, NULL, 'UNRESOLVED'
FROM versiones_master_v01
ON CONFLICT (version_id) DO NOTHING;

COMMIT;
