BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS producto_atributos_fisicos_v01 (
  atributo_fisico_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modelo_id bigint REFERENCES modelos_master_v01(modelo_id),
  version_id bigint REFERENCES versiones_master_v01(version_id),
  attribute text NOT NULL,
  value numeric NOT NULL,
  unit text NOT NULL DEFAULT 'mm',
  source_type text NOT NULL,
  source_reference text NOT NULL,
  observed_at timestamptz NOT NULL,
  valid_from date NOT NULL,
  valid_to date,
  status text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((modelo_id IS NOT NULL) <> (version_id IS NOT NULL)),
  CHECK (attribute IN ('length_mm','wheelbase_mm')),
  CHECK (value > 0),
  CHECK (unit = 'mm'),
  CHECK (source_type IN (
    'HOMOLOGATION','MANUFACTURER_CHILE',
    'MANUFACTURER_GLOBAL','STRUCTURED_EXTERNAL'
  )),
  CHECK (status IN ('CERTIFIED','CONFLICT','SUPERSEDED')),
  CHECK (valid_to IS NULL OR valid_to > valid_from)
);

ALTER TABLE producto_atributos_fisicos_v01
  ADD CONSTRAINT ex_atributo_fisico_model_certified
  EXCLUDE USING gist (
    modelo_id WITH =,
    attribute WITH =,
    daterange(valid_from, COALESCE(valid_to, 'infinity'::date), '[)') WITH &&
  ) WHERE (status = 'CERTIFIED' AND modelo_id IS NOT NULL);

ALTER TABLE producto_atributos_fisicos_v01
  ADD CONSTRAINT ex_atributo_fisico_version_certified
  EXCLUDE USING gist (
    version_id WITH =,
    attribute WITH =,
    daterange(valid_from, COALESCE(valid_to, 'infinity'::date), '[)') WITH &&
  ) WHERE (status = 'CERTIFIED' AND version_id IS NOT NULL);

CREATE OR REPLACE FUNCTION validate_atributo_fisico_cross_grain_v01()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  parent_modelo_id bigint;
  new_period daterange;
  has_conflict boolean;
BEGIN
  IF NEW.status <> 'CERTIFIED' THEN RETURN NEW; END IF;

  IF NEW.modelo_id IS NOT NULL THEN
    parent_modelo_id := NEW.modelo_id;
  ELSE
    SELECT modelo_id INTO parent_modelo_id
    FROM versiones_master_v01 WHERE version_id = NEW.version_id;
  END IF;

  PERFORM 1 FROM modelos_master_v01
  WHERE modelo_id = parent_modelo_id FOR UPDATE;

  new_period := daterange(
    NEW.valid_from, COALESCE(NEW.valid_to, 'infinity'::date), '[)'
  );

  IF NEW.modelo_id IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1
      FROM producto_atributos_fisicos_v01 a
      JOIN versiones_master_v01 v ON v.version_id = a.version_id
      WHERE a.status = 'CERTIFIED'
        AND v.modelo_id = parent_modelo_id
        AND a.attribute = NEW.attribute
        AND daterange(a.valid_from, COALESCE(a.valid_to, 'infinity'::date), '[)') && new_period
        AND a.atributo_fisico_id <> COALESCE(NEW.atributo_fisico_id, -1)
    ) INTO has_conflict;
  ELSE
    SELECT EXISTS (
      SELECT 1 FROM producto_atributos_fisicos_v01 a
      WHERE a.status = 'CERTIFIED'
        AND a.modelo_id = parent_modelo_id
        AND a.attribute = NEW.attribute
        AND daterange(a.valid_from, COALESCE(a.valid_to, 'infinity'::date), '[)') && new_period
        AND a.atributo_fisico_id <> COALESCE(NEW.atributo_fisico_id, -1)
    ) INTO has_conflict;
  END IF;

  IF has_conflict THEN
    RAISE EXCEPTION 'CERTIFIED physical attribute overlaps MODEL/VERSION grain';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_atributo_fisico_cross_grain_v01
  ON producto_atributos_fisicos_v01;
CREATE TRIGGER trg_atributo_fisico_cross_grain_v01
BEFORE INSERT OR UPDATE ON producto_atributos_fisicos_v01
FOR EACH ROW EXECUTE FUNCTION validate_atributo_fisico_cross_grain_v01();

CREATE INDEX IF NOT EXISTS idx_atributo_fisico_model
  ON producto_atributos_fisicos_v01(modelo_id, attribute)
  WHERE modelo_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_atributo_fisico_version
  ON producto_atributos_fisicos_v01(version_id, attribute)
  WHERE version_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_atributo_fisico_status
  ON producto_atributos_fisicos_v01(status);

COMMIT;
