import { createAction, validateGoalInstance } from '../contracts.js';
import { clone } from '../primitives.js';
import { validateInitialGoalCandidate } from './contracts.js';
import { validateCandidateGoal } from '../investigation/contracts.js';

function publicBindings(binding,source){return {subject:binding.subject.canonical_label,measure:binding.measure,commercial_universe:binding.commercial_universe,organization_scope:binding.organization_scope,period:clone(binding.period),grain:binding.grain,...(source.comparison?{comparison:source.comparison}:{}),...(source.explicit_constraints?{explicit_constraints:clone(source.explicit_constraints)}:{})};}
function actionId(target,fingerprint){return `action_${target}_${fingerprint.slice(-12)}`;}
function limitations(binding,availability){const sales=availability.sources.find(item=>item.source_domain==='SALES');return sales&&sales.coverage.status!=='FULL'&&binding.measure==='VIN_SALES'?['REQUESTED_PERIOD_NOT_FULLY_COVERED']:[];}

export function actionForGoal({protocol_id,issued_state_version,goal,availability}){validateGoalInstance(goal);const draft={contract_version:'action.v1',action_id:'pending',protocol_id,issued_state_version,goal_id:goal.goal_id,goal_type:goal.goal_type,evidence_class:goal.evidence_class,semantic_label:goal.goal_type==='OBSERVED_RESULT'?'OBSERVE_SALES_RESULT':`PURSUE_${goal.goal_type}`,description:'Select this bounded semantic objective for later physical assessment.',public_bindings:publicBindings(goal.bindings,goal),expected_contribution:goal.goal_type==='OBSERVED_RESULT'?['OBSERVED_VALUE']:[goal.goal_type],limitations:limitations(goal.bindings,availability)};const semantic=createAction(draft);draft.action_id=actionId('goal',semantic.action_fingerprint);return createAction(draft);}
export function actionForCandidate({protocol_id,issued_state_version,candidate,availability}){validateInitialGoalCandidate(candidate);const draft={contract_version:'action.v1',action_id:'pending',protocol_id,issued_state_version,candidate_id:candidate.candidate_id,goal_type:candidate.goal_type,evidence_class:candidate.evidence_class_if_selected,semantic_label:candidate.semantic_label,description:candidate.description,public_bindings:publicBindings(candidate.bindings,candidate),expected_contribution:clone(candidate.expected_claim_types),limitations:[...clone(candidate.limitations),...limitations(candidate.bindings,availability)]};const semantic=createAction(draft);draft.action_id=actionId('candidate',semantic.action_fingerprint);return createAction(draft);}
export function actionForTransitionCandidate({protocol_id,issued_state_version,candidate,availability}){validateCandidateGoal(candidate);const draft={contract_version:'action.v1',action_id:'pending',protocol_id,issued_state_version,candidate_id:candidate.candidate_id,goal_type:candidate.goal_type,evidence_class:candidate.evidence_class,semantic_label:`INVESTIGATE_${candidate.progress_type}`,description:'Select this bounded semantic investigation for later physical assessment.',public_bindings:publicBindings(candidate.semantic_binding,{}),expected_contribution:clone(candidate.expected_contribution),limitations:limitations(candidate.semantic_binding,availability)};const semantic=createAction(draft);draft.action_id=actionId('transition',semantic.action_fingerprint);return createAction(draft);}
export function generateActions({protocol_id,issued_state_version,goals,candidates,availability}){return goals.length?goals.filter(item=>item.status==='PENDING').map(goal=>actionForGoal({protocol_id,issued_state_version,goal,availability})):candidates.map(candidate=>actionForCandidate({protocol_id,issued_state_version,candidate,availability}));}
