import { validateAction } from '../contracts.js';
import { clone, fingerprint, invariant } from '../primitives.js';
import { generateActions } from './actions.js';
import { activateCandidate, compileInitialGoals } from './compiler.js';
import { createProtocolState, validateProtocolState, validateSelectActionCommand } from './contracts.js';

function clockValue(clock){const value=typeof clock==='function'?clock():clock;const instant=new Date(value);invariant(Number.isFinite(instant.getTime()),'CLOCK_REQUIRED','$.clock');return instant.toISOString();}
function referenceId(value,fallback){return value??fallback;}

export function initializeProtocol({questionContract,universeResolution,availabilitySnapshot,budget={max_semantic_selections:4,semantic_selections_used:0,max_depth:4},clock,protocol_id}){
  const now=clockValue(clock);const compiled=compileInitialGoals({questionContract,universeResolution,availabilitySnapshot});const id=protocol_id??`protocol_${questionContract.question_contract_hash.slice(-16)}`;const actions=generateActions({protocol_id:id,issued_state_version:1,goals:compiled.goals,candidates:compiled.candidates,availability:availabilitySnapshot});
  return createProtocolState({contract_version:'protocol_state.v1',protocol_id:id,protocol_version:1,state_version:1,status:'AWAITING_SELECTION',question_contract_ref:questionContract.question_id,question_contract_hash:questionContract.question_contract_hash,universe_resolution_ref:referenceId(universeResolution.resolution_id,universeResolution.resolution_fingerprint),universe_resolution_fingerprint:universeResolution.resolution_fingerprint,availability_snapshot_ref:availabilitySnapshot.snapshot_id,availability_snapshot_fingerprint:availabilitySnapshot.snapshot_fingerprint,goals:compiled.goals,initial_goal_candidates:compiled.candidates,open_obligations:compiled.goals.map(item=>item.goal_id),actions,selected_action_ref:{status:'OMITTED'},pending_execution_objective:{status:'OMITTED'},physical_authorization_refs:[],consumed_action_fingerprints:[],budget:clone(budget),terminal:{status:'OPEN',reason_codes:[]},previous_state_hash:'GENESIS',created_at:now,updated_at:now});
}

export function selectAction(state,command,{clock}){
  validateProtocolState(state);validateSelectActionCommand(command);invariant(command.protocol_id===state.protocol_id,'PROTOCOL_MISMATCH','$.protocol_id');invariant(command.expected_state_version===state.state_version,'STALE_STATE_VERSION','$.expected_state_version');invariant(state.status==='AWAITING_SELECTION','INVALID_STATE_TRANSITION','$.status');invariant(state.budget.semantic_selections_used<state.budget.max_semantic_selections,'SEMANTIC_BUDGET_EXHAUSTED','$.budget');
  const action=state.actions.find(item=>item.action_id===command.action_id);invariant(action,'UNKNOWN_ACTION','$.action_id');validateAction(action);invariant(action.issued_state_version===state.state_version,'STALE_ACTION_STATE_VERSION','$.action_id');invariant(action.action_fingerprint===command.action_fingerprint,'ACTION_FINGERPRINT_MISMATCH','$.action_fingerprint');invariant(!state.consumed_action_fingerprints.includes(action.action_fingerprint),'ACTION_ALREADY_CONSUMED','$.action_id');
  let goals=clone(state.goals),candidates=clone(state.initial_goal_candidates),goal;if(action.candidate_id){const candidate=candidates.find(item=>item.candidate_id===action.candidate_id);invariant(candidate,'UNKNOWN_GOAL_CANDIDATE','$.candidate_id');goal=activateCandidate(candidate,{questionContractRef:state.question_contract_hash,universeResolutionRef:state.universe_resolution_fingerprint});goals=[...goals,goal];candidates=[];}else{goal=goals.find(item=>item.goal_id===action.goal_id);invariant(goal,'ACTION_GOAL_MISMATCH','$.goal_id');}
  const now=clockValue(clock),objective={status:'PENDING',goal_id:goal.goal_id,goal_fingerprint:goal.goal_fingerprint,semantic_label:action.semantic_label,selected_action_fingerprint:action.action_fingerprint};objective.objective_fingerprint=fingerprint({goal_fingerprint:objective.goal_fingerprint,semantic_label:objective.semantic_label,selected_action_fingerprint:objective.selected_action_fingerprint});return createProtocolState({...clone(state),state_version:state.state_version+1,status:'AWAITING_SELECTION',goals,initial_goal_candidates:candidates,open_obligations:[goal.goal_id],actions:[],selected_action_ref:{action_id:action.action_id,action_fingerprint:action.action_fingerprint,selected_at:now,source_state_version:state.state_version},pending_execution_objective:objective,consumed_action_fingerprints:[...state.consumed_action_fingerprints,action.action_fingerprint],budget:{...clone(state.budget),semantic_selections_used:state.budget.semantic_selections_used+1},terminal:{status:'OPEN',reason_codes:[]},previous_state_hash:state.state_hash,updated_at:now,state_hash:undefined});
}
