import { validateAvailabilitySnapshot, validateGoalInstance, validateUniverseResolution } from '../contracts.js';
import { ApplicabilityPredicate, ApplicabilityStatus } from '../enums.js';
import { clone, deepFreeze } from '../primitives.js';
import { createApplicabilityDecisionV2, validateNativeCapabilityContract } from './contracts.js';

const REASON=Object.freeze({GOAL_TYPE_SUPPORTED:'GOAL_UNSUPPORTED',CLAIM_INTERSECTION:'CLAIM_UNSUPPORTED',ENTITY_TYPE_SUPPORTED:'ENTITY_TYPE_UNSUPPORTED',IDENTITY_RESOLVED:'IDENTITY_UNRESOLVED',IDENTITY_AUTHORITY_VALID:'IDENTITY_AUTHORITY_MISSING',COMMERCIAL_UNIVERSE_EXACT:'UNIVERSE_UNSUPPORTED',MEMBERSHIP_CERTIFIED:'MEMBERSHIP_UNCERTIFIED',ORGANIZATION_SCOPE_EXACT:'ORGANIZATION_SCOPE_UNSUPPORTED',ORGANIZATION_AUTHORITY_VALID:'ORGANIZATION_AUTHORITY_MISSING',MEASURE_SUPPORTED:'MEASURE_UNSUPPORTED',PERIOD_SUPPORTED:'PERIOD_UNSUPPORTED',REQUESTED_PERIOD_PRESERVED:'SEMANTIC_SUBSTITUTION_REQUIRED',TEMPORAL_AUTHORITY_VALID:'TEMPORAL_AUTHORITY_MISSING',GRAIN_SUPPORTED:'GRAIN_UNSUPPORTED',COMPARISON_SUPPORTED:'COMPARISON_UNSUPPORTED',REQUIRED_SOURCE_AVAILABLE:'SOURCE_UNAVAILABLE',DATA_STATUS_ACCEPTABLE:'DATA_STATUS_UNSUPPORTED',TEMPORAL_COVERAGE_MET:'COVERAGE_INSUFFICIENT',MINIMUM_COVERAGE_MET:'COVERAGE_INSUFFICIENT',COMPARABILITY_MET:'COMPARABILITY_INSUFFICIENT',EXPLICIT_CONSTRAINTS_SUPPORTED:'CONSTRAINT_UNSUPPORTED',NO_SEMANTIC_SUBSTITUTION:'SEMANTIC_SUBSTITUTION_REQUIRED'});
const COST={LOW:3,MEDIUM:2,HIGH:1},LATENCY={LOW:3,MEDIUM:2,HIGH:1};
function contains(ref,period){return ref?.effective_period?.date_from<=period.date_from&&ref?.effective_period?.date_to>=period.date_to;}
function samePeriod(left,right){return left?.date_from===right?.date_from&&left?.date_to===right?.date_to&&left?.period_status===right?.period_status;}
function result(predicate,passed){return passed?{predicate,passed:true}:{predicate,passed:false,reason_code:REASON[predicate]};}

export function evaluateNativeApplicability({goal,capabilityContract:capability,universeResolution:resolution,availabilitySnapshot:availability,decision_id}){
  validateGoalInstance(goal);validateNativeCapabilityContract(capability);validateUniverseResolution(resolution);validateAvailabilitySnapshot(availability);const b=goal.bindings,s=capability.supported_bindings,claims=capability.satisfies.claim_types.filter(item=>capability.evidence.authorized_claim_types.includes(item));const org=resolution.membership.organization_scope;const source=availability.sources.find(item=>item.source_domain===capability.availability_requirements.source_domain);const comparison=goal.comparison??'NONE',constraints=goal.explicit_constraints??[];
  const checks={GOAL_TYPE_SUPPORTED:capability.satisfies.goal_types.includes(goal.goal_type),CLAIM_INTERSECTION:claims.length>0,ENTITY_TYPE_SUPPORTED:s.entity_types.includes(b.subject.entity_type),IDENTITY_RESOLVED:resolution.subject.resolution_status==='RESOLVED'&&resolution.subject.canonical_id===b.subject.canonical_id,IDENTITY_AUTHORITY_VALID:resolution.coverage.identity==='CERTIFIED'&&resolution.authority.identity_ref.authority_fingerprint===b.subject.authority_ref&&contains(resolution.authority.identity_ref,b.period),COMMERCIAL_UNIVERSE_EXACT:s.commercial_universes.includes(b.commercial_universe)&&resolution.membership.commercial_universe===b.commercial_universe,MEMBERSHIP_CERTIFIED:resolution.membership.membership_status==='RESOLVED'&&resolution.coverage.membership==='CERTIFIED'&&resolution.authority.membership_refs.length>0,ORGANIZATION_SCOPE_EXACT:s.organization_scopes.includes(b.organization_scope)&&org.status==='BOUND'&&org.value===b.organization_scope,ORGANIZATION_AUTHORITY_VALID:!capability.authority_requirements.organization_scope||(resolution.authority.membership_refs.length>0&&resolution.authority.membership_refs.every(ref=>contains(ref,b.period))),MEASURE_SUPPORTED:s.measures.includes(b.measure),PERIOD_SUPPORTED:s.period_units.includes(b.period.unit)&&s.period_statuses.includes(b.period.period_status)&&s.period_alignments.includes(b.period.alignment),REQUESTED_PERIOD_PRESERVED:resolution.temporal.date_from===b.period.date_from&&resolution.temporal.date_to===b.period.date_to&&resolution.temporal.period_status===b.period.period_status&&samePeriod(availability.requested_period,b.period),TEMPORAL_AUTHORITY_VALID:!capability.authority_requirements.temporal||(resolution.coverage.temporal==='CERTIFIED'&&contains(resolution.authority.temporal_ref,b.period)),GRAIN_SUPPORTED:s.grains.includes(b.grain)&&resolution.grain.resolved===b.grain,COMPARISON_SUPPORTED:s.comparisons.includes(comparison),REQUIRED_SOURCE_AVAILABLE:Boolean(source&&source.data_status!=='UNAVAILABLE'),DATA_STATUS_ACCEPTABLE:Boolean(source&&capability.availability_requirements.accepted_data_statuses.includes(source.data_status)),TEMPORAL_COVERAGE_MET:Boolean(source&&(capability.availability_requirements.required_coverage==='ANY'||source.coverage.status===capability.availability_requirements.required_coverage)&&(!capability.availability_requirements.through_period_end||source.available_to>=b.period.date_to)&&(!capability.coverage_requirements.full_closed_period_required||source.coverage.status==='FULL')),MINIMUM_COVERAGE_MET:Boolean(source&&source.coverage.ratio>=capability.availability_requirements.minimum_coverage_ratio),COMPARABILITY_MET:capability.comparability_requirements.supported_modes.includes(comparison),EXPLICIT_CONSTRAINTS_SUPPORTED:constraints.every(item=>capability.constraint_policy.supported_axes.includes(item.target_axis)),NO_SEMANTIC_SUBSTITUTION:false};
  checks.NO_SEMANTIC_SUBSTITUTION=['ENTITY_TYPE_SUPPORTED','IDENTITY_RESOLVED','COMMERCIAL_UNIVERSE_EXACT','ORGANIZATION_SCOPE_EXACT','MEASURE_SUPPORTED','PERIOD_SUPPORTED','REQUESTED_PERIOD_PRESERVED','GRAIN_SUPPORTED','COMPARISON_SUPPORTED','EXPLICIT_CONSTRAINTS_SUPPORTED'].every(key=>checks[key]);const predicate_results=ApplicabilityPredicate.map(predicate=>result(predicate,checks[predicate]));const hardFailure=predicate_results.some(item=>!item.passed);const limited=!hardFailure&&source.coverage.ratio<1&&capability.availability_requirements.limited_coverage_permitted;const status=hardFailure?ApplicabilityStatus.NOT_APPLICABLE:limited?ApplicabilityStatus.APPLICABLE_WITH_LIMITED_COVERAGE:ApplicabilityStatus.APPLICABLE;const reason_codes=[...new Set(predicate_results.filter(item=>!item.passed).map(item=>item.reason_code))];const ranking={claim_coverage:claims.length,exact_binding:checks.NO_SEMANTIC_SUBSTITUTION?1:0,authority:['IDENTITY_AUTHORITY_VALID','MEMBERSHIP_CERTIFIED','ORGANIZATION_AUTHORITY_VALID','TEMPORAL_AUTHORITY_VALID'].filter(key=>checks[key]).length,comparability:checks.COMPARABILITY_MET?1:0,coverage:source?Math.round(source.coverage.ratio*1000000):0,data_status:checks.DATA_STATUS_ACCEPTABLE?1:0,transformation_distance:capability.selection_metadata.semantic_transformation_distance,specialization:capability.selection_metadata.specialization,cost_rank:COST[capability.selection_metadata.cost_class],latency_rank:LATENCY[capability.selection_metadata.latency_class]};return createApplicabilityDecisionV2({contract_version:'applicability_decision.v2',decision_id:decision_id??`decision_${goal.goal_fingerprint.slice(-8)}_${capability.contract_fingerprint.slice(-8)}`,goal_ref:goal.goal_fingerprint,capability_contract_ref:capability.contract_fingerprint,universe_resolution_ref:resolution.resolution_fingerprint,availability_snapshot_ref:availability.snapshot_fingerprint,status,predicate_results,reason_codes,authorized_claim_types:status==='NOT_APPLICABLE'?[]:claims,ranking});
}

export function evaluateCapabilityCatalog(input){return deepFreeze([...input.capabilityContracts].sort((a,b)=>a.capability_id.localeCompare(b.capability_id)).map(capabilityContract=>evaluateNativeApplicability({...input,capabilityContract})));}
export function cloneApplicability(value){return clone(value);}
