import { invariant } from '../primitives.js';
import { createNativeCapabilityContract, validateNativeCapabilityContract } from './contracts.js';

export const LONGITUDINAL_VENTAS_NATIVE_CAPABILITY=createNativeCapabilityContract({
  contract_version:'capability_contract.v2',capability_id:'LONGITUDINAL/VENTAS',capability_version:'0.3',
  satisfies:{goal_types:['OBSERVED_RESULT'],claim_types:['OBSERVED_VALUE']},
  supported_bindings:{entity_types:['BRAND'],measures:['VIN_SALES'],commercial_universes:['COMPANY'],organization_scopes:['CIDEF'],period_units:['MONTH'],period_statuses:['CLOSED'],period_alignments:['CALENDAR'],grains:['BRAND'],comparisons:['NONE']},
  authority_requirements:{identity:true,membership:true,organization_scope:true,temporal:true},
  availability_requirements:{source_domain:'SALES',accepted_data_statuses:['AVAILABLE'],required_coverage:'FULL',minimum_coverage_ratio:1,through_period_end:true,limited_coverage_permitted:false},
  coverage_requirements:{full_closed_period_required:true},comparability_requirements:{required:false,supported_modes:['NONE']},constraint_policy:{mode:'PRESERVE',supported_axes:[]},
  semantic_requirements:{minimum_periods:1,exact_periods:1,reconciliation_required:false},
  physical:{executor_ref:'motor_registry.getMotor',motor_ref:'ventas_longitudinal_context_v01',input_contract_ref:'parseVentasLongitudinalInput.v0.3'},
  evidence:{authorized_claim_types:['OBSERVED_VALUE'],evidence_projector_ref:'protocol.evidence.observed_value.v1'},
  selection_metadata:{specialization:100,cost_class:'LOW',latency_class:'MEDIUM',semantic_transformation_distance:0},
});

function salesCapability({capability_id,goal_type,claim_type,entity_types=['COMPANY'],measures=['VIN_SALES'],commercial_universes=['COMPANY'],grains,motor_ref,input_contract_ref,evidence_projector_ref,comparisons=['NONE'],comparability_required=comparisons.some(item=>item!=='NONE'),minimum_periods=1,exact_periods,reconciliation_required=false,period_statuses=['CLOSED'],required_coverage='FULL',minimum_coverage_ratio=1,through_period_end=true,limited_coverage_permitted=false,specialization=90}){
  return createNativeCapabilityContract({contract_version:'capability_contract.v2',capability_id,capability_version:'1.0',satisfies:{goal_types:[goal_type],claim_types:[claim_type]},supported_bindings:{entity_types,measures,commercial_universes,organization_scopes:['CIDEF'],period_units:['MONTH'],period_statuses,period_alignments:['CALENDAR'],grains,comparisons},authority_requirements:{identity:true,membership:true,organization_scope:true,temporal:true},availability_requirements:{source_domain:'SALES',accepted_data_statuses:['AVAILABLE'],required_coverage,minimum_coverage_ratio,through_period_end,limited_coverage_permitted},coverage_requirements:{full_closed_period_required:period_statuses.includes('CLOSED')&&required_coverage==='FULL'},comparability_requirements:{required:comparability_required,supported_modes:comparisons},constraint_policy:{mode:'PRESERVE',supported_axes:[]},semantic_requirements:{minimum_periods, ...(exact_periods?{exact_periods}:{}),reconciliation_required},physical:{executor_ref:'motor_registry.getMotor',motor_ref,input_contract_ref},evidence:{authorized_claim_types:[claim_type],evidence_projector_ref},selection_metadata:{specialization,cost_class:'LOW',latency_class:'MEDIUM',semantic_transformation_distance:0}});
}

export const LONGITUDINAL_VENTAS_TRAJECTORY_NATIVE_CAPABILITY=salesCapability({capability_id:'LONGITUDINAL/VENTAS_TRAJECTORY',goal_type:'TEMPORAL_TRAJECTORY',claim_type:'TRAJECTORY_SERIES',entity_types:['BRAND','MODEL'],commercial_universes:['COMPANY','OWN_STORES','DEALERS'],grains:['BRAND','MODEL'],motor_ref:'ventas_longitudinal_context_v01',input_contract_ref:'parseVentasLongitudinalInput.v0.3',evidence_projector_ref:'protocol.evidence.ventas_trajectory.v1',comparability_required:true,minimum_periods:2,specialization:96});
export const LONGITUDINAL_VENTAS_CHANGE_NATIVE_CAPABILITY=salesCapability({capability_id:'LONGITUDINAL/VENTAS_CHANGE',goal_type:'TEMPORAL_CHANGE',claim_type:'CHANGE_VALUE',entity_types:['BRAND','MODEL'],commercial_universes:['COMPANY','OWN_STORES','DEALERS'],grains:['BRAND','MODEL'],motor_ref:'ventas_longitudinal_context_v01',input_contract_ref:'parseVentasLongitudinalInput.v0.3',evidence_projector_ref:'protocol.evidence.ventas_change.v1',comparisons:['PREVIOUS_PERIOD'],minimum_periods:2,exact_periods:2,specialization:97});
export const SALES_PRODUCT_CHANGE_CONTRIBUTION_NATIVE_CAPABILITY=salesCapability({capability_id:'SALES/PRODUCT_CHANGE_CONTRIBUTION',goal_type:'CHANGE_ATTRIBUTION',claim_type:'CHANGE_CONTRIBUTION_SET',grains:['MODEL'],motor_ref:'ventas_product_change_contribution_v01',input_contract_ref:'parseProductChangeInput.v0.1',evidence_projector_ref:'protocol.evidence.product_change_contribution.v1',comparisons:['PREVIOUS_PERIOD'],minimum_periods:2,exact_periods:2,reconciliation_required:true,specialization:95});
export const SALES_STORE_CHANGE_CONTRIBUTION_NATIVE_CAPABILITY=salesCapability({capability_id:'SALES/STORE_CHANGE_CONTRIBUTION',goal_type:'CHANGE_ATTRIBUTION',claim_type:'CHANGE_CONTRIBUTION_SET',grains:['STORE'],motor_ref:'ventas_store_change_contribution_v01',input_contract_ref:'parseStoreChangeInput.v0.1',evidence_projector_ref:'protocol.evidence.store_change_contribution.v1',comparisons:['PREVIOUS_PERIOD'],minimum_periods:2,exact_periods:2,reconciliation_required:true,specialization:95});
export const SALES_SELLER_CHANGE_CONTRIBUTION_NATIVE_CAPABILITY=salesCapability({capability_id:'SALES/SELLER_CHANGE_CONTRIBUTION',goal_type:'CHANGE_ATTRIBUTION',claim_type:'CHANGE_CONTRIBUTION_SET',grains:['SELLER'],motor_ref:'ventas_seller_change_contribution_v01',input_contract_ref:'parseSellerChangeInput.v0.1',evidence_projector_ref:'protocol.evidence.seller_change_contribution.v1',comparisons:['PREVIOUS_PERIOD'],minimum_periods:2,exact_periods:2,reconciliation_required:true,specialization:95});
export const SALES_ORGANIZATIONAL_RELATIVE_PERFORMANCE_NATIVE_CAPABILITY=salesCapability({capability_id:'SALES/ORGANIZATIONAL_RELATIVE_PERFORMANCE',goal_type:'RELATIVE_PERFORMANCE',claim_type:'RELATIVE_PERFORMANCE_VALUE',entity_types:['STORE','SELLER'],commercial_universes:['OWN_STORES'],grains:['STORE','SELLER'],motor_ref:'organizational_relative_performance_v01',input_contract_ref:'parseRelativePerformanceInput.v0.1',evidence_projector_ref:'protocol.evidence.organizational_relative_performance.v1',comparisons:['EXPECTED'],reconciliation_required:true,specialization:93});
export const SALES_DETERIORATION_STATUS_NATIVE_CAPABILITY=salesCapability({capability_id:'SALES/DETERIORATION_STATUS',goal_type:'RISK_STATUS',claim_type:'RISK_RULE_RESULT',entity_types:['STORE'],commercial_universes:['OWN_STORES'],grains:['STORE'],motor_ref:'org_sales_deterioration_status_v01',input_contract_ref:'parseDeteriorationStatusInput.v0.1',evidence_projector_ref:'protocol.evidence.deterioration_status.v1',comparisons:['EXPECTED'],exact_periods:1,reconciliation_required:true,specialization:98});
export const SALES_CURRENT_MONTH_CLOSE_FORECAST_NATIVE_CAPABILITY=salesCapability({capability_id:'SALES/CURRENT_MONTH_CLOSE_FORECAST',goal_type:'PROJECTED_RESULT',claim_type:'PROJECTED_VALUE',entity_types:['COMPANY'],commercial_universes:['OWN_STORES'],grains:['TOTAL'],motor_ref:'current_month_close_forecast_v01',input_contract_ref:'parseLiveCutoff.v0.1',evidence_projector_ref:'protocol.evidence.current_month_forecast.v1',period_statuses:['OPEN','PARTIAL'],required_coverage:'PARTIAL',minimum_coverage_ratio:0,through_period_end:false,limited_coverage_permitted:true,specialization:99});

function sourceCapability({capability_id,capability_version,goal_type,claim_type,source_domain,accepted_data_statuses,entity_types,measures,commercial_universes,organization_scopes,period_units=['MONTH'],period_statuses=['CLOSED'],grains,comparisons,motor_ref,input_contract_ref,evidence_projector_ref,minimum_periods=1,exact_periods,required_market_universe,required_geography,comparability_required=comparisons.some(item=>item!=='NONE'),specialization}){
  return createNativeCapabilityContract({contract_version:'capability_contract.v2',capability_id,capability_version,satisfies:{goal_types:[goal_type],claim_types:[claim_type]},supported_bindings:{entity_types,measures,commercial_universes,organization_scopes,period_units,period_statuses,period_alignments:['CALENDAR'],grains,comparisons},authority_requirements:{identity:true,membership:true,organization_scope:true,temporal:true},availability_requirements:{source_domain,accepted_data_statuses,required_coverage:'FULL',minimum_coverage_ratio:1,through_period_end:true,limited_coverage_permitted:false},coverage_requirements:{full_closed_period_required:period_statuses.includes('CLOSED')},comparability_requirements:{required:comparability_required,supported_modes:comparisons},constraint_policy:{mode:'PRESERVE',supported_axes:[]},semantic_requirements:{minimum_periods,...(exact_periods?{exact_periods}:{}),reconciliation_required:false,...(required_market_universe?{required_market_universe}:{}),...(required_geography?{required_geography}:{})},physical:{executor_ref:'motor_registry.getMotor',motor_ref,input_contract_ref},evidence:{authorized_claim_types:[claim_type],evidence_projector_ref},selection_metadata:{specialization,cost_class:'LOW',latency_class:'MEDIUM',semantic_transformation_distance:0}});
}
export const MARKET_SHARE_POSITION_NATIVE_CAPABILITY=sourceCapability({capability_id:'MARKET/SHARE_POSITION',capability_version:'0.2',goal_type:'MARKET_POSITION',claim_type:'MARKET_POSITION_VALUE',source_domain:'RVM',accepted_data_statuses:['CONSOLIDATED'],entity_types:['BRAND'],measures:['MARKET_SHARE'],commercial_universes:['RVM_MARKET'],organization_scopes:['CIDEF'],grains:['BRAND'],comparisons:['MARKET'],motor_ref:'competitive_share_trajectory_v01',input_contract_ref:'parseRvmBrandShareTrajectoryInput.v0.1',evidence_projector_ref:'protocol.evidence.rvm_market_position.v1',minimum_periods:1,exact_periods:1,required_market_universe:'TOTAL_RVM_MARKET',required_geography:'CHILE',specialization:100});
export const MARKET_SHARE_TRAJECTORY_NATIVE_CAPABILITY=sourceCapability({capability_id:'MARKET/SHARE_TRAJECTORY',capability_version:'0.2',goal_type:'TEMPORAL_TRAJECTORY',claim_type:'TRAJECTORY_SERIES',source_domain:'RVM',accepted_data_statuses:['CONSOLIDATED'],entity_types:['BRAND'],measures:['MARKET_SHARE'],commercial_universes:['RVM_MARKET'],organization_scopes:['CIDEF'],grains:['BRAND'],comparisons:['NONE'],motor_ref:'competitive_share_trajectory_v01',input_contract_ref:'parseRvmBrandShareTrajectoryInput.v0.1',evidence_projector_ref:'protocol.evidence.rvm_share_trajectory.v1',minimum_periods:2,required_market_universe:'TOTAL_RVM_MARKET',required_geography:'CHILE',comparability_required:true,specialization:99});
export const PRICING_HISTORY_OBSERVED_NATIVE_CAPABILITY=sourceCapability({capability_id:'PRICING/HISTORY_OBSERVED',capability_version:'0.1',goal_type:'OBSERVED_RESULT',claim_type:'OBSERVED_COMMERCIAL_CONDITION',source_domain:'PRICING',accepted_data_statuses:['AVAILABLE'],entity_types:['VERSION'],measures:['PUBLISHED_COMMERCIAL_CONDITION'],commercial_universes:['PUBLISHED_CONDITIONS'],organization_scopes:['CIDEF'],period_units:['DAY','MONTH'],period_statuses:['CLOSED','OPEN','PARTIAL'],grains:['VERSION'],comparisons:['NONE'],motor_ref:'pricing_history_v01',input_contract_ref:'parsePricingHistoryInput.v0.1',evidence_projector_ref:'protocol.evidence.pricing_observed_condition.v1',minimum_periods:1,required_geography:'CHILE',specialization:100});

const CATALOG=Object.freeze([LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,LONGITUDINAL_VENTAS_TRAJECTORY_NATIVE_CAPABILITY,LONGITUDINAL_VENTAS_CHANGE_NATIVE_CAPABILITY,SALES_PRODUCT_CHANGE_CONTRIBUTION_NATIVE_CAPABILITY,SALES_STORE_CHANGE_CONTRIBUTION_NATIVE_CAPABILITY,SALES_SELLER_CHANGE_CONTRIBUTION_NATIVE_CAPABILITY,SALES_ORGANIZATIONAL_RELATIVE_PERFORMANCE_NATIVE_CAPABILITY,SALES_DETERIORATION_STATUS_NATIVE_CAPABILITY,SALES_CURRENT_MONTH_CLOSE_FORECAST_NATIVE_CAPABILITY,MARKET_SHARE_POSITION_NATIVE_CAPABILITY,MARKET_SHARE_TRAJECTORY_NATIVE_CAPABILITY,PRICING_HISTORY_OBSERVED_NATIVE_CAPABILITY]);
export function listCapabilityContracts(){return CATALOG;}
export function getCapabilityContract(capabilityId){const value=CATALOG.find(item=>item.capability_id===capabilityId);invariant(value,'UNKNOWN_TARGET_CAPABILITY','$.capability_id');validateNativeCapabilityContract(value);return value;}
