import { createGoalInstance, validateAuthorityRef } from '../contracts.js';
import { ApplicabilityPredicate, ApplicabilityReason, ApplicabilityStatus, ClaimType, GoalType } from '../enums.js';
import { clone, finalizeWithHash, fingerprint, invariant, rejectUnknown, requireArray, requireEnum, requireObject, requireString, verifyHash } from '../primitives.js';

const TIMESTAMP=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
function integer(value,path,{minimum=0}={}){invariant(Number.isInteger(value)&&value>=minimum,'INVALID_INTEGER',path);}
function strings(value,path,{nonEmpty=false,allowed=null}={}){requireArray(value,path);invariant(!nonEmpty||value.length>0,'EMPTY_ARRAY',path);value.forEach((item,index)=>{requireString(item,`${path}[${index}]`);if(allowed)requireEnum(item,allowed,`${path}[${index}]`);});invariant(new Set(value).size===value.length,'DUPLICATE_VALUE',path);}
function bool(value,path){invariant(typeof value==='boolean','INVALID_BOOLEAN',path);}
function semanticBinding(value,path){const direct=clone(value);const comparison=value.comparison;const constraints=value.explicit_constraints;delete direct.comparison;delete direct.explicit_constraints;createGoalInstance({contract_version:'goal_instance.v1',goal_id:'validate',question_contract_ref:'validate',universe_resolution_ref:'validate',goal_type:'OBSERVED_RESULT',evidence_class:'REQUIRED',origin:'USER_EXPRESSED',status:'PENDING',bindings:clone(value.bindings??direct),...(comparison?{comparison}:{}),...(constraints?{explicit_constraints:clone(constraints)}:{})});}

export function validateNativeCapabilityContract(value){
  rejectUnknown(value,['contract_version','capability_id','capability_version','satisfies','supported_bindings','authority_requirements','availability_requirements','coverage_requirements','comparability_requirements','constraint_policy','semantic_requirements','physical','evidence','selection_metadata','contract_fingerprint'],'$');requireEnum(value.contract_version,['capability_contract.v2'],'$.contract_version');requireString(value.capability_id,'$.capability_id');requireString(value.capability_version,'$.capability_version');
  rejectUnknown(value.satisfies,['goal_types','claim_types'],'$.satisfies');strings(value.satisfies.goal_types,'$.satisfies.goal_types',{nonEmpty:true,allowed:Object.values(GoalType)});strings(value.satisfies.claim_types,'$.satisfies.claim_types',{nonEmpty:true,allowed:Object.values(ClaimType)});
  const bindingKeys=['entity_types','measures','commercial_universes','organization_scopes','period_units','period_statuses','period_alignments','grains','comparisons'];rejectUnknown(value.supported_bindings,bindingKeys,'$.supported_bindings');for(const key of bindingKeys)strings(value.supported_bindings[key],`$.supported_bindings.${key}`,{nonEmpty:true});
  const authorityKeys=['identity','membership','organization_scope','temporal'];rejectUnknown(value.authority_requirements,authorityKeys,'$.authority_requirements');for(const key of authorityKeys)bool(value.authority_requirements[key],`$.authority_requirements.${key}`);
  rejectUnknown(value.availability_requirements,['source_domain','accepted_data_statuses','required_coverage','minimum_coverage_ratio','through_period_end','limited_coverage_permitted'],'$.availability_requirements');requireEnum(value.availability_requirements.source_domain,['SALES','RVM','CRM','PRICING'],'$.availability_requirements.source_domain');strings(value.availability_requirements.accepted_data_statuses,'$.availability_requirements.accepted_data_statuses',{nonEmpty:true});requireEnum(value.availability_requirements.required_coverage,['FULL','PARTIAL','ANY'],'$.availability_requirements.required_coverage');invariant(typeof value.availability_requirements.minimum_coverage_ratio==='number'&&value.availability_requirements.minimum_coverage_ratio>=0&&value.availability_requirements.minimum_coverage_ratio<=1,'INVALID_COVERAGE','$.availability_requirements.minimum_coverage_ratio');bool(value.availability_requirements.through_period_end,'$.availability_requirements.through_period_end');bool(value.availability_requirements.limited_coverage_permitted,'$.availability_requirements.limited_coverage_permitted');
  rejectUnknown(value.coverage_requirements,['full_closed_period_required'],'$.coverage_requirements');bool(value.coverage_requirements.full_closed_period_required,'$.coverage_requirements.full_closed_period_required');rejectUnknown(value.comparability_requirements,['required','supported_modes'],'$.comparability_requirements');bool(value.comparability_requirements.required,'$.comparability_requirements.required');strings(value.comparability_requirements.supported_modes,'$.comparability_requirements.supported_modes',{nonEmpty:true});rejectUnknown(value.constraint_policy,['mode','supported_axes'],'$.constraint_policy');requireEnum(value.constraint_policy.mode,['PRESERVE'],'$.constraint_policy.mode');strings(value.constraint_policy.supported_axes,'$.constraint_policy.supported_axes');
  if(value.semantic_requirements){rejectUnknown(value.semantic_requirements,['minimum_periods','exact_periods','reconciliation_required','required_market_universe','required_geography'],'$.semantic_requirements');integer(value.semantic_requirements.minimum_periods,'$.semantic_requirements.minimum_periods',{minimum:1});if(Object.hasOwn(value.semantic_requirements,'exact_periods'))integer(value.semantic_requirements.exact_periods,'$.semantic_requirements.exact_periods',{minimum:1});bool(value.semantic_requirements.reconciliation_required,'$.semantic_requirements.reconciliation_required');if(Object.hasOwn(value.semantic_requirements,'required_market_universe'))requireString(value.semantic_requirements.required_market_universe,'$.semantic_requirements.required_market_universe');if(Object.hasOwn(value.semantic_requirements,'required_geography'))requireString(value.semantic_requirements.required_geography,'$.semantic_requirements.required_geography');}
  const physicalKeys=['executor_ref','motor_ref','input_contract_ref'];rejectUnknown(value.physical,physicalKeys,'$.physical');for(const key of physicalKeys)requireString(value.physical[key],`$.physical.${key}`);rejectUnknown(value.evidence,['authorized_claim_types','evidence_projector_ref'],'$.evidence');strings(value.evidence.authorized_claim_types,'$.evidence.authorized_claim_types',{nonEmpty:true,allowed:Object.values(ClaimType)});requireString(value.evidence.evidence_projector_ref,'$.evidence.evidence_projector_ref');
  rejectUnknown(value.selection_metadata,['specialization','cost_class','latency_class','semantic_transformation_distance'],'$.selection_metadata');integer(value.selection_metadata.specialization,'$.selection_metadata.specialization');requireEnum(value.selection_metadata.cost_class,['LOW','MEDIUM','HIGH'],'$.selection_metadata.cost_class');requireEnum(value.selection_metadata.latency_class,['LOW','MEDIUM','HIGH'],'$.selection_metadata.latency_class');integer(value.selection_metadata.semantic_transformation_distance,'$.selection_metadata.semantic_transformation_distance');verifyHash(value,'contract_fingerprint');return true;
}
export function createNativeCapabilityContract(draft){const value=finalizeWithHash(draft,'contract_fingerprint');validateNativeCapabilityContract(value);return value;}

function validatePredicateResult(value,path){rejectUnknown(value,['predicate','passed','reason_code'],path);requireEnum(value.predicate,ApplicabilityPredicate,`${path}.predicate`);bool(value.passed,`${path}.passed`);if(Object.hasOwn(value,'reason_code'))requireEnum(value.reason_code,ApplicabilityReason,`${path}.reason_code`);invariant(value.passed!==Object.hasOwn(value,'reason_code'),'INVALID_PREDICATE_REASON',path);}
export function validateApplicabilityDecisionV2(value){rejectUnknown(value,['contract_version','decision_id','goal_ref','capability_contract_ref','universe_resolution_ref','availability_snapshot_ref','status','predicate_results','reason_codes','authorized_claim_types','ranking','decision_fingerprint'],'$');requireEnum(value.contract_version,['applicability_decision.v2'],'$.contract_version');for(const key of ['decision_id','goal_ref','capability_contract_ref','universe_resolution_ref','availability_snapshot_ref'])requireString(value[key],`$.${key}`);requireEnum(value.status,Object.values(ApplicabilityStatus),'$.status');requireArray(value.predicate_results,'$.predicate_results');value.predicate_results.forEach((item,index)=>validatePredicateResult(item,`$.predicate_results[${index}]`));invariant(value.predicate_results.length===ApplicabilityPredicate.length&&new Set(value.predicate_results.map(item=>item.predicate)).size===ApplicabilityPredicate.length,'INCOMPLETE_APPLICABILITY_PREDICATES','$.predicate_results');strings(value.reason_codes,'$.reason_codes',{allowed:ApplicabilityReason});strings(value.authorized_claim_types,'$.authorized_claim_types',{allowed:Object.values(ClaimType)});invariant(value.status==='NOT_APPLICABLE'?value.reason_codes.length>0&&value.authorized_claim_types.length===0:value.reason_codes.length===0&&value.authorized_claim_types.length>0,'INVALID_APPLICABILITY_OUTCOME','$');rejectUnknown(value.ranking,['claim_coverage','exact_binding','authority','comparability','coverage','data_status','transformation_distance','specialization','cost_rank','latency_rank'],'$.ranking');for(const [key,score] of Object.entries(value.ranking))integer(score,`$.ranking.${key}`);verifyHash(value,'decision_fingerprint',['decision_id']);return true;}
export function createApplicabilityDecisionV2(draft){const value=finalizeWithHash(draft,'decision_fingerprint',['decision_id']);validateApplicabilityDecisionV2(value);return value;}

export function validateAuthorizeExecutionCommand(value){rejectUnknown(value,['contract_version','command_id','protocol_id','expected_state_version','selected_action_ref','pending_objective_fingerprint','command_fingerprint'],'$');requireEnum(value.contract_version,['authorize_execution_command.v1'],'$.contract_version');for(const key of ['command_id','protocol_id','pending_objective_fingerprint'])requireString(value[key],`$.${key}`);integer(value.expected_state_version,'$.expected_state_version',{minimum:1});rejectUnknown(value.selected_action_ref,['action_id','action_fingerprint'],'$.selected_action_ref');requireString(value.selected_action_ref.action_id,'$.selected_action_ref.action_id');requireString(value.selected_action_ref.action_fingerprint,'$.selected_action_ref.action_fingerprint');verifyHash(value,'command_fingerprint',['command_id']);return true;}
export function createAuthorizeExecutionCommand(draft){const value=finalizeWithHash(draft,'command_fingerprint',['command_id']);validateAuthorizeExecutionCommand(value);return value;}

export function validatePhysicalExecutionAuthorization(value){rejectUnknown(value,['contract_version','authorization_id','protocol_id','state_version','selected_action_ref','goal_ref','capability','applicability','semantic_binding','authority_refs','availability_snapshot_ref','physical_request','authorized_claim_types','execution_fingerprint','issued_at','status','authorization_fingerprint'],'$');requireEnum(value.contract_version,['execution_authorization.v2'],'$.contract_version');for(const key of ['authorization_id','protocol_id','goal_ref','availability_snapshot_ref','execution_fingerprint'])requireString(value[key],`$.${key}`);integer(value.state_version,'$.state_version',{minimum:1});rejectUnknown(value.selected_action_ref,['action_id','action_fingerprint'],'$.selected_action_ref');for(const key of Object.keys(value.selected_action_ref))requireString(value.selected_action_ref[key],`$.selected_action_ref.${key}`);rejectUnknown(value.capability,['capability_id','capability_version','capability_contract_fingerprint'],'$.capability');for(const key of Object.keys(value.capability))requireString(value.capability[key],`$.capability.${key}`);rejectUnknown(value.applicability,['decision_id','status','decision_fingerprint'],'$.applicability');requireString(value.applicability.decision_id,'$.applicability.decision_id');requireEnum(value.applicability.status,['APPLICABLE','APPLICABLE_WITH_LIMITED_COVERAGE'],'$.applicability.status');requireString(value.applicability.decision_fingerprint,'$.applicability.decision_fingerprint');semanticBinding(value.semantic_binding);rejectUnknown(value.authority_refs,['identity_ref','membership_refs','temporal_ref'],'$.authority_refs');validateAuthorityRef(value.authority_refs.identity_ref,'$.authority_refs.identity_ref');requireArray(value.authority_refs.membership_refs,'$.authority_refs.membership_refs');value.authority_refs.membership_refs.forEach((item,index)=>validateAuthorityRef(item,`$.authority_refs.membership_refs[${index}]`));validateAuthorityRef(value.authority_refs.temporal_ref,'$.authority_refs.temporal_ref');rejectUnknown(value.physical_request,['executor_ref','motor_ref','input_contract_ref','evidence_projector_ref','validated_input'],'$.physical_request');for(const key of ['executor_ref','motor_ref','input_contract_ref','evidence_projector_ref'])requireString(value.physical_request[key],`$.physical_request.${key}`);requireObject(value.physical_request.validated_input,'$.physical_request.validated_input');strings(value.authorized_claim_types,'$.authorized_claim_types',{nonEmpty:true,allowed:Object.values(ClaimType)});invariant(TIMESTAMP.test(value.issued_at||''),'INVALID_TIMESTAMP','$.issued_at');requireEnum(value.status,['AUTHORIZED_READY'],'$.status');verifyHash(value,'authorization_fingerprint',['authorization_id']);return true;}
export function createPhysicalExecutionAuthorization(draft){const value=finalizeWithHash(draft,'authorization_fingerprint',['authorization_id']);validatePhysicalExecutionAuthorization(value);return value;}

export function executionFingerprint(value){return fingerprint(value);}
