import { ApplicabilityStatus } from '../enums.js';
import { deepFreeze, invariant } from '../primitives.js';
import { evaluateCapabilityCatalog } from './applicability.js';

const STATUS={APPLICABLE:2,APPLICABLE_WITH_LIMITED_COVERAGE:1};
function tuple(decision,capability){const r=decision.ranking;return [STATUS[decision.status]??0,r.claim_coverage,r.exact_binding,r.authority,r.comparability,r.coverage,r.data_status,-r.transformation_distance,r.specialization,r.cost_rank,r.latency_rank];}
function compare(left,right){for(let i=0;i<left.tuple.length;i++)if(left.tuple[i]!==right.tuple[i])return right.tuple[i]-left.tuple[i];return left.capability.capability_id.localeCompare(right.capability.capability_id);}
export function rankApplicabilityDecisions(decisions,capabilityContracts){const byFingerprint=new Map(capabilityContracts.map(item=>[item.contract_fingerprint,item]));return deepFreeze(decisions.filter(item=>item.status!==ApplicabilityStatus.NOT_APPLICABLE).map(decision=>{const capability=byFingerprint.get(decision.capability_contract_ref);invariant(capability,'CAPABILITY_CONTRACT_NOT_FOUND','$.capability_contract_ref');return {decision,capability,tuple:tuple(decision,capability)};}).sort(compare));}
export function selectPhysicalCapability({pendingExecutionObjective,goal,capabilityContracts,universeResolution,availabilitySnapshot}){invariant(pendingExecutionObjective?.status==='PENDING','PENDING_EXECUTION_OBJECTIVE_REQUIRED','$.pendingExecutionObjective');invariant(goal.goal_id===pendingExecutionObjective.goal_id&&goal.goal_fingerprint===pendingExecutionObjective.goal_fingerprint,'PENDING_OBJECTIVE_GOAL_MISMATCH','$.goal');const decisions=evaluateCapabilityCatalog({goal,capabilityContracts,universeResolution,availabilitySnapshot});const ranked=rankApplicabilityDecisions(decisions,capabilityContracts);return deepFreeze({decisions,selected:ranked.length?{capability:ranked[0].capability,decision:ranked[0].decision}:null});}
