import test from 'node:test';
import assert from 'node:assert/strict';
import { createTypedClaim } from '../../lib/protocol/execution/contracts.js';
import { evaluateNativeApplicability } from '../../lib/protocol/planning/applicability.js';
import { getCapabilityContract } from '../../lib/protocol/planning/capabilityCatalog.js';
import { createGoalInstance } from '../../lib/protocol/contracts.js';
import { buildGoalEvidenceObligation, claimMateriallySatisfiesGoal } from '../../lib/protocol/sufficiency/evaluator.js';
import { buildFocusedRuntimeFixture } from '../../lib/protocol/runtime/fixtures.js';
import { clone } from '../../lib/protocol/primitives.js';
import { TARGET_CAPABILITY_COVERAGE, TARGET_GOAL_COVERAGE } from '../../lib/protocol/certification/coverage.js';

function claim(type,value){return createTypedClaim({contract_version:'typed_claim.v1',claim_type:type,subject:{canonical_id:'subject',entity_type:'BRAND'},measure:'VIN_SALES',value,period:{date_from:'2026-07-01',date_to:'2026-08-31',period_status:'CLOSED',alignment:'CALENDAR'},commercial_universe:'COMPANY',organization_scope:'CIDEF',grain:'BRAND',comparison:'NONE',authority_refs:['sha256:authority'],source_execution_ref:{execution_fingerprint:'sha256:execution',execution_attempt_fingerprint:'sha256:attempt'}});}
function reGoal(goal,goal_type){const draft=clone(goal);delete draft.goal_fingerprint;draft.goal_id=`goal_${goal_type}`;draft.goal_type=goal_type;return createGoalInstance(draft);}

test('N01/N02 OWN_STORES or DEALERS paths cannot satisfy COMPANY by fallback',async()=>{const f=await buildFocusedRuntimeFixture(),decision=evaluateNativeApplicability({goal:f.state.goals[0],capabilityContract:getCapabilityContract('SALES/CURRENT_MONTH_CLOSE_FORECAST'),universeResolution:f.resolution,availabilitySnapshot:f.availability});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(decision.reason_codes.includes('UNIVERSE_UNSUPPORTED'));assert.equal(getCapabilityContract('LONGITUDINAL/VENTAS').supported_bindings.commercial_universes.includes('DEALERS'),false);});
test('N03/N04 preliminary RVM and current CRM remain unavailable for consolidated or historical proof',()=>{assert.equal(TARGET_CAPABILITY_COVERAGE.find(row=>row.capability_id==='LONGITUDINAL/RVM').classification,'UNSUPPORTED_AUTHORITY');assert.equal(TARGET_CAPABILITY_COVERAGE.find(row=>row.capability_id==='LONGITUDINAL/CRM').classification,'UNSUPPORTED_COVERAGE');});
test('N05 published pricing cannot satisfy realized-price proposition',()=>{const pricing=TARGET_CAPABILITY_COVERAGE.find(row=>row.capability_id==='PRICING/HISTORY');assert.equal(pricing.target_goal_types.length,0);assert.match(pricing.blocker,/published is not realized/);});
test('N06 association and N07 attribution cannot be promoted to causal claims',()=>{assert.throws(()=>claim('ASSOCIATION_RESULT',{coefficient:.4,method:'PEARSON',observations:12,causal:true}),/CAUSAL_PROMOTION_FORBIDDEN/);assert.throws(()=>claim('CHANGE_CONTRIBUTION_SET',{total_change:3,unit:'VIN',components:[],residual:3,reconciled:true,causal:true}),/UNKNOWN_FIELD/);});
test('N08 trajectory cannot satisfy risk without the registered risk claim',async()=>{const f=await buildFocusedRuntimeFixture(),goal=reGoal(f.state.goals[0],'RISK_STATUS'),obligation=buildGoalEvidenceObligation({goal,universeResolution:f.resolution,availabilitySnapshot:f.availability});assert.equal(obligation.required_claim_type,'RISK_RULE_RESULT');assert.notEqual(obligation.required_claim_type,'TRAJECTORY_SERIES');});
test('N09/N10 market position requires denominator and relative performance requires comparator',()=>{assert.throws(()=>claim('MARKET_POSITION_VALUE',{entity_value:10,share:.1,rank:2,unit:'VIN',denominator_ref:'rvm'}),/UNKNOWN_FIELD|INVALID_CLAIM_VALUE/);assert.throws(()=>claim('RELATIVE_PERFORMANCE_VALUE',{actual_value:.4,difference:.1,unit:'PP',comparator_ref:'median_3',common_basis:'CERTIFIED_SHARE_BASIS'}),/INVALID_CLAIM_VALUE/);});
test('N11 non-comparable change and N12/N13 unreconciled decompositions cannot prove goals',()=>{assert.throws(()=>claim('CHANGE_VALUE',{from_amount:1,to_amount:2,absolute_change:1,pct_change:1,unit:'VIN',comparable_basis:'UNVERIFIED'}),/INVALID_ENUM/);assert.equal(claimMateriallySatisfiesGoal('CONCENTRATION_STATUS',{denominator:10,distribution:[],reconciled:false}),false);assert.equal(claimMateriallySatisfiesGoal('CHANGE_ATTRIBUTION',{components:[{component_id:'x'}],reconciled:false}),false);});
test('N14 flow evidence cannot satisfy leakage and N15 unsupported capabilities are not fallback-routed',async()=>{const f=await buildFocusedRuntimeFixture(),goal=reGoal(f.state.goals[0],'OPERATIONAL_LEAKAGE'),obligation=buildGoalEvidenceObligation({goal,universeResolution:f.resolution,availabilitySnapshot:f.availability});assert.equal(obligation.required_claim_type,'LEAKAGE_RESULT');assert.equal(TARGET_GOAL_COVERAGE.FLOW_STATUS.status,'NOT_EXECUTABLE');assert.throws(()=>getCapabilityContract('LONGITUDINAL/RVM'),/UNKNOWN_TARGET_CAPABILITY/);});
test('each non-observed Goal has one semantic exact-claim obligation and no physical identity',async()=>{const f=await buildFocusedRuntimeFixture(),mapping={PROJECTED_RESULT:'PROJECTED_VALUE',EXPECTATION_GAP:'GAP_VALUE',TEMPORAL_CHANGE:'CHANGE_VALUE',TEMPORAL_TRAJECTORY:'TRAJECTORY_SERIES',RELATIVE_PERFORMANCE:'RELATIVE_PERFORMANCE_VALUE',MARKET_POSITION:'MARKET_POSITION_VALUE',RISK_STATUS:'RISK_RULE_RESULT',CHANGE_ATTRIBUTION:'CHANGE_CONTRIBUTION_SET',CONCENTRATION_STATUS:'CONCENTRATION_RESULT',SIGNAL_STATUS:'SIGNAL_RULE_RESULT',ASSOCIATED_MOVEMENT:'ASSOCIATION_RESULT',FLOW_STATUS:'FLOW_RESULT',OPERATIONAL_LEAKAGE:'LEAKAGE_RESULT'};for(const [goalType,claimType] of Object.entries(mapping)){const obligation=buildGoalEvidenceObligation({goal:reGoal(f.state.goals[0],goalType),universeResolution:f.resolution,availabilitySnapshot:f.availability});assert.equal(obligation.required_claim_type,claimType);for(const forbidden of ['capability_id','motor_id','physical_request','question_family'])assert.equal(JSON.stringify(obligation).includes(forbidden),false);}});
