import test from 'node:test';
import assert from 'node:assert/strict';
import { ClaimType, GoalType } from '../../lib/protocol/enums.js';
import { listCapabilityContracts } from '../../lib/protocol/planning/capabilityCatalog.js';
import { validateNativeCapabilityContract } from '../../lib/protocol/planning/contracts.js';
import { TARGET_EVIDENCE_PROJECTORS, projectVentasTrajectory, projectVentasChange, projectChangeContribution, projectRelativePerformance, projectDeteriorationStatus, projectCurrentMonthForecast } from '../../lib/protocol/execution/projector.js';
import { validateEvidenceRecordV2 } from '../../lib/protocol/execution/contracts.js';
import { getTargetCertificationCoverage, TARGET_CAPABILITY_COVERAGE, TARGET_GOAL_COVERAGE } from '../../lib/protocol/certification/coverage.js';

const period={date_from:'2026-06-01',date_to:'2026-08-31',period_status:'CLOSED',alignment:'CALENDAR',timezone:'America/Santiago',anchor_timestamp:'2026-09-01T00:00:00.000Z',temporal_policy_ref:'closed.v1',quantity:3,unit:'MONTH'};
function authorization(capability_id,projector,claim_type,{subject={canonical_id:'brand_foton',entity_type:'BRAND'},grain='BRAND',comparison='NONE',commercial_universe='COMPANY',periodOverride=period}={}){return {authorization_id:'authorization_fixture',authorization_fingerprint:'sha256:authorization',protocol_id:'protocol_fixture',goal_ref:'sha256:goal',selected_action_ref:{action_id:'action',action_fingerprint:'sha256:action'},capability:{capability_id,capability_version:'1.0',capability_contract_fingerprint:'sha256:capability'},semantic_binding:{subject:{...subject,canonical_label:'Fixture',resolution_status:'RESOLVED',authority_ref:'sha256:identity'},measure:'VIN_SALES',commercial_universe,organization_scope:'CIDEF',period:periodOverride,grain,comparison,explicit_constraints:[]},authority_refs:{identity_ref:{authority_fingerprint:'sha256:identity'},membership_refs:[{authority_fingerprint:'sha256:membership'}],temporal_ref:{authority_fingerprint:'sha256:temporal'}},availability_snapshot_ref:'sha256:snapshot',physical_request:{motor_ref:capability_id.startsWith('LONGITUDINAL')?'ventas_longitudinal_context_v01':capability_id==='SALES/PRODUCT_CHANGE_CONTRIBUTION'?'ventas_product_change_contribution_v01':capability_id==='SALES/ORGANIZATIONAL_RELATIVE_PERFORMANCE'?'organizational_relative_performance_v01':capability_id==='SALES/DETERIORATION_STATUS'?'org_sales_deterioration_status_v01':'current_month_close_forecast_v01',evidence_projector_ref:projector},authorized_claim_types:[claim_type],execution_fingerprint:'sha256:execution'};}
const executionAttempt={attempt_fingerprint:'sha256:attempt'};
const timing={executionAttempt,observed_at:'2026-09-01T00:00:00.000Z',admitted_at:'2026-09-01T00:00:01.000Z',question_contract_ref:'sha256:question'};
function ventasRaw(series){return {motor:'ventas_longitudinal_context_v01',metric:'VIN_SALES',grain:'BRAND',dateFrom:'2026-06-01',dateTo:'2026-08-31',commercial_scope:{universe:'COMPANY'},commercial_validation:{valid:true},filters:{brand_id:['brand_foton']},series};}

test('closed goal and claim vocabularies contain the fourteen migration targets only',()=>{assert.equal(Object.keys(GoalType).length,14);assert.deepEqual(new Set(Object.values(ClaimType)),new Set(['OBSERVED_VALUE','PROJECTED_VALUE','GAP_VALUE','CHANGE_VALUE','TRAJECTORY_SERIES','RELATIVE_PERFORMANCE_VALUE','MARKET_POSITION_VALUE','RISK_RULE_RESULT','CHANGE_CONTRIBUTION_SET','CONCENTRATION_RESULT','SIGNAL_RULE_RESULT','ASSOCIATION_RESULT','FLOW_RESULT','LEAKAGE_RESULT']));});
test('nine production contracts are native and claim-bounded',()=>{const contracts=listCapabilityContracts();assert.equal(contracts.length,9);for(const contract of contracts){assert.equal(validateNativeCapabilityContract(contract),true);assert.deepEqual(contract.satisfies.claim_types,contract.evidence.authorized_claim_types);assert.equal(Object.hasOwn(contract,'question_family'),false);}assert.equal(new Set(contracts.map(item=>item.capability_id)).size,9);});
test('trajectory projector preserves ordered certified values without calculating change',()=>{const auth=authorization('LONGITUDINAL/VENTAS_TRAJECTORY','protocol.evidence.ventas_trajectory.v1','TRAJECTORY_SERIES');const record=projectVentasTrajectory({authorization:auth,rawResult:ventasRaw([{period:'2026-06',value:5},{period:'2026-07',value:7},{period:'2026-08',value:6}]),...timing});assert.equal(validateEvidenceRecordV2(record),true);assert.deepEqual(record.claims[0].value.observations.map(x=>x.amount),[5,7,6]);assert.equal(record.claims[0].claim_type,'TRAJECTORY_SERIES');});
test('change projector copies motor-certified arithmetic and exact comparison',()=>{const auth=authorization('LONGITUDINAL/VENTAS_CHANGE','protocol.evidence.ventas_change.v1','CHANGE_VALUE',{comparison:'PREVIOUS_PERIOD'});const raw=ventasRaw([{period:'2026-06',value:5,absoluteChange:null,pctChange:null},{period:'2026-08',value:8,absoluteChange:3,pctChange:.6}]);const record=projectVentasChange({authorization:auth,rawResult:raw,...timing});assert.equal(record.claims[0].value.absolute_change,3);assert.equal(record.claims[0].comparison,'PREVIOUS_PERIOD');});
test('contribution adapter exposes components plus residual and requires reconciliation',()=>{const raw={engine:'ventas_product_change_contribution_v01',inputs:{period_a:'2026-06',period_b:'2026-08'},cidef:{delta_sales:3},models:[{modelo_id:1,delta_sales:4,contribution_pct_of_cidef_delta:133.33}],identity_residual:{total:{delta_sales:-1}},validation:{cidef_delta_reconciles:true}};const auth=authorization('SALES/PRODUCT_CHANGE_CONTRIBUTION','protocol.evidence.product_change_contribution.v1','CHANGE_CONTRIBUTION_SET',{subject:{canonical_id:'cidef',entity_type:'COMPANY'},grain:'MODEL',comparison:'PREVIOUS_PERIOD'});const record=projectChangeContribution({authorization:auth,rawResult:raw,...timing});assert.deepEqual(record.claims[0].value,{total_change:3,unit:'VIN',components:[{component_id:'1',change:4,contribution_pct:133.33}],residual:-1,reconciled:true});assert.equal(validateEvidenceRecordV2(record),true);});
test('relative performance, deterioration and forecast project only exact authorized propositions',()=>{const relativeAuth=authorization('SALES/ORGANIZATIONAL_RELATIVE_PERFORMANCE','protocol.evidence.organizational_relative_performance.v1','RELATIVE_PERFORMANCE_VALUE',{subject:{canonical_id:'10',entity_type:'STORE'},grain:'STORE',comparison:'EXPECTED',commercial_universe:'OWN_STORES'});const relative=projectRelativePerformance({authorization:relativeAuth,rawResult:{engine:'organizational_relative_performance_v01',certified_rule:{baseline:'median_3'},rows:[{sucursal_id:'10',evaluable:true,actual_share:.4,expected_share:.3,relative_gap_pp:10}],validation:{ok:true}},...timing});assert.equal(relative.claims[0].value.difference,10);const riskPeriod={...period,date_from:'2026-08-01',quantity:1};const riskAuth=authorization('SALES/DETERIORATION_STATUS','protocol.evidence.deterioration_status.v1','RISK_RULE_RESULT',{subject:{canonical_id:'10',entity_type:'STORE'},grain:'STORE',comparison:'EXPECTED',commercial_universe:'OWN_STORES',periodOverride:riskPeriod});const risk=projectDeteriorationStatus({authorization:riskAuth,rawResult:{engine:'org_sales_deterioration_status_v01',inputs:{cutoff_month:'2026-08'},units:[{unit_id:'10',status:'DETERIORATING',observation_state:'OBSERVED_POSITIVE',status_reason:'ACTIVE_EPISODE',current:{month:'2026-08'},persistence_rows:[{month:'2026-07'},{month:'2026-08'}]}],validation:{fixed_rule:true}},...timing});assert.equal(risk.claims[0].value.status,'DETERIORATING');const forecastPeriod={...period,date_from:'2026-09-01',date_to:'2026-09-15',period_status:'PARTIAL',quantity:1};const forecastAuth=authorization('SALES/CURRENT_MONTH_CLOSE_FORECAST','protocol.evidence.current_month_forecast.v1','PROJECTED_VALUE',{subject:{canonical_id:'cidef',entity_type:'COMPANY'},grain:'TOTAL',commercial_universe:'OWN_STORES',periodOverride:forecastPeriod});const forecast=projectCurrentMonthForecast({authorization:forecastAuth,rawResult:{engine:'current_month_close_forecast_v01',as_of:{cutoff_date:'2026-09-15'},historical:{backtest_start_month:'2025-01',backtest_end_month:'2026-08'},cidef_propio:{forecast_status:'EVALUABLE',forecast_close:42,historical_observations:12},validation:{ok:true}},...timing});assert.equal(forecast.claims[0].value.amount,42);for(const record of [relative,risk,forecast])assert.equal(validateEvidenceRecordV2(record),true);});
test('all native evidence projectors are registered and records expose no raw payload',()=>{for(const contract of listCapabilityContracts())assert.equal(typeof TARGET_EVIDENCE_PROJECTORS[contract.evidence.evidence_projector_ref],'function');});
test('machine-readable matrix covers all 14 goals and all 34 public capabilities',()=>{const matrix=getTargetCertificationCoverage();assert.equal(Object.keys(matrix.goals).length,14);assert.equal(matrix.capabilities.length,34);assert.equal(TARGET_CAPABILITY_COVERAGE.filter(row=>row.target_contract).length,7);assert.equal(TARGET_GOAL_COVERAGE.CONCENTRATION_STATUS.status,'NOT_EXECUTABLE');assert.match(TARGET_GOAL_COVERAGE.CONCENTRATION_STATUS.blockers[0],/distribution/);});
test('business blockers prevent scope, authority and causal widening',()=>{assert.match(TARGET_GOAL_COVERAGE.PROJECTED_RESULT.blockers[0],/OWN_STORES/);assert.equal(TARGET_GOAL_COVERAGE.MARKET_POSITION.status,'NOT_EXECUTABLE');assert.equal(TARGET_GOAL_COVERAGE.FLOW_STATUS.status,'NOT_EXECUTABLE');assert.equal(TARGET_CAPABILITY_COVERAGE.find(row=>row.capability_id==='PRICING/HISTORY').classification,'UNSUPPORTED_AUTHORITY');assert.match(TARGET_CAPABILITY_COVERAGE.find(row=>row.capability_id==='MARKET/INVERSE_SHARE_MOVEMENT').blocker,/noncausal/);});
