import test from 'node:test';
import assert from 'node:assert/strict';
import { createAuthorityRef, createAvailabilitySnapshot, createQuestionContract, createUniverseResolution } from '../../lib/protocol/contracts.js';
import { clone } from '../../lib/protocol/primitives.js';
import { buildWp04Fixture } from '../../lib/protocol/resolution/fixtures.js';
import { initializeProtocol, createSelectActionCommand, selectAction } from '../../lib/protocol/runtime/index.js';
import { assessBroadCandidateViability } from '../../lib/protocol/investigation/runtime.js';
import { authorizeExecution, createAuthorizeExecutionCommand } from '../../lib/protocol/planning/index.js';
import { createExecuteAuthorizationCommand, executeAndAdmitEvidence } from '../../lib/protocol/execution/index.js';
import { evaluateGoalSufficiencyV2, applySufficiencyEvaluation, evaluateProtocolClosure, applyProtocolClosure, buildSynthesisPacketV2 } from '../../lib/protocol/sufficiency/index.js';

function withoutHash(value,key){const draft=clone(value);delete draft[key];return draft;}
async function broadTrajectoryFixture(){
  const base=await buildWp04Fixture();
  const q=withoutHash(base.question,'question_contract_hash');
  q.question_id='question_migration_trajectory';q.original_question='¿Cómo va Foton?';q.period.semantic.quantity=3;q.period.materialized.date_from='2026-06-01';q.semantic_intent={operation:'ASSESS',breadth:'BROAD',expressed_concepts:['SIGNAL'],explicit_conjunction:false,causality:'NOT_REQUESTED'};q.deferred_choice_axes=['EVIDENCE_PROPOSITION'];q.field_provenance={...q.field_provenance,'semantic_intent.operation':'LINGUISTICALLY_INFERRED','semantic_intent.breadth':'LINGUISTICALLY_INFERRED','semantic_intent.expressed_concepts':'LINGUISTICALLY_INFERRED'};
  const question=createQuestionContract(q),r=withoutHash(base.resolution,'resolution_fingerprint');
  r.resolution_id='resolution_migration_trajectory';r.question_contract_ref=question.question_contract_hash;r.temporal.date_from='2026-06-01';r.temporal.effective_from='2026-06-01';
  const extend=value=>{const draft=withoutHash(value,'authority_fingerprint');draft.effective_period={date_from:'2026-06-01',date_to:'2026-08-31'};return createAuthorityRef(draft);};
  r.authority.identity_ref=extend(r.authority.identity_ref);r.authority.membership_refs=r.authority.membership_refs.map(extend);r.authority.temporal_ref=extend(r.authority.temporal_ref);r.subject.authority_ref=r.authority.identity_ref;r.membership.membership_authority_refs=r.authority.membership_refs;
  const resolution=createUniverseResolution(r),a=withoutHash(base.availability,'snapshot_fingerprint');
  a.snapshot_id='availability_migration_trajectory';a.question_contract_ref=question.question_contract_hash;a.requested_period.date_from='2026-06-01';const availability=createAvailabilitySnapshot(a);const state=initializeProtocol({questionContract:question,universeResolution:resolution,availabilitySnapshot:availability,protocol_id:'protocol_migration_trajectory',clock:'2026-09-15T13:00:00.000Z'});return {question,resolution,availability,state};
}
function selectCommand(state){const action=state.actions[0];return createSelectActionCommand({contract_version:'select_action_command.v1',command_id:'select_trajectory',protocol_id:state.protocol_id,expected_state_version:state.state_version,action_id:action.action_id,action_fingerprint:action.action_fingerprint});}
function authorizeCommand(state){return createAuthorizeExecutionCommand({contract_version:'authorize_execution_command.v1',command_id:'authorize_trajectory',protocol_id:state.protocol_id,expected_state_version:state.state_version,selected_action_ref:{action_id:state.selected_action_ref.action_id,action_fingerprint:state.selected_action_ref.action_fingerprint},pending_objective_fingerprint:state.pending_execution_objective.objective_fingerprint});}
function executeCommand(state,authorization){return createExecuteAuthorizationCommand({contract_version:'execute_authorization_command.v1',command_id:'execute_trajectory',protocol_id:state.protocol_id,expected_state_version:state.state_version,authorization_ref:{authorization_id:authorization.authorization_id,authorization_fingerprint:authorization.authorization_fingerprint,execution_fingerprint:authorization.execution_fingerprint}});}

test('real SALES trajectory path completes broad semantic selection through evidence-bounded synthesis',async()=>{const f=await broadTrajectoryFixture();const viable=assessBroadCandidateViability(f.state,{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:'2026-09-15T13:01:00.000Z'});assert.deepEqual(viable.actions.map(action=>action.goal_type),['TEMPORAL_TRAJECTORY']);const selected=selectAction(viable,selectCommand(viable),{clock:'2026-09-15T13:02:00.000Z'});assert.equal(selected.goals.length,1);assert.equal(selected.goals[0].goal_type,'TEMPORAL_TRAJECTORY');const planned=authorizeExecution(selected,authorizeCommand(selected),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:'2026-09-15T13:03:00.000Z'});assert.equal(planned.physical_selection.capability_id,'LONGITUDINAL/VENTAS_TRAJECTORY');const raw={motor:'ventas_longitudinal_context_v01',metric:'VIN_SALES',grain:'BRAND',dateFrom:'2026-06-01',dateTo:'2026-08-31',commercial_scope:{universe:'COMPANY'},commercial_validation:{valid:true},filters:{brand_id:['brand_fixture_foton']},series:[{period:'2026-06',value:20,absoluteChange:null,pctChange:null},{period:'2026-07',value:24,absoluteChange:4,pctChange:.2},{period:'2026-08',value:22,absoluteChange:-2,pctChange:-.083333}]};const executed=await executeAndAdmitEvidence(planned.state,planned.authorization,executeCommand(planned.state,planned.authorization),{applicabilityDecisions:planned.applicability_decisions,availabilitySnapshot:f.availability,motorResolver:async()=>async()=>raw,clock:'2026-09-15T13:04:00.000Z'});assert.equal(executed.admission.status,'ADMITTED');const evaluation=evaluateGoalSufficiencyV2({state:executed.state,goal:executed.state.goals[0],ledger:executed.ledger,questionContract:f.question,universeResolution:f.resolution,availabilitySnapshot:f.availability,evaluated_at:'2026-09-15T13:05:00.000Z'});assert.equal(evaluation.status,'SATISFIED');const assessed=applySufficiencyEvaluation(executed.state,evaluation,{clock:'2026-09-15T13:06:00.000Z'});const closure=evaluateProtocolClosure({state:assessed,sufficiencyEvaluations:[evaluation]});const complete=applyProtocolClosure(assessed,closure,{clock:'2026-09-15T13:07:00.000Z'});const packet=buildSynthesisPacketV2({questionContract:f.question,protocolState:complete,sufficiencyEvaluations:[evaluation],evidenceRecords:executed.ledger.records,universeResolution:f.resolution,availabilitySnapshot:f.availability,created_at:'2026-09-15T13:08:00.000Z'});assert.equal(packet.authorized_claims[0].claim_type,'TRAJECTORY_SERIES');assert.deepEqual(packet.authorized_claims[0].value.observations.map(row=>row.amount),[20,24,22]);assert.equal(JSON.stringify(packet).includes('LONGITUDINAL/VENTAS'),false);});
