import test from 'node:test';import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { createGoalInstance } from '../../lib/protocol/contracts.js';
import { createProtocolState } from '../../lib/protocol/runtime/index.js';
import { applyProtocolClosure, applySufficiencyEvaluation, evaluateObservedResultSufficiencyV2, evaluateProtocolClosure } from '../../lib/protocol/sufficiency/index.js';
import { admittedFocused, CLOSURE_CLOCK, GOAL_CLOCK, SUFFICIENCY_CLOCK } from './sufficiency-helpers.js';

function evaluate(f){return evaluateObservedResultSufficiencyV2({state:f.state,goal:f.goal,ledger:f.ledger,questionContract:f.question,universeResolution:f.resolution,availabilitySnapshot:f.availability,evaluated_at:SUFFICIENCY_CLOCK});}
function extraGoal(f,evidence_class,status='PENDING'){const draft=clone(f.goal);delete draft.goal_fingerprint;draft.goal_id=`goal_${evidence_class.toLowerCase()}`;draft.evidence_class=evidence_class;draft.status=status;return createGoalInstance(draft);}
function withGoal(state,goal){return createProtocolState({...clone(state),goals:[...state.goals,goal],open_obligations:[...state.open_obligations,...(['REQUIRED','CONDITIONAL'].includes(goal.evidence_class)&&goal.status==='PENDING'?[goal.goal_id]:[])],state_hash:undefined});}

test('only SATISFIED backend evaluation transitions Goal and chains immutable state',async()=>{const f=await admittedFocused(),evaluation=evaluate(f),next=applySufficiencyEvaluation(f.state,evaluation,{clock:GOAL_CLOCK});assert.equal(f.state.goals[0].status,'PENDING');assert.equal(next.goals[0].status,'SATISFIED');assert.equal(next.state_version,f.state.state_version+1);assert.equal(next.previous_state_hash,f.state.state_hash);assert.deepEqual(next.sufficiency_evaluation_refs,[evaluation.evaluation_fingerprint]);});
test('N14 pending evaluation cannot mark Goal SATISFIED',async()=>{const f=await admittedFocused(),evaluation=evaluate({...f,ledger:(await import('../../lib/protocol/execution/index.js')).createEvidenceLedger(f.state.protocol_id)});assert.throws(()=>applySufficiencyEvaluation(f.state,evaluation,{clock:GOAL_CLOCK}),/SUFFICIENCY_NOT_SATISFIED/);});
test('external state or command input cannot set SATISFIED',async()=>{const f=await admittedFocused(),draft=clone(f.state);delete draft.state_hash;const goal=clone(draft.goals[0]);delete goal.goal_fingerprint;goal.status='SATISFIED';draft.goals=[createGoalInstance(goal)];draft.open_obligations=[];assert.throws(()=>createProtocolState(draft),/SATISFIED_GOAL_REQUIRES_SUFFICIENCY_RUNTIME/);});
test('closure is deterministic and focused slice reaches COMPLETE in a separate mutation',async()=>{const f=await admittedFocused(),evaluation=evaluate(f),assessed=applySufficiencyEvaluation(f.state,evaluation,{clock:GOAL_CLOCK}),a=evaluateProtocolClosure({state:assessed,sufficiencyEvaluations:[evaluation]}),b=evaluateProtocolClosure({state:assessed,sufficiencyEvaluations:[evaluation]}),complete=applyProtocolClosure(assessed,a,{clock:CLOSURE_CLOCK});assert.equal(a.status,'COMPLETE');assert.equal(a.closure_fingerprint,b.closure_fingerprint);assert.equal(complete.status,'COMPLETE');assert.equal(complete.state_version,assessed.state_version+1);assert.equal(complete.previous_state_hash,assessed.state_hash);});
test('N15 another REQUIRED PENDING blocks COMPLETE',async()=>{const f=await admittedFocused(),evaluation=evaluate(f),assessed=applySufficiencyEvaluation(f.state,evaluation,{clock:GOAL_CLOCK}),state=withGoal(assessed,extraGoal(f,'REQUIRED'));assert.equal(evaluateProtocolClosure({state,sufficiencyEvaluations:[evaluation]}).status,'PENDING');});
test('active CONDITIONAL PENDING blocks while SUPPLEMENTAL PENDING does not',async()=>{const f=await admittedFocused(),evaluation=evaluate(f),assessed=applySufficiencyEvaluation(f.state,evaluation,{clock:GOAL_CLOCK});assert.equal(evaluateProtocolClosure({state:withGoal(assessed,extraGoal(f,'CONDITIONAL')),sufficiencyEvaluations:[evaluation]}).status,'PENDING');assert.equal(evaluateProtocolClosure({state:withGoal(assessed,extraGoal(f,'SUPPLEMENTAL')),sufficiencyEvaluations:[evaluation]}).status,'COMPLETE');});
test('N17/N18 active execution and blocking selection prevent COMPLETE',async()=>{const f=await admittedFocused(),evaluation=evaluate(f),state=applySufficiencyEvaluation(f.state,evaluation,{clock:GOAL_CLOCK});assert.equal(evaluateProtocolClosure({state,sufficiencyEvaluations:[evaluation],activeExecutionRefs:['attempt']}).status,'PENDING');assert.equal(evaluateProtocolClosure({state,sufficiencyEvaluations:[evaluation],blockingSemanticSelection:true}).status,'PENDING');});
test('technical failure and budget conditions do not fabricate TERMINAL_PARTIAL',async()=>{const f=await admittedFocused();assert.equal(evaluateProtocolClosure({state:f.state,sufficiencyEvaluations:[]}).status,'PENDING');assert.notEqual(evaluateProtocolClosure({state:f.state,sufficiencyEvaluations:[],activeExecutionRefs:[]}).status,'TERMINAL_PARTIAL');});
