import test from 'node:test';import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { getCapabilityContract } from '../../lib/protocol/planning/index.js';
import { appendAdmittedEvidence, createEvidenceLedger, createEvidenceRecordV2, createTypedClaim, evaluateEvidenceAdmission, executeAuthorizedMotor, projectObservedValue, validateLongitudinalVentasRawResult } from '../../lib/protocol/execution/index.js';
import { authorizedFocused, EXEC_CLOCK, executeCommand, motorFor } from './execution-helpers.js';

async function candidate(){const f=await authorizedFocused(),m=motorFor(),x=await executeAuthorizedMotor(f.state,f.authorization,executeCommand(f.state,f.authorization),{applicabilityDecisions:f.applicabilityDecisions,motorResolver:m.resolver,resultValidator:validateLongitudinalVentasRawResult,clock:EXEC_CLOCK});const evidence=projectObservedValue({authorization:f.authorization,executionAttempt:x.attempt,rawResult:x.rawResult,observed_at:EXEC_CLOCK,admitted_at:EXEC_CLOCK,question_contract_ref:f.state.question_contract_hash});const ledger=createEvidenceLedger(f.state.protocol_id),context={state:f.state,authorization:f.authorization,executionAttempt:x.attempt,capabilityContract:getCapabilityContract('LONGITUDINAL/VENTAS'),availabilitySnapshot:f.availability,ledger};return {...f,...x,evidence,ledger,context};}
function rebuild(record,mutate){const d=clone(record);delete d.evidence_fingerprint;mutate(d);return createEvidenceRecordV2(d);}
test('valid exact EvidenceRecord is admitted by all 25 predicates',async()=>{const f=await candidate(),d=evaluateEvidenceAdmission(f.evidence,f.context);assert.equal(d.status,'ADMITTED');assert.equal(d.predicate_results.length,25);assert.ok(d.predicate_results.every(v=>v.passed));assert.deepEqual(d.reason_codes,[]);});
test('admission evaluation is pure and deterministic',async()=>{const f=await candidate(),evidenceBefore=clone(f.evidence),stateBefore=clone(f.state),a=evaluateEvidenceAdmission(f.evidence,{...f.context,decision_id:'opaque-a'}),b=evaluateEvidenceAdmission(f.evidence,{...f.context,decision_id:'opaque-b'});assert.equal(a.decision_fingerprint,b.decision_fingerprint);assert.deepEqual(f.evidence,evidenceBefore);assert.deepEqual(f.state,stateBefore);});
for(const [name,mutate,reason] of [
 ['subject',d=>d.semantic_binding.subject.canonical_id='other','SUBJECT_MISMATCH'],['measure',d=>d.semantic_binding.measure='OTHER','MEASURE_MISMATCH'],['universe',d=>d.semantic_binding.commercial_universe='OWN_STORES','UNIVERSE_MISMATCH'],['organization',d=>d.semantic_binding.organization_scope='OTHER','ORGANIZATION_SCOPE_MISMATCH'],['period',d=>d.semantic_binding.period.date_to='2026-09-30','PERIOD_MISMATCH'],['grain',d=>d.semantic_binding.grain='STORE','GRAIN_MISMATCH'],['comparison',d=>d.semantic_binding.comparison='YOY','COMPARISON_MISMATCH'],['availability',d=>d.availability_snapshot_ref='sha256:other','AVAILABILITY_MISMATCH'],
])test(`admission rejects exact ${name} mismatch`,async()=>{const f=await candidate(),bad=rebuild(f.evidence,mutate),d=evaluateEvidenceAdmission(bad,{...f.context});assert.equal(d.status,'REJECTED');assert.ok(d.reason_codes.includes(reason));});
test('admission requires successful execution and authorized claim',async()=>{const f=await candidate();const failed=clone(f.attempt);failed.status='FAILED_FINAL';const d=evaluateEvidenceAdmission(f.evidence,{...f.context,executionAttempt:failed});assert.equal(d.status,'REJECTED');assert.ok(d.reason_codes.includes('EXECUTION_NOT_SUCCEEDED'));const bad=clone(f.evidence);bad.claims[0].claim_type='TEMPORAL_CHANGE';const unauthorized=evaluateEvidenceAdmission(bad,f.context);assert.equal(unauthorized.status,'REJECTED');assert.ok(unauthorized.reason_codes.includes('CLAIM_NOT_AUTHORIZED'));assert.ok(unauthorized.reason_codes.includes('UNSUPPORTED_INFERENCE'));});
test('raw payload is forbidden and missing authority provenance is rejected',async()=>{const f=await candidate(),raw=clone(f.evidence);raw.raw_payload={series:[]};let d=evaluateEvidenceAdmission(raw,f.context);assert.ok(d.reason_codes.includes('RAW_PAYLOAD_FORBIDDEN'));const auth=clone(f.evidence);auth.authority_refs=[];d=evaluateEvidenceAdmission(auth,f.context);assert.ok(d.reason_codes.includes('AUTHORITY_MISMATCH'));});
test('ledger appends only ADMITTED evidence, is immutable and rejects duplicates',async()=>{const f=await candidate(),d=evaluateEvidenceAdmission(f.evidence,f.context),before=clone(f.ledger),next=appendAdmittedEvidence(f.ledger,d,f.evidence);assert.equal(next.records.length,1);assert.equal(next.previous_ledger_hash,f.ledger.ledger_hash);assert.deepEqual(f.ledger,before);assert.ok(Object.isFrozen(next.records[0]));const duplicate=evaluateEvidenceAdmission(f.evidence,{...f.context,ledger:next});assert.equal(duplicate.status,'REJECTED');assert.ok(duplicate.reason_codes.includes('DUPLICATE_EVIDENCE'));assert.throws(()=>appendAdmittedEvidence(next,d,f.evidence),/DUPLICATE_EVIDENCE/);});
test('evidence fingerprint excludes opaque id/runtime times but changes with value, period and authority',async()=>{const f=await candidate(),a=rebuild(f.evidence,d=>{d.evidence_id='opaque-a';d.observed_at='2026-09-15T13:00:00.000Z';d.admitted_at='2026-09-15T13:00:00.000Z';}),b=rebuild(f.evidence,d=>{d.evidence_id='opaque-b';d.observed_at='2026-09-15T14:00:00.000Z';d.admitted_at='2026-09-15T14:00:00.000Z';});assert.equal(a.evidence_fingerprint,b.evidence_fingerprint);const changedValue=rebuild(f.evidence,d=>{const claim=clone(d.claims[0]);delete claim.claim_fingerprint;claim.value.amount+=1;d.claims[0]=createTypedClaim(claim);});for(const changed of [changedValue,rebuild(f.evidence,d=>d.semantic_binding.period.date_from='2026-07-01'),rebuild(f.evidence,d=>d.authority_refs[0]='sha256:changed')])assert.notEqual(changed.evidence_fingerprint,f.evidence.evidence_fingerprint);});
