import test from 'node:test';import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { executeAndAdmitEvidence, executeAuthorizedMotor, validateLongitudinalVentasRawResult } from '../../lib/protocol/execution/index.js';
import { authorizedFocused, EXEC_CLOCK, executeCommand, motorFor, rawVentas } from './execution-helpers.js';

async function run(options={}){const f=await authorizedFocused(),m=options.motor??motorFor();const out=await executeAndAdmitEvidence(f.state,f.authorization,executeCommand(f.state,f.authorization,options.command),{applicabilityDecisions:f.applicabilityDecisions,availabilitySnapshot:f.availability,motorResolver:m.resolver,clock:EXEC_CLOCK,...options.runtime});return {...f,m,out};}
test('focused WP08 E2E executes, admits one record and stops in ASSESSING with pending Goal',async()=>{const f=await run();assert.equal(f.m.counter.calls,1);assert.equal(f.out.attempt.status,'SUCCEEDED');assert.equal(f.out.admission.status,'ADMITTED');assert.equal(f.out.ledger.records.length,1);assert.equal(f.out.state.status,'ASSESSING');assert.equal(f.out.state.goals[0].status,'PENDING');assert.equal(f.out.state.open_obligations.length,1);assert.equal(f.out.state.terminal.status,'OPEN');assert.equal(f.out.state.state_version,f.state.state_version+1);assert.equal(f.out.state.previous_state_hash,f.state.state_hash);for(const forbidden of ['sufficiency','typed_signal','transition_rule','synthesis_packet'])assert.equal(JSON.stringify(f.out).toLowerCase().includes(forbidden),false);assert.equal(Object.hasOwn(f.out,'rawResult'),false);});
test('execute before/stale/wrong authorization never invokes motor',async()=>{const f=await authorizedFocused();for(const mutate of [c=>c.expected_state_version-=1,c=>c.authorization_ref.authorization_fingerprint='sha256:wrong']){const c=clone(executeCommand(f.state,f.authorization));delete c.command_fingerprint;mutate(c);const {createExecuteAuthorizationCommand}=await import('../../lib/protocol/execution/index.js');const command=createExecuteAuthorizationCommand(c),m=motorFor();await assert.rejects(()=>executeAuthorizedMotor(f.state,f.authorization,command,{applicabilityDecisions:f.applicabilityDecisions,motorResolver:m.resolver,resultValidator:validateLongitudinalVentasRawResult,clock:EXEC_CLOCK}));assert.equal(m.counter.calls,0);}});
test('altered authorization physical request or capability cannot invoke motor',async()=>{const f=await authorizedFocused();for(const mutate of [a=>a.physical_request.validated_input.date_to='2026-09-30',a=>a.capability.capability_id='OTHER']){const altered=clone(f.authorization);mutate(altered);const m=motorFor();await assert.rejects(()=>executeAuthorizedMotor(f.state,altered,executeCommand(f.state,f.authorization),{applicabilityDecisions:f.applicabilityDecisions,motorResolver:m.resolver,resultValidator:validateLongitudinalVentasRawResult,clock:EXEC_CLOCK}));assert.equal(m.counter.calls,0);}});
test('successful execution fingerprint is exactly-once and motor is not called twice',async()=>{const f=await authorizedFocused(),m=motorFor(),command=executeCommand(f.state,f.authorization),first=await executeAuthorizedMotor(f.state,f.authorization,command,{applicabilityDecisions:f.applicabilityDecisions,motorResolver:m.resolver,resultValidator:validateLongitudinalVentasRawResult,clock:EXEC_CLOCK});await assert.rejects(()=>executeAuthorizedMotor(f.state,f.authorization,command,{applicabilityDecisions:f.applicabilityDecisions,previousAttempts:[first.attempt],motorResolver:m.resolver,resultValidator:validateLongitudinalVentasRawResult,clock:EXEC_CLOCK}),/EXECUTION_ALREADY_SUCCEEDED/);assert.equal(m.counter.calls,1);});
for(const [name,error,status] of [['retryable',Object.assign(new Error('temporary'),{code:'TEMPORARY',retryable:true}),'FAILED_RETRYABLE'],['final',Object.assign(new Error('broken'),{code:'BROKEN'}),'FAILED_FINAL'],['timeout',Object.assign(new Error('late'),{code:'TIMEOUT'}),'TIMED_OUT']])test(`${name} technical failure creates no evidence and leaves Goal pending`,async()=>{const counter={calls:0},motor={counter,resolver:async()=>async()=>{counter.calls++;throw error;}},f=await run({motor});assert.equal(f.out.attempt.status,status);assert.equal(f.out.evidence,null);assert.equal(f.out.admission,null);assert.equal(f.out.ledger.records.length,0);assert.equal(f.out.state.goals[0].status,'PENDING');assert.notEqual(f.out.state.status,'COMPLETE');});
test('failed retryable execution alone may retry with a new immutable attempt',async()=>{const f=await authorizedFocused(),command=executeCommand(f.state,f.authorization),bad={resolver:async()=>async()=>{throw Object.assign(new Error('temporary'),{code:'TEMP',retryable:true});}},first=await executeAuthorizedMotor(f.state,f.authorization,command,{applicabilityDecisions:f.applicabilityDecisions,motorResolver:bad.resolver,resultValidator:validateLongitudinalVentasRawResult,clock:EXEC_CLOCK}),good=motorFor(),second=await executeAuthorizedMotor(f.state,f.authorization,command,{applicabilityDecisions:f.applicabilityDecisions,previousAttempts:[first.attempt],motorResolver:good.resolver,resultValidator:validateLongitudinalVentasRawResult,clock:EXEC_CLOCK});assert.equal(first.attempt.status,'FAILED_RETRYABLE');assert.equal(second.attempt.status,'SUCCEEDED');assert.notEqual(first.attempt.attempt_fingerprint,second.attempt.attempt_fingerprint);});
test('malformed physical result enters ledger neither as evidence nor technical business conclusion',async()=>{const f=await run({motor:motorFor(rawVentas({series:[]}))});assert.equal(f.out.attempt.status,'FAILED_FINAL');assert.equal(f.out.attempt.error.class,'UNEXPECTED_RESULT_SHAPE');assert.equal(f.out.ledger.records.length,0);assert.equal(f.out.state.goals[0].status,'PENDING');});
