import test from 'node:test';import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { executeAuthorizedMotor, projectObservedValue, validateLongitudinalVentasRawResult } from '../../lib/protocol/execution/index.js';
import { authorizedFocused, EXEC_CLOCK, executeCommand, motorFor, rawVentas } from './execution-helpers.js';

async function successful(){const f=await authorizedFocused(),m=motorFor();const x=await executeAuthorizedMotor(f.state,f.authorization,executeCommand(f.state,f.authorization),{applicabilityDecisions:f.applicabilityDecisions,motorResolver:m.resolver,resultValidator:validateLongitudinalVentasRawResult,clock:EXEC_CLOCK});return {...f,...x};}
test('registered-shape executor uses authorization request exactly and succeeds serially',async()=>{const f=await authorizedFocused();let seen;const x=await executeAuthorizedMotor(f.state,f.authorization,executeCommand(f.state,f.authorization),{applicabilityDecisions:f.applicabilityDecisions,motorResolver:async()=>async input=>{seen=input;return rawVentas();},resultValidator:validateLongitudinalVentasRawResult,clock:EXEC_CLOCK});assert.deepEqual(seen,f.authorization.physical_request.validated_input);assert.equal(x.attempt.status,'SUCCEEDED');assert.deepEqual(x.lifecycle.map(v=>v.status),['AUTHORIZED','RUNNING','SUCCEEDED']);});
test('projector copies exact series value and emits no comparative/risk/trajectory inference',async()=>{const f=await successful(),record=projectObservedValue({authorization:f.authorization,executionAttempt:f.attempt,rawResult:f.rawResult,observed_at:EXEC_CLOCK,admitted_at:EXEC_CLOCK,question_contract_ref:f.state.question_contract_hash});assert.equal(record.claims.length,1);assert.equal(record.claims[0].claim_type,'OBSERVED_VALUE');assert.equal(record.claims[0].value.amount,731);for(const value of ['TEMPORAL_CHANGE','RISK','TRAJECTORY','MARKET_POSITION','CAUSALITY'])assert.equal(JSON.stringify(record).includes(value),false);assert.equal(Object.hasOwn(record,'raw_payload'),false);});
test('projector is deterministic and runtime evidence id does not change semantic fingerprint',async()=>{const f=await successful(),base={authorization:f.authorization,executionAttempt:f.attempt,rawResult:f.rawResult,observed_at:EXEC_CLOCK,admitted_at:EXEC_CLOCK,question_contract_ref:f.state.question_contract_hash},a=projectObservedValue({...base,evidence_id:'opaque-a'}),b=projectObservedValue({...base,evidence_id:'opaque-b'});assert.equal(a.evidence_fingerprint,b.evidence_fingerprint);assert.equal(a.claims[0].claim_fingerprint,b.claims[0].claim_fingerprint);});
for(const [name,mutate,code] of [
 ['missing point',r=>r.series=[],'AUTHORIZED_RESULT_POINT_MISSING'],['duplicate point',r=>r.series.push(clone(r.series[0])),'AMBIGUOUS_RESULT_POINT'],['subject mismatch',r=>r.filters.brand_id=['other'],'PHYSICAL_SUBJECT_MISMATCH'],['period mismatch',r=>r.dateTo='2026-09-30','PHYSICAL_PERIOD_MISMATCH'],['universe mismatch',r=>r.commercial_scope.universe='OWN_STORES','PHYSICAL_UNIVERSE_MISMATCH'],['grain mismatch',r=>r.grain='STORE','UNEXPECTED_RESULT_SHAPE'],
])test(`exact projector rejects ${name}`,async()=>{const f=await authorizedFocused(),raw=rawVentas();mutate(raw);assert.throws(()=>validateLongitudinalVentasRawResult(raw,f.authorization),new RegExp(code));});
test('malformed result is FAILED_FINAL technical outcome and produces no evidence',async()=>{const f=await authorizedFocused(),m=motorFor(rawVentas({series:[]}));const x=await executeAuthorizedMotor(f.state,f.authorization,executeCommand(f.state,f.authorization),{applicabilityDecisions:f.applicabilityDecisions,motorResolver:m.resolver,resultValidator:validateLongitudinalVentasRawResult,clock:EXEC_CLOCK});assert.equal(x.attempt.status,'FAILED_FINAL');assert.equal(x.attempt.error.class,'UNEXPECTED_RESULT_SHAPE');assert.equal(Object.hasOwn(x,'rawResult'),false);});
