import { authorizeExecution } from '../../lib/protocol/planning/index.js';
import { createExecuteAuthorizationCommand } from '../../lib/protocol/execution/index.js';
import { AUTH_CLOCK, authorizationCommand, selectedFocused } from './planning-helpers.js';

export const EXEC_CLOCK='2026-09-15T12:03:00.000Z';
export async function authorizedFocused(){const f=await selectedFocused();const planned=authorizeExecution(f.state,authorizationCommand(f.state),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:AUTH_CLOCK});return {...f,state:planned.state,authorization:planned.authorization,applicabilityDecisions:planned.applicability_decisions};}
export function executeCommand(state,authorization,over={}){return createExecuteAuthorizationCommand({contract_version:'execute_authorization_command.v1',command_id:'execute_fixture',protocol_id:state.protocol_id,expected_state_version:state.state_version,authorization_ref:{authorization_id:authorization.authorization_id,authorization_fingerprint:authorization.authorization_fingerprint,execution_fingerprint:authorization.execution_fingerprint},...over});}
export function rawVentas(over={}){return {motor:'ventas_longitudinal_context_v01',version:'0.2',domain:'VENTAS',metric:'VIN_SALES',grain:'BRAND',timeGrain:'MONTH',dateFrom:'2026-08-01',dateTo:'2026-08-31',filters:{brand_id:['brand_fixture_foton']},series:[{period:'2026-08',value:731,absoluteChange:null,pctChange:null}],breakdown:null,temporalSemantics:{requestedDateFrom:'2026-08-01',requestedDateTo:'2026-08-31',effectiveDateFrom:'2026-08-01',effectiveDateTo:'2026-08-31',lastObservedDate:'2026-08-31',lastPeriodComplete:true,cutoffMode:'FULL_PERIOD'},coverage:{dimensionCoverage:[{dimension:'BRAND',resolved:731,unresolved:0,ambiguous:0,notApplicable:0,total:731}]},warnings:[],metadata:{unit:'N_VIN_RECOGNIZED_SALES'},commercial_scope:{universe:'COMPANY'},commercial_coverage:{status:'OK'},commercial_validation:{valid:true,violations:[]},...over};}
export function motorFor(raw=rawVentas(),counter={calls:0}){return {counter,resolver:async ref=>{if(ref!=='ventas_longitudinal_context_v01')throw Object.assign(new Error('wrong motor'),{code:'EXECUTOR_NOT_FOUND'});return async()=>{counter.calls+=1;return raw;};}};}
