import test from 'node:test';import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { createSelectActionCommand, selectAction } from '../../lib/protocol/runtime/index.js';
import { buildBroadRuntimeFixture } from '../../lib/protocol/runtime/fixtures.js';
import { authorizeExecution } from '../../lib/protocol/planning/index.js';
import { executeAndAdmitEvidence } from '../../lib/protocol/execution/index.js';
import { applySufficiencyEvaluation, buildSynthesisPacketV2, evaluateObservedResultSufficiencyV2 } from '../../lib/protocol/sufficiency/index.js';
import {
  assessBroadCandidateViability, assessInvestigationFixedPoint, createCandidateGoal, createSignalRule, createTransitionRule,
  createTypedSignal, deriveTypedSignals, evaluateTransitionRules, selectTransitionAction, SYNTHETIC_SIGNAL_RULES,
  SYNTHETIC_TRANSITION_RULES, TARGET_SIGNAL_RULES, TARGET_TRANSITION_RULES, validateCandidateGoal, validateTransitionRule, validateTypedSignal,
} from '../../lib/protocol/investigation/index.js';
import { admittedFocused, GOAL_CLOCK, SUFFICIENCY_CLOCK, SYNTHESIS_CLOCK } from './sufficiency-helpers.js';
import { rebuildClaim, rebuildEvidence } from './sufficiency-helpers.js';
import { authorizationCommand } from './planning-helpers.js';
import { authorizedFocused, executeCommand, motorFor } from './execution-helpers.js';

const CLOCKS={viability:'2026-09-15T12:00:30.000Z',selection:'2026-09-15T12:01:00.000Z',auth:'2026-09-15T12:02:00.000Z',exec:'2026-09-15T12:03:00.000Z',assessment:'2026-09-15T12:06:00.000Z',transition:'2026-09-15T12:07:00.000Z'};
function command(state,index=0,id='selection'){const action=state.actions[index];return createSelectActionCommand({contract_version:'select_action_command.v1',command_id:id,protocol_id:state.protocol_id,expected_state_version:state.state_version,action_id:action.action_id,action_fingerprint:action.action_fingerprint});}
async function assessedFocused(){const f=await admittedFocused(),evaluation=evaluateObservedResultSufficiencyV2({state:f.state,goal:f.goal,ledger:f.ledger,questionContract:f.question,universeResolution:f.resolution,availabilitySnapshot:f.availability,evaluated_at:SUFFICIENCY_CLOCK}),state=applySufficiencyEvaluation(f.state,evaluation,{clock:GOAL_CLOCK});return {...f,evaluation,state};}
async function selectedBroad(){const f=await buildBroadRuntimeFixture(),viable=assessBroadCandidateViability(f.state,{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:CLOCKS.viability}),state=selectAction(viable,command(viable),{clock:CLOCKS.selection});return {...f,initial:f.state,viable,state};}

test('BROAD starts with zero REQUIRED goals and viability offers only executable semantic Actions',async()=>{const f=await buildBroadRuntimeFixture();assert.equal(f.state.goals.length,0);assert.equal(f.state.initial_goal_candidates.length,4);const next=assessBroadCandidateViability(f.state,{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:CLOCKS.viability});assert.deepEqual(next.actions.map(item=>item.goal_type),['OBSERVED_RESULT']);assert.equal(next.selected_action_ref.status,'OMITTED');assert.equal(next.pending_execution_objective.status,'OMITTED');assert.equal(JSON.stringify(next.actions).includes('LONGITUDINAL/VENTAS'),false);});
test('explicit broad selection activates exactly one REQUIRED goal and no sibling',async()=>{const f=await selectedBroad();assert.equal(f.state.goals.length,1);assert.equal(f.state.goals[0].goal_type,'OBSERVED_RESULT');assert.equal(f.state.goals[0].evidence_class,'REQUIRED');assert.equal(f.state.goals[0].origin,'USER_SELECTED');assert.equal(f.state.initial_goal_candidates.length,0);assert.equal(f.state.physical_authorization_refs.length,0);});
test('broad selected OBSERVED_RESULT follows normal target path and completes with zero production signals',async()=>{const f=await selectedBroad(),planned=authorizeExecution(f.state,authorizationCommand(f.state),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:CLOCKS.auth}),motor=motorFor(),executed=await executeAndAdmitEvidence(planned.state,planned.authorization,executeCommand(planned.state,planned.authorization),{applicabilityDecisions:planned.applicability_decisions,availabilitySnapshot:f.availability,motorResolver:motor.resolver,clock:CLOCKS.exec}),evaluation=evaluateObservedResultSufficiencyV2({state:executed.state,goal:executed.state.goals[0],ledger:executed.ledger,questionContract:f.question,universeResolution:f.resolution,availabilitySnapshot:f.availability,evaluated_at:SUFFICIENCY_CLOCK}),satisfied=applySufficiencyEvaluation(executed.state,evaluation,{clock:GOAL_CLOCK}),assessed=assessInvestigationFixedPoint({state:satisfied,ledger:executed.ledger,signalRules:TARGET_SIGNAL_RULES,transitionRules:TARGET_TRANSITION_RULES,sufficiencyEvaluations:[evaluation],availabilitySnapshot:f.availability,clock:CLOCKS.assessment}),packet=buildSynthesisPacketV2({questionContract:f.question,protocolState:assessed.state,sufficiencyEvaluations:[evaluation],evidenceRecords:executed.ledger.records,universeResolution:f.resolution,availabilitySnapshot:f.availability,created_at:SYNTHESIS_CLOCK});assert.equal(motor.counter.calls,1);assert.equal(assessed.signals.length,0);assert.equal(assessed.candidates.length,0);assert.equal(assessed.state.status,'COMPLETE');assert.equal(packet.question.operation,'ASSESS');assert.deepEqual(packet.question.concepts,['SIGNAL']);assert.equal(packet.authorized_claims.length,1);});

test('registered synthetic rule derives deterministic provenance-complete TypedSignal only from admitted evidence',async()=>{const f=await assessedFocused(),a=deriveTypedSignals({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.assessment}),b=deriveTypedSignals({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.transition});assert.equal(a.length,1);assert.equal(validateTypedSignal(a[0]),true);assert.equal(a[0].signal_fingerprint,b[0].signal_fingerprint);assert.deepEqual(a[0].source_evidence_refs,[f.out.evidence.evidence_fingerprint]);assert.equal(JSON.stringify(a[0]).includes('capability'),false);const empty=clone(f.ledger);empty.records=[];empty.ledger_version=0;delete empty.ledger_hash;const {createEvidenceLedgerValue}=await import('../../lib/protocol/execution/index.js');assert.equal(deriveTypedSignals({state:f.state,ledger:createEvidenceLedgerValue(empty),signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.assessment}).length,0);});
test('stale evidence and missing registered rule derive no signal',async()=>{const f=await assessedFocused();assert.equal(deriveTypedSignals({state:f.state,ledger:f.ledger,signalRules:[],created_at:CLOCKS.assessment}).length,0);assert.equal(deriveTypedSignals({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,evidenceLifecycle:[{evidence_ref:f.out.evidence.evidence_fingerprint,status:'STALE'}],created_at:CLOCKS.assessment}).length,0);});
test('TransitionRule projects a semantic CONDITIONAL CandidateGoal without activation',async()=>{const f=await assessedFocused(),signals=deriveTypedSignals({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.assessment}),projected=evaluateTransitionRules({state:f.state,signals,transitionRules:SYNTHETIC_TRANSITION_RULES});assert.equal(projected.length,1);assert.equal(validateCandidateGoal(projected[0].candidate),true);assert.equal(projected[0].candidate.evidence_class,'CONDITIONAL');assert.equal(f.state.goals.length,1);assert.equal(JSON.stringify(projected).includes('capability'),false);});
test('contracts reject physical identity, REQUIRED target and open binding operators',async()=>{const f=await assessedFocused(),signals=deriveTypedSignals({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.assessment}),candidate=evaluateTransitionRules({state:f.state,signals,transitionRules:SYNTHETIC_TRANSITION_RULES})[0].candidate;for(const [value,validator] of [[{...clone(candidate),capability_id:'x'},validateCandidateGoal],[{...clone(SYNTHETIC_TRANSITION_RULES[0]),capability_id:'x'},validateTransitionRule]])assert.throws(()=>validator(value),/UNKNOWN_FIELD|FORBIDDEN_FIELD/);for(const mutate of [d=>d.target_evidence_class='REQUIRED',d=>d.binding_rules[0].operator='LOOKUP']){const draft=clone(SYNTHETIC_TRANSITION_RULES[0]);delete draft.rule_fingerprint;mutate(draft);assert.throws(()=>createTransitionRule(draft));}});
test('fixed point is bounded, monotonic and idempotent without selecting or executing',async()=>{const f=await assessedFocused(),first=assessInvestigationFixedPoint({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,transitionRules:SYNTHETIC_TRANSITION_RULES,sufficiencyEvaluations:[f.evaluation],availabilitySnapshot:f.availability,clock:CLOCKS.assessment});assert.equal(first.signals.length,1);assert.equal(first.candidates.length,1);assert.equal(first.state.actions.length,1);assert.equal(first.state.goals.length,1);assert.equal(first.state.status,'AWAITING_SELECTION');assert.equal(first.state.physical_authorization_refs.length,f.state.physical_authorization_refs.length);const second=assessInvestigationFixedPoint({state:first.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,transitionRules:SYNTHETIC_TRANSITION_RULES,existingSignals:first.signals,existingCandidates:first.candidates,sufficiencyEvaluations:[f.evaluation],availabilitySnapshot:f.availability,clock:CLOCKS.transition});assert.equal(second.state,first.state);assert.equal(second.signals.length,1);assert.equal(second.candidates.length,1);});
test('transition Action requires explicit fresh selection and activates one CONDITIONAL goal only',async()=>{const f=await assessedFocused(),fixed=assessInvestigationFixedPoint({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,transitionRules:SYNTHETIC_TRANSITION_RULES,sufficiencyEvaluations:[f.evaluation],availabilitySnapshot:f.availability,clock:CLOCKS.assessment});assert.throws(()=>selectTransitionAction(fixed.state,{...command(fixed.state),expected_state_version:fixed.state.state_version-1},{candidates:fixed.candidates,clock:CLOCKS.transition}),/FINGERPRINT_MISMATCH|STALE_STATE_VERSION/);const selected=selectTransitionAction(fixed.state,command(fixed.state,0,'transition'),{candidates:fixed.candidates,clock:CLOCKS.transition});assert.equal(selected.goals.length,2);assert.equal(selected.goals[1].evidence_class,'CONDITIONAL');assert.equal(selected.goals[1].origin,'TRANSITION_RULE');assert.equal(selected.goals[1].status,'PENDING');assert.equal(selected.physical_authorization_refs.length,f.state.physical_authorization_refs.length);assert.equal(selected.pending_execution_objective.status,'PENDING');});
test('SUPPLEMENTAL candidates do not block closure while CONDITIONAL candidates do',async()=>{const f=await assessedFocused(),conditional=assessInvestigationFixedPoint({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,transitionRules:SYNTHETIC_TRANSITION_RULES,sufficiencyEvaluations:[f.evaluation],availabilitySnapshot:f.availability,clock:CLOCKS.assessment});assert.notEqual(conditional.state.status,'COMPLETE');const draft=clone(SYNTHETIC_TRANSITION_RULES[0]);delete draft.rule_fingerprint;draft.transition_rule_id='fixture.supplemental';draft.target_evidence_class='SUPPLEMENTAL';const supplemental=assessInvestigationFixedPoint({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,transitionRules:[createTransitionRule(draft)],sufficiencyEvaluations:[f.evaluation],availabilitySnapshot:f.availability,clock:CLOCKS.assessment});assert.equal(supplemental.state.status,'COMPLETE');assert.equal(supplemental.state.actions.length,0);});
test('iteration cap fails loudly and LLM-style budget or capability fields are rejected',async()=>{const f=await assessedFocused(),state=clone(f.state);state.budget.max_fixed_point_iterations=1;delete state.state_hash;const {createProtocolState}=await import('../../lib/protocol/runtime/index.js');const bounded=createProtocolState(state);assert.throws(()=>assessInvestigationFixedPoint({state:bounded,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,transitionRules:SYNTHETIC_TRANSITION_RULES,sufficiencyEvaluations:[f.evaluation],availabilitySnapshot:f.availability,clock:CLOCKS.assessment}),/FIXED_POINT_ITERATION_CAP_REACHED/);const signal=clone((deriveTypedSignals({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.assessment}))[0]);signal.capability_id='x';assert.throws(()=>createTypedSignal(signal));const rule=clone(SYNTHETIC_SIGNAL_RULES[0]);delete rule.rule_fingerprint;rule.predicate.operator='LLM';assert.throws(()=>createSignalRule(rule));});

test('signal, candidate and transition activation fingerprints ignore opaque ids but bind semantic mutation',async()=>{const f=await assessedFocused(),signal=deriveTypedSignals({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.assessment})[0],signalDraft=clone(signal);delete signalDraft.signal_fingerprint;signalDraft.signal_id='opaque';signalDraft.created_at=CLOCKS.transition;assert.equal(createTypedSignal(signalDraft).signal_fingerprint,signal.signal_fingerprint);const projected=evaluateTransitionRules({state:f.state,signals:[signal],transitionRules:SYNTHETIC_TRANSITION_RULES})[0],candidateDraft=clone(projected.candidate);delete candidateDraft.candidate_fingerprint;candidateDraft.candidate_id='opaque';candidateDraft.protocol_id='opaque';candidateDraft.state_version+=100;assert.equal(createCandidateGoal(candidateDraft).candidate_fingerprint,projected.candidate.candidate_fingerprint);candidateDraft.depth+=1;assert.notEqual(createCandidateGoal(candidateDraft).candidate_fingerprint,projected.candidate.candidate_fingerprint);const again=evaluateTransitionRules({state:f.state,signals:[signal],transitionRules:SYNTHETIC_TRANSITION_RULES})[0];assert.equal(again.activation_fingerprint,projected.activation_fingerprint);});
test('evidence ordering is irrelevant and incompatible exact values conservatively derive no signal',async()=>{const f=await assessedFocused(),copy=rebuildEvidence(f.out.evidence,d=>{d.evidence_version=2;}),conflict=rebuildEvidence(f.out.evidence,d=>{d.evidence_version=3;d.claims[0]=rebuildClaim(d.claims[0],c=>{c.value.amount+=1;});d.provenance.typed_claim_fingerprints=[d.claims[0].claim_fingerprint];}),{createEvidenceLedgerValue}=await import('../../lib/protocol/execution/index.js');const ledger=records=>createEvidenceLedgerValue({contract_version:'evidence_ledger.v1',protocol_id:f.ledger.protocol_id,ledger_version:records.length,records,previous_ledger_hash:f.ledger.previous_ledger_hash}),a=deriveTypedSignals({state:f.state,ledger:ledger([f.out.evidence,copy]),signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.assessment}),b=deriveTypedSignals({state:f.state,ledger:ledger([copy,f.out.evidence]),signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.assessment});assert.deepEqual(a.map(item=>item.signal_fingerprint),b.map(item=>item.signal_fingerprint));assert.equal(deriveTypedSignals({state:f.state,ledger:ledger([f.out.evidence,conflict]),signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.assessment}).length,0);});
test('signal and transition derivation are pure and cannot widen admitted TypedClaims',async()=>{const f=await assessedFocused(),before={state:clone(f.state),ledger:clone(f.ledger)},signals=deriveTypedSignals({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.assessment}),stateBefore=clone(f.state),projected=evaluateTransitionRules({state:f.state,signals,transitionRules:SYNTHETIC_TRANSITION_RULES});assert.deepEqual({state:f.state,ledger:f.ledger},before);assert.deepEqual(f.state,stateBefore);assert.equal(projected.length,1);assert.equal(f.ledger.records[0].claims.length,1);assert.equal(f.ledger.records[0].claims[0].claim_type,'OBSERVED_VALUE');assert.equal(Object.hasOwn(signals[0],'claims'),false);});
test('fixed point is deterministic and deduplicates preauthorized artifacts',async()=>{const f=await assessedFocused(),input={state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,transitionRules:SYNTHETIC_TRANSITION_RULES,sufficiencyEvaluations:[f.evaluation],availabilitySnapshot:f.availability,clock:CLOCKS.assessment},a=assessInvestigationFixedPoint(input),b=assessInvestigationFixedPoint(input);assert.equal(a.state.state_hash,b.state.state_hash);assert.deepEqual(a.state.typed_signal_refs,[a.signals[0].signal_fingerprint]);assert.deepEqual(a.state.candidate_goal_refs,[a.candidates[0].candidate_fingerprint]);assert.equal(new Set(a.state.transition_activation_refs).size,1);});
test('unregistered existing signal/candidate injection is rejected by fixed point',async()=>{const f=await assessedFocused(),signals=deriveTypedSignals({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,created_at:CLOCKS.assessment}),candidate=evaluateTransitionRules({state:f.state,signals,transitionRules:SYNTHETIC_TRANSITION_RULES})[0].candidate;assert.throws(()=>assessInvestigationFixedPoint({state:f.state,ledger:f.ledger,signalRules:[],transitionRules:[],existingSignals:signals,availabilitySnapshot:f.availability,clock:CLOCKS.assessment}),/UNAUTHORIZED_EXISTING_SIGNAL/);assert.throws(()=>assessInvestigationFixedPoint({state:f.state,ledger:f.ledger,signalRules:SYNTHETIC_SIGNAL_RULES,transitionRules:[],existingSignals:signals,existingCandidates:[candidate],availabilitySnapshot:f.availability,clock:CLOCKS.assessment}),/UNAUTHORIZED_EXISTING_CANDIDATE/);});
test('fixed point refuses an execution lifecycle state',async()=>{const f=await authorizedFocused(),{createEvidenceLedger}=await import('../../lib/protocol/execution/index.js');assert.throws(()=>assessInvestigationFixedPoint({state:f.state,ledger:createEvidenceLedger(f.state.protocol_id),availabilitySnapshot:f.availability,clock:CLOCKS.assessment}),/ASSESSMENT_REQUIRES_NO_ACTIVE_EXECUTION/);});
