import test from 'node:test';
import assert from 'node:assert/strict';
import { clone, fingerprint } from '../../lib/protocol/primitives.js';
import { LONGITUDINAL_VENTAS_NATIVE_CAPABILITY, authorizeExecution, buildExecutionFingerprintPayload, projectLongitudinalVentasRequest, validateLongitudinalVentasProjection } from '../../lib/protocol/planning/index.js';
import { buildFocusedRuntimeFixture } from '../../lib/protocol/runtime/fixtures.js';
import { AUTH_CLOCK, authorizationCommand, reAvailability, reCapability, selectedFocused } from './planning-helpers.js';

async function authorize(overrides={}){const f=await selectedFocused(),command=authorizationCommand(f.state,overrides.command);const result=authorizeExecution(f.state,command,{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:AUTH_CLOCK,...overrides.options});return {...f,command,result};}

test('focused authorization E2E selects audited LONGITUDINAL/VENTAS and stops before execution',async()=>{const {state,result}=await authorize(),a=result.authorization;assert.equal(result.physical_selection.capability_id,'LONGITUDINAL/VENTAS');assert.equal(a.status,'AUTHORIZED_READY');assert.equal(a.physical_request.motor_ref,'ventas_longitudinal_context_v01');assert.deepEqual(a.physical_request.validated_input,{metric:'VIN_SALES',grain:'BRAND',filters:{brand_id:['brand_fixture_foton']},commercial_universe:'COMPANY',date_from:'2026-08-01',date_to:'2026-08-31',time_grain:'MONTH',cutoff_mode:'FULL_PERIOD'});assert.deepEqual(a.authorized_claim_types,['OBSERVED_VALUE']);assert.equal(result.state.status,'EXECUTING');assert.equal(result.state.goals[0].status,'PENDING');assert.equal(result.state.terminal.status,'OPEN');assert.equal(Object.hasOwn(result,'evidence'),false);assert.equal(Object.hasOwn(result,'execution_result'),false);assert.equal(state.status,'AWAITING_SELECTION');});
test('authorization increments state once, chains hash and preserves immutable source',async()=>{const f=await selectedFocused(),before=clone(f.state),out=authorizeExecution(f.state,authorizationCommand(f.state),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:AUTH_CLOCK});assert.equal(out.state.state_version,f.state.state_version+1);assert.equal(out.state.previous_state_hash,f.state.state_hash);assert.deepEqual(f.state,before);assert.equal(out.state.physical_authorization_refs.length,1);assert.equal(out.state.pending_execution_objective.status,'AUTHORIZED');});
test('initialization never auto-authorizes even when one Action exists',async()=>{const {state}=await buildFocusedRuntimeFixture();assert.equal(state.actions.length,1);assert.equal(state.physical_authorization_refs.length,0);assert.equal(state.pending_execution_objective.status,'OMITTED');});
test('authorization before explicit Action selection is rejected',async()=>{const f=await buildFocusedRuntimeFixture();const command={contract_version:'authorize_execution_command.v1',command_id:'early',protocol_id:f.state.protocol_id,expected_state_version:f.state.state_version,selected_action_ref:{action_id:f.state.actions[0].action_id,action_fingerprint:f.state.actions[0].action_fingerprint},pending_objective_fingerprint:'sha256:none'};const {createAuthorizeExecutionCommand}=await import('../../lib/protocol/planning/index.js');assert.throws(()=>authorizeExecution(f.state,createAuthorizeExecutionCommand(command),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:AUTH_CLOCK}),/SELECTED_ACTION_MISMATCH|PENDING_EXECUTION_OBJECTIVE_REQUIRED/);});
test('stale state and wrong objective/action fingerprints cannot authorize',async()=>{const f=await selectedFocused();assert.throws(()=>authorizeExecution(f.state,authorizationCommand(f.state,{expected_state_version:f.state.state_version-1}),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:AUTH_CLOCK}),/STALE_STATE_VERSION/);assert.throws(()=>authorizeExecution(f.state,authorizationCommand(f.state,{pending_objective_fingerprint:'sha256:wrong'}),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:AUTH_CLOCK}),/PENDING_OBJECTIVE_FINGERPRINT_MISMATCH/);assert.throws(()=>authorizeExecution(f.state,authorizationCommand(f.state,{selected_action_ref:{action_id:'wrong',action_fingerprint:'sha256:wrong'}}),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:AUTH_CLOCK}),/SELECTED_ACTION_MISMATCH/);});
test('authorization replay/duplicate cannot mutate authorized state',async()=>{const f=await selectedFocused(),command=authorizationCommand(f.state),first=authorizeExecution(f.state,command,{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:AUTH_CLOCK}),before=clone(first.state);assert.throws(()=>authorizeExecution(first.state,command,{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:AUTH_CLOCK}),/STALE_STATE_VERSION|INVALID_STATE_TRANSITION/);assert.deepEqual(first.state,before);});
test('no viable capability produces no ExecutionAuthorization',async()=>{const f=await selectedFocused(),wrong=reCapability(LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,d=>d.supported_bindings.commercial_universes=['OWN_STORES']);assert.throws(()=>authorizeExecution(f.state,authorizationCommand(f.state),{universeResolution:f.resolution,availabilitySnapshot:f.availability,capabilityContracts:[wrong],clock:AUTH_CLOCK}),/NO_APPLICABLE_CAPABILITY/);});
test('physical projector validates actual parser and exact semantic equivalence',async()=>{const f=await selectedFocused(),goal=f.state.goals[0],request=projectLongitudinalVentasRequest({goal,capabilityContract:LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,universeResolution:f.resolution});const validated=validateLongitudinalVentasProjection(request,{goal,capabilityContract:LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,universeResolution:f.resolution});assert.equal(validated.parsed.commercialUniverse,'COMPANY');assert.equal(validated.parsed.dateFrom,'2026-08-01');assert.equal(validated.parsed.dateTo,'2026-08-31');});
for(const [name,mutate,code] of [
  ['projector period mutation',r=>r.validated_input.date_to='2026-09-30','PHYSICAL_PERIOD_MUTATION'],
  ['projector universe mutation',r=>r.validated_input.commercial_universe='OWN_STORES','PHYSICAL_UNIVERSE_MUTATION'],
  ['projector subject mutation',r=>r.validated_input.filters.brand_id=['other'],'PHYSICAL_SUBJECT_MUTATION'],
  ['projector invalid physical input',r=>r.validated_input.metric='INVALID','INVALID_METRIC'],
]) test(`${name} prevents authorization`,async()=>{const f=await selectedFocused();const bad=({goal,capabilityContract,universeResolution})=>{const r=clone(projectLongitudinalVentasRequest({goal,capabilityContract,universeResolution}));mutate(r);return r;};assert.throws(()=>authorizeExecution(f.state,authorizationCommand(f.state),{universeResolution:f.resolution,availabilitySnapshot:f.availability,requestProjectors:{'LONGITUDINAL/VENTAS':bad},clock:AUTH_CLOCK}),new RegExp(code));});
test('same semantic physical execution has deterministic execution fingerprint despite authorization id',async()=>{const a=await authorize({options:{authorization_id:'opaque_a'}}),b=await authorize({options:{authorization_id:'opaque_b'}});assert.equal(a.result.authorization.execution_fingerprint,b.result.authorization.execution_fingerprint);assert.notEqual(a.result.authorization.authorization_id,b.result.authorization.authorization_id);});
test('capability version, availability, authority and physical request mutations alter execution fingerprint',async()=>{const f=await selectedFocused(),goal=f.state.goals[0],request=projectLongitudinalVentasRequest({goal,capabilityContract:LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,universeResolution:f.resolution}),base={goal,capabilityContract:LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,universeResolution:f.resolution,availabilitySnapshot:f.availability,physicalRequest:request,authorizedClaimTypes:['OBSERVED_VALUE']},original=fingerprint(buildExecutionFingerprintPayload(base));const capability=reCapability(base.capabilityContract,d=>d.capability_version='0.4');const availability=reAvailability(base.availabilitySnapshot,d=>d.observed_at='2026-09-15T13:00:00.000Z');const authority=clone(base.universeResolution);authority.authority.identity_ref.snapshot_ref='changed';const physicalRequest=clone(request);physicalRequest.validated_input.date_from='2026-07-01';for(const mutation of [{...base,capabilityContract:capability},{...base,availabilitySnapshot:availability},{...base,universeResolution:authority},{...base,physicalRequest}])assert.notEqual(fingerprint(buildExecutionFingerprintPayload(mutation)),original);});
test('authorization output is internal while original public Action never gains physical fields',async()=>{const f=await selectedFocused(),actionBefore=clone(f.state.selected_action_ref),out=authorizeExecution(f.state,authorizationCommand(f.state),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:AUTH_CLOCK});assert.deepEqual(f.state.selected_action_ref,actionBefore);assert.equal(out.authorization.capability.capability_id,'LONGITUDINAL/VENTAS');assert.equal(JSON.stringify(f.state).includes('LONGITUDINAL/VENTAS'),false);});
