import test from 'node:test';
import assert from 'node:assert/strict';
import { LONGITUDINAL_VENTAS_NATIVE_CAPABILITY, rankApplicabilityDecisions, selectPhysicalCapability } from '../../lib/protocol/planning/index.js';
import { reAvailability, reCapability, selectedFocused } from './planning-helpers.js';

test('physical selection is deterministic and independent of registry order',async()=>{const f=await selectedFocused(),alternate=reCapability(LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,d=>{d.capability_id='ZZZ/SYNTHETIC';d.selection_metadata.specialization=99;});const input={pendingExecutionObjective:f.state.pending_execution_objective,goal:f.state.goals[0],universeResolution:f.resolution,availabilitySnapshot:f.availability};const a=selectPhysicalCapability({...input,capabilityContracts:[alternate,LONGITUDINAL_VENTAS_NATIVE_CAPABILITY]}),b=selectPhysicalCapability({...input,capabilityContracts:[LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,alternate]});assert.equal(a.selected.capability.capability_id,'LONGITUDINAL/VENTAS');assert.equal(a.selected.capability.capability_id,b.selected.capability.capability_id);});
test('lexical capability_id is the final deterministic tie-break',async()=>{const f=await selectedFocused(),a=reCapability(LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,d=>d.capability_id='A/SYNTHETIC'),z=reCapability(LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,d=>d.capability_id='Z/SYNTHETIC');const out=selectPhysicalCapability({pendingExecutionObjective:f.state.pending_execution_objective,goal:f.state.goals[0],capabilityContracts:[z,a],universeResolution:f.resolution,availabilitySnapshot:f.availability});assert.equal(out.selected.capability.capability_id,'A/SYNTHETIC');});
test('APPLICABLE ranks above LIMITED without weighted scoring',async()=>{const f=await selectedFocused(),availability=reAvailability(f.availability,d=>d.sources=d.sources.map(s=>s.source_domain==='SALES'?{...s,available_to:'2026-08-30',coverage:{status:'PARTIAL',ratio:.95}}:s)),exact=reCapability(LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,d=>{d.capability_id='EXACT';d.availability_requirements.required_coverage='PARTIAL';d.availability_requirements.minimum_coverage_ratio=.9;d.availability_requirements.through_period_end=false;d.availability_requirements.limited_coverage_permitted=false;d.coverage_requirements.full_closed_period_required=false;}),limited=reCapability(exact,d=>{d.capability_id='LIMITED';d.availability_requirements.limited_coverage_permitted=true;});const out=selectPhysicalCapability({pendingExecutionObjective:f.state.pending_execution_objective,goal:f.state.goals[0],capabilityContracts:[limited,exact],universeResolution:f.resolution,availabilitySnapshot:availability});assert.equal(out.selected.capability.capability_id,'EXACT');assert.deepEqual(out.decisions.map(x=>x.status).sort(),['APPLICABLE','APPLICABLE_WITH_LIMITED_COVERAGE']);});
test('semantic mismatch is discarded before ranking',async()=>{const f=await selectedFocused(),wrong=reCapability(LONGITUDINAL_VENTAS_NATIVE_CAPABILITY,d=>{d.capability_id='A/WRONG';d.supported_bindings.commercial_universes=['OWN_STORES'];d.selection_metadata.specialization=9999;});const out=selectPhysicalCapability({pendingExecutionObjective:f.state.pending_execution_objective,goal:f.state.goals[0],capabilityContracts:[wrong],universeResolution:f.resolution,availabilitySnapshot:f.availability});assert.equal(out.selected,null);assert.equal(out.decisions[0].status,'NOT_APPLICABLE');});
test('ranking rejects decision whose capability contract is absent',async()=>{const f=await selectedFocused();const out=selectPhysicalCapability({pendingExecutionObjective:f.state.pending_execution_objective,goal:f.state.goals[0],capabilityContracts:[LONGITUDINAL_VENTAS_NATIVE_CAPABILITY],universeResolution:f.resolution,availabilitySnapshot:f.availability});assert.throws(()=>rankApplicabilityDecisions(out.decisions,[]),/CAPABILITY_CONTRACT_NOT_FOUND/);});
