import test from 'node:test';
import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { LONGITUDINAL_VENTAS_NATIVE_CAPABILITY, evaluateNativeApplicability } from '../../lib/protocol/planning/index.js';
import { reAvailability, reCapability, reGoal, reResolution, selectedFocused } from './planning-helpers.js';

async function base(){const f=await selectedFocused();return {...f,goal:f.state.goals[0],capability:LONGITUDINAL_VENTAS_NATIVE_CAPABILITY};}
function evaluate(f,overrides={}){return evaluateNativeApplicability({goal:overrides.goal??f.goal,capabilityContract:overrides.capability??f.capability,universeResolution:overrides.resolution??f.resolution,availabilitySnapshot:overrides.availability??f.availability});}
function has(decision,code){return decision.reason_codes.includes(code);}

test('exact focused slice is APPLICABLE with all 22 predicates and OBSERVED_VALUE',async()=>{const f=await base(),d=evaluate(f);assert.equal(d.status,'APPLICABLE');assert.equal(d.predicate_results.length,22);assert.ok(d.predicate_results.every(x=>x.passed));assert.deepEqual(d.authorized_claim_types,['OBSERVED_VALUE']);});
test('same applicability inputs have deterministic decision fingerprint',async()=>{const f=await base();assert.equal(evaluate(f).decision_fingerprint,evaluate(f).decision_fingerprint);});
test('COMPANY cannot fall back to OWN_STORES capability',async()=>{const f=await base(),capability=reCapability(f.capability,d=>d.supported_bindings.commercial_universes=['OWN_STORES']),decision=evaluate(f,{capability});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(has(decision,'UNIVERSE_UNSUPPORTED'));});
test('OWN_STORES cannot fall back to COMPANY capability',async()=>{const f=await base(),resolution=reResolution(f.resolution,d=>d.membership.commercial_universe='OWN_STORES'),goal=reGoal(f.goal,d=>{d.universe_resolution_ref=resolution.resolution_fingerprint;d.bindings.commercial_universe='OWN_STORES';});const decision=evaluate(f,{goal,resolution});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(has(decision,'UNIVERSE_UNSUPPORTED'));});

for(const [name,mutation,reason] of [
  ['STORE entity cannot use BRAND-only capability',d=>d.supported_bindings.entity_types=['STORE'],'ENTITY_TYPE_UNSUPPORTED'],
  ['unsupported measure is rejected',d=>d.supported_bindings.measures=['OTHER_MEASURE'],'MEASURE_UNSUPPORTED'],
  ['CURRENT-only period capability rejects CLOSED',d=>d.supported_bindings.period_statuses=['CURRENT'],'PERIOD_UNSUPPORTED'],
  ['STORE grain cannot use BRAND goal',d=>d.supported_bindings.grains=['STORE'],'GRAIN_UNSUPPORTED'],
  ['YOY-only comparison capability rejects NONE',d=>{d.supported_bindings.comparisons=['YOY'];d.comparability_requirements.supported_modes=['YOY'];},'COMPARISON_UNSUPPORTED'],
]) test(name,async()=>{const f=await base(),decision=evaluate(f,{capability:reCapability(f.capability,mutation)});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(has(decision,reason));});

test('requested period mismatch is semantic substitution and NOT_APPLICABLE',async()=>{const f=await base(),resolution=reResolution(f.resolution,d=>{d.temporal.date_from='2026-07-01';d.temporal.date_to='2026-07-31';});const decision=evaluate(f,{resolution});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(has(decision,'SEMANTIC_SUBSTITUTION_REQUIRED'));});
test('uncertified identity authority is NOT_APPLICABLE',async()=>{const f=await base(),resolution=reResolution(f.resolution,d=>d.coverage.identity='UNCERTIFIED'),decision=evaluate(f,{resolution});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(has(decision,'IDENTITY_AUTHORITY_MISSING'));});
test('uncertified membership/organization authority is NOT_APPLICABLE',async()=>{const f=await base(),resolution=reResolution(f.resolution,d=>d.coverage.membership='UNCERTIFIED'),decision=evaluate(f,{resolution});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(has(decision,'MEMBERSHIP_UNCERTIFIED'));});
test('uncertified temporal authority is NOT_APPLICABLE',async()=>{const f=await base(),resolution=reResolution(f.resolution,d=>d.coverage.temporal='UNCERTIFIED'),decision=evaluate(f,{resolution});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(has(decision,'TEMPORAL_AUTHORITY_MISSING'));});
test('missing SALES availability is NOT_APPLICABLE and never rewrites period',async()=>{const f=await base(),availability=reAvailability(f.availability,d=>{d.sources=d.sources.map(s=>{if(s.source_domain!=='SALES')return s;const x={...s,data_status:'UNAVAILABLE',coverage:{status:'NONE',ratio:0},limitations:['SOURCE_UNAVAILABLE']};delete x.available_from;delete x.available_to;delete x.snapshot_date;return x;});}),decision=evaluate(f,{availability});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(has(decision,'SOURCE_UNAVAILABLE'));assert.equal(f.goal.bindings.period.date_from,'2026-08-01');});
test('PRELIMINARY cannot satisfy AVAILABLE/CONSOLIDATED requirement',async()=>{const f=await base(),availability=reAvailability(f.availability,d=>{d.sources=d.sources.map(s=>s.source_domain==='SALES'?{...s,data_status:'PRELIMINARY',snapshot_date:'2026-09-01'}:s);}),decision=evaluate(f,{availability});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(has(decision,'DATA_STATUS_UNSUPPORTED'));});
test('explicit unsupported constraint is NOT_APPLICABLE',async()=>{const f=await base(),goal=reGoal(f.goal,d=>d.explicit_constraints=[{target_axis:'COMMERCIAL_UNIVERSE',operator:'ALLOW_ONLY',value:'COMPANY',source_text:'CIDEF completo'}]),decision=evaluate(f,{goal});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(has(decision,'CONSTRAINT_UNSUPPORTED'));});
test('LIMITED is emitted only by explicit contract policy above minimum threshold',async()=>{const f=await base(),capability=reCapability(f.capability,d=>{d.availability_requirements.required_coverage='PARTIAL';d.availability_requirements.minimum_coverage_ratio=.9;d.availability_requirements.through_period_end=false;d.availability_requirements.limited_coverage_permitted=true;d.coverage_requirements.full_closed_period_required=false;}),availability=reAvailability(f.availability,d=>{d.sources=d.sources.map(s=>s.source_domain==='SALES'?{...s,available_to:'2026-08-30',coverage:{status:'PARTIAL',ratio:.95}}:s);}),decision=evaluate(f,{capability,availability});assert.equal(decision.status,'APPLICABLE_WITH_LIMITED_COVERAGE');});
test('closed full-period native capability never weakens partial August to LIMITED',async()=>{const f=await base(),availability=reAvailability(f.availability,d=>{d.sources=d.sources.map(s=>s.source_domain==='SALES'?{...s,available_to:'2026-08-20',coverage:{status:'PARTIAL',ratio:.65}}:s);}),decision=evaluate(f,{availability});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(has(decision,'COVERAGE_INSUFFICIENT'));});
test('applicability evaluator is pure and does not mutate inputs',async()=>{const f=await base(),before=clone({goal:f.goal,resolution:f.resolution,availability:f.availability,capability:f.capability});evaluate(f);assert.deepEqual({goal:f.goal,resolution:f.resolution,availability:f.availability,capability:f.capability},before);});
