import test from 'node:test';
import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { ENGINE_VERSION, run as longitudinalVentasMotor } from '../../lib/motors/ventas-longitudinal-context-v01.js';
import { buildFocusedRuntimeFixture } from '../../lib/protocol/runtime/fixtures.js';
import { LONGITUDINAL_VENTAS_NATIVE_CAPABILITY, createAuthorizeExecutionCommand, createNativeCapabilityContract, getCapabilityContract, listCapabilityContracts, validateNativeCapabilityContract } from '../../lib/protocol/planning/index.js';
import { selectedFocused } from './planning-helpers.js';

test('native LONGITUDINAL/VENTAS contract separates semantic support and physical metadata',()=>{const c=LONGITUDINAL_VENTAS_NATIVE_CAPABILITY;assert.equal(validateNativeCapabilityContract(c),true);assert.deepEqual(c.satisfies,{goal_types:['OBSERVED_RESULT'],claim_types:['OBSERVED_VALUE']});assert.deepEqual(c.supported_bindings,{entity_types:['BRAND'],measures:['VIN_SALES'],commercial_universes:['COMPANY'],organization_scopes:['CIDEF'],period_units:['MONTH'],period_statuses:['CLOSED'],period_alignments:['CALENDAR'],grains:['BRAND'],comparisons:['NONE']});assert.deepEqual(c.physical,{executor_ref:'motor_registry.getMotor',motor_ref:'ventas_longitudinal_context_v01',input_contract_ref:'parseVentasLongitudinalInput.v0.3'});});
test('production target catalog contains only audited native capabilities and is deterministic',()=>{assert.deepEqual(listCapabilityContracts().map(x=>x.capability_id),['LONGITUDINAL/VENTAS','LONGITUDINAL/VENTAS_TRAJECTORY','LONGITUDINAL/VENTAS_CHANGE','SALES/PRODUCT_CHANGE_CONTRIBUTION','SALES/STORE_CHANGE_CONTRIBUTION','SALES/SELLER_CHANGE_CONTRIBUTION','SALES/ORGANIZATIONAL_RELATIVE_PERFORMANCE','SALES/DETERIORATION_STATUS','SALES/CURRENT_MONTH_CLOSE_FORECAST','MARKET/SHARE_POSITION','MARKET/SHARE_TRAJECTORY','PRICING/HISTORY_OBSERVED']);assert.equal(getCapabilityContract('LONGITUDINAL/VENTAS'),LONGITUDINAL_VENTAS_NATIVE_CAPABILITY);assert.throws(()=>listCapabilityContracts().push({}),TypeError);});
test('native physical motor_ref and version match the real motor module without execution',()=>{assert.equal(typeof longitudinalVentasMotor,'function');assert.equal(ENGINE_VERSION,LONGITUDINAL_VENTAS_NATIVE_CAPABILITY.capability_version);});
test('authorization command is backend planning intent with no user-selected physical fields',async()=>{const {state}=await selectedFocused();const base={contract_version:'authorize_execution_command.v1',command_id:'a',protocol_id:state.protocol_id,expected_state_version:state.state_version,selected_action_ref:{action_id:state.selected_action_ref.action_id,action_fingerprint:state.selected_action_ref.action_fingerprint},pending_objective_fingerprint:state.pending_execution_objective.objective_fingerprint};for(const field of ['capability_id','motor_id','physical_request','executor_ref'])assert.throws(()=>createAuthorizeExecutionCommand({...base,[field]:'forbidden'}),/UNKNOWN_FIELD/,field);});
test('Action and Goal remain physically clean after target planning modules load',async()=>{const {state}=await buildFocusedRuntimeFixture();for(const value of [state.actions[0],state.goals[0]]){const text=JSON.stringify(value);for(const token of ['LONGITUDINAL/VENTAS','capability','motor','physical_request','executor'])assert.equal(text.toLowerCase().includes(token.toLowerCase()),false,token);}});
test('capability semantic mutation changes fingerprint while clone remains stable',()=>{const copy=clone(LONGITUDINAL_VENTAS_NATIVE_CAPABILITY);assert.equal(copy.contract_fingerprint,LONGITUDINAL_VENTAS_NATIVE_CAPABILITY.contract_fingerprint);copy.supported_bindings.grains=['STORE'];delete copy.contract_fingerprint;assert.notEqual(createNativeCapabilityContract(copy).contract_fingerprint,LONGITUDINAL_VENTAS_NATIVE_CAPABILITY.contract_fingerprint);});
