import test from 'node:test';
import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { buildObservedResultFixture } from '../../lib/protocol/fixtures/observedResult.js';
import { createUniverseResolutionRequestFromQuestionContract } from '../../lib/protocol/resolution/contracts.js';
import { createCertifiedMembershipAdapter, createLegacyEntityAuthorityAdapter, createVentasUniverseAuthorityAdapter } from '../../lib/protocol/resolution/authorityAdapters.js';
import { resolveUniverseBoundary } from '../../lib/protocol/resolution/resolveUniverse.js';
import { PRODUCT_AUTHORITY, SALES_AUTHORITY } from '../../lib/protocol/resolution/fixtures.js';

const question=()=>buildObservedResultFixture().question;
const request=()=>createUniverseResolutionRequestFromQuestionContract(question());
const member=(overrides={})=>createCertifiedMembershipAdapter({provider:async(req)=>({status:'RESOLVED',commercial_universe:req.requested_scope.commercial_universe,organization_scope:clone(req.requested_scope.organization_scope),market_universe:clone(req.requested_scope.market_universe),geography:clone(req.requested_scope.geography),authority_descriptors:[SALES_AUTHORITY],effective_from:'2026-01-01',effective_to:'2026-12-31',...overrides})});
const identity=(result)=>createLegacyEntityAuthorityAdapter({authority_descriptor:PRODUCT_AUTHORITY,resolver:async()=>result});
const resolve=(id,membership=member())=>resolveUniverseBoundary(request(),{identity_adapter:identity(id),membership_adapter:membership});

test('R01 unique certified Foton BRAND resolves through authority adapter',async()=>{const value=await resolve({status:'UNIQUE',canonical_id:'brand_foton',display_name:'Foton'});assert.equal(value.subject.resolution_status,'RESOLVED');assert.equal(value.subject.canonical_id,'brand_foton');assert.equal(value.coverage.identity,'CERTIFIED');});
test('R02 unknown subject remains NOT_FOUND without changing expression',async()=>{const value=await resolve({status:'NOT_FOUND',resolved:false});assert.equal(value.subject.resolution_status,'NOT_FOUND');assert.equal(value.subject.expression,'Foton');assert.equal(Object.hasOwn(value.subject,'canonical_id'),false);});
test('R03 multiple certified candidates remain AMBIGUOUS',async()=>{const value=await resolve({status:'AMBIGUOUS',resolved:false,candidates:[{canonical_id:'a',display_name:'Foton A'},{canonical_id:'b',display_name:'Foton B'}]});assert.equal(value.subject.resolution_status,'AMBIGUOUS');assert.equal(value.subject.candidates.length,2);});
test('R04 COMPANY requested and certified is preserved exactly',async()=>{const value=await resolve({status:'UNIQUE',canonical_id:'brand_foton',display_name:'Foton'});assert.equal(value.membership.membership_status,'RESOLVED');assert.equal(value.membership.commercial_universe,'COMPANY');});
test('R05 COMPANY cannot resolve from OWN_STORES provider candidate',async()=>{const value=await resolve({status:'UNIQUE',canonical_id:'brand_foton',display_name:'Foton'},member({commercial_universe:'OWN_STORES'}));assert.equal(value.membership.membership_status,'NOT_AUTHORIZED');assert.equal(value.membership.commercial_universe,'COMPANY');assert.ok(value.limitations.includes('REQUESTED_MEMBERSHIP_MISMATCH'));});
test('R06 OWN_STORES request is preserved exactly',async()=>{const q=clone(question());delete q.question_contract_hash;q.question_id='own';q.scope.commercial_universe='OWN_STORES';const {createQuestionContract}=await import('../../lib/protocol/contracts.js');const req=createUniverseResolutionRequestFromQuestionContract(createQuestionContract(q));const value=await resolveUniverseBoundary(req,{identity_adapter:identity({status:'UNIQUE',canonical_id:'brand_foton',display_name:'Foton'}),membership_adapter:member()});assert.equal(value.membership.commercial_universe,'OWN_STORES');assert.equal(value.membership.membership_status,'RESOLVED');});
test('R06b OWN_STORES cannot resolve from COMPANY provider candidate',async()=>{const q=clone(question());delete q.question_contract_hash;q.question_id='own_mismatch';q.scope.commercial_universe='OWN_STORES';const {createQuestionContract}=await import('../../lib/protocol/contracts.js');const req=createUniverseResolutionRequestFromQuestionContract(createQuestionContract(q));const value=await resolveUniverseBoundary(req,{identity_adapter:identity({status:'UNIQUE',canonical_id:'brand_foton',display_name:'Foton'}),membership_adapter:createCertifiedMembershipAdapter({provider:async(r)=>({status:'RESOLVED',commercial_universe:'COMPANY',organization_scope:r.requested_scope.organization_scope,market_universe:r.requested_scope.market_universe,geography:r.requested_scope.geography,authority_descriptors:[SALES_AUTHORITY]})})});assert.equal(value.membership.membership_status,'NOT_AUTHORIZED');assert.equal(value.membership.commercial_universe,'OWN_STORES');});
test('R07 authority resolution cannot mutate QuestionContract',async()=>{const q=question(),hash=q.question_contract_hash;await resolve({status:'UNIQUE',canonical_id:'brand_foton',display_name:'Foton'});assert.equal(q.question_contract_hash,hash);assert.equal(Object.hasOwn(q.subject,'canonical_id'),false);});
test('R09 membership without authority is not resolved',async()=>{const value=await resolve({status:'UNIQUE',canonical_id:'brand_foton',display_name:'Foton'},createCertifiedMembershipAdapter({provider:async(req)=>({status:'RESOLVED',commercial_universe:'COMPANY',organization_scope:req.requested_scope.organization_scope,market_universe:req.requested_scope.market_universe,geography:req.requested_scope.geography,authority_descriptors:[]})}));assert.equal(value.membership.membership_status,'NOT_AUTHORIZED');});
test('R10 requested period is preserved while effective authority period is separate',async()=>{const value=await resolve({status:'UNIQUE',canonical_id:'brand_foton',display_name:'Foton'});assert.deepEqual([value.temporal.date_from,value.temporal.date_to],['2026-08-01','2026-08-31']);assert.deepEqual([value.temporal.effective_from,value.temporal.effective_to],['2026-01-01','2026-12-31']);});
test('ventas authority adapter refuses uncertified organization scope',async()=>{const adapter=createVentasUniverseAuthorityAdapter({build_universe:async()=>{throw new Error('must not execute');},authority_descriptors:[SALES_AUTHORITY]});const value=await adapter(request());assert.equal(value.status,'NOT_AUTHORIZED');assert.ok(value.limitations.includes('ORGANIZATION_SCOPE_AUTHORITY_NOT_CERTIFIED'));});
test('ventas authority adapter requires exact certified commercial universe',async()=>{const adapter=createVentasUniverseAuthorityAdapter({build_universe:async()=>({universe:'ventas_universe_v01',commercial_universe:'OWN_STORES',commercial_scope:{universe:'OWN_STORES'},validation:{valid:true}}),authority_descriptors:[SALES_AUTHORITY],certified_organization_scope:'CIDEF',certified_geography:'CHILE'});const value=await adapter(request());assert.equal(value.status,'NOT_AUTHORIZED');assert.equal(value.commercial_universe,'COMPANY');});
test('material authority mutation changes resolution fingerprint',async()=>{const req=request(),provider=member(),base=await resolveUniverseBoundary(req,{identity_adapter:identity({status:'UNIQUE',canonical_id:'brand_foton',display_name:'Foton'}),membership_adapter:provider}),changedIdentity=createLegacyEntityAuthorityAdapter({authority_descriptor:{...PRODUCT_AUTHORITY,snapshot_ref:'product-master-fixture-new'},resolver:async()=>({status:'UNIQUE',canonical_id:'brand_foton',display_name:'Foton'})}),changed=await resolveUniverseBoundary(req,{identity_adapter:changedIdentity,membership_adapter:provider});assert.notEqual(base.resolution_fingerprint,changed.resolution_fingerprint);});
