import test from 'node:test';
import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { createAvailabilitySnapshot } from '../../lib/protocol/contracts.js';
import { buildObservedResultFixture } from '../../lib/protocol/fixtures/observedResult.js';
import { coverageForPeriod, createAvailabilitySnapshotFromQuestionContract, crmAvailabilityObservation, rvmAvailabilityObservation, salesAvailabilityObservation } from '../../lib/protocol/resolution/availability.js';
import { buildWp04Fixture, CRM_AUTHORITY, RVM_AUTHORITY, SALES_AUTHORITY, WP04_OBSERVED_AT } from '../../lib/protocol/resolution/fixtures.js';
import { createAuthorityRef } from '../../lib/protocol/contracts.js';

const requested={date_from:'2026-08-01',date_to:'2026-08-31'};
const auth=(descriptor,from='2026-01-01',to='2026-09-14')=>createAuthorityRef({...descriptor,effective_period:{date_from:from,date_to:to}});
const snapshot=(sources,id='snapshot',observed_at=WP04_OBSERVED_AT)=>createAvailabilitySnapshotFromQuestionContract(buildObservedResultFixture().question,{snapshot_id:id,observed_at,source_observations:sources});

test('A01 requested period fully covered',()=>{assert.deepEqual(coverageForPeriod(requested,{available_from:'2026-01-01',available_to:'2026-08-31'}),{status:'FULL',ratio:1});});
test('A02 requested period partially covered',()=>{const value=coverageForPeriod(requested,{available_from:'2026-08-15',available_to:'2026-09-30'});assert.equal(value.status,'PARTIAL');assert.ok(value.ratio>0&&value.ratio<1);});
test('A03 absent requested period has NONE coverage',()=>{assert.deepEqual(coverageForPeriod(requested,{available_from:'2026-07-01',available_to:'2026-07-31'}),{status:'NONE',ratio:0});});
test('A04 RVM PRELIMINARY remains PRELIMINARY',()=>{const value=snapshot([rvmAvailabilityObservation({authority_ref:auth(RVM_AUTHORITY,'2026-09-01','2026-09-14'),data_status:'PRELIMINARY',snapshot_date:'2026-09-14',available_from:'2026-09-01',available_to:'2026-09-14'})]);assert.equal(value.sources[0].data_status,'PRELIMINARY');assert.equal(value.sources[0].coverage.status,'NONE');});
test('A05 RVM CONSOLIDATED remains CONSOLIDATED',()=>{const value=snapshot([rvmAvailabilityObservation({authority_ref:auth(RVM_AUTHORITY,'2026-01-01','2026-08-31'),data_status:'CONSOLIDATED',available_from:'2026-01-01',available_to:'2026-08-31'})]);assert.equal(value.sources[0].data_status,'CONSOLIDATED');assert.equal(value.sources[0].coverage.status,'FULL');});
test('A06 PRELIMINARY cannot be promoted to CONSOLIDATED assertion',()=>{const value=snapshot([rvmAvailabilityObservation({authority_ref:auth(RVM_AUTHORITY),data_status:'PRELIMINARY',snapshot_date:'2026-09-14',available_from:'2026-08-01',available_to:'2026-08-31'})]),draft=clone(value);delete draft.snapshot_fingerprint;draft.sources[0].data_status='CONSOLIDATED';assert.throws(()=>createAvailabilitySnapshot(draft),/CONSOLIDATED_SNAPSHOT_FORBIDDEN/);});
test('A07 current CRM does not advertise historical snapshot coverage',()=>{const value=snapshot([crmAvailabilityObservation({authority_ref:auth(CRM_AUTHORITY,'2026-09-14','2026-09-14'),available_from:'2026-09-14',available_to:'2026-09-14'})]);assert.equal(value.sources[0].data_status,'CURRENT');assert.equal(value.sources[0].coverage.status,'NONE');assert.ok(value.sources[0].limitations.includes('HISTORICAL_CRM_SNAPSHOT_UNAVAILABLE'));});
test('A08 availability facts contain no applicability or capability selection',async()=>{const {availability}=await buildWp04Fixture(),text=JSON.stringify(availability);for(const token of ['capability','applicability','goal_instance','decision_plan'])assert.equal(text.includes(token),false,token);});
test('A09 refresh produces a new immutable snapshot and fingerprint',()=>{const source=salesAvailabilityObservation({authority_ref:auth(SALES_AUTHORITY),available_from:'2026-01-01',available_to:'2026-09-14'}),a=snapshot([source],'a','2026-09-14T12:00:00.000Z'),b=snapshot([source],'b','2026-09-15T12:00:00.000Z');assert.notEqual(a.snapshot_fingerprint,b.snapshot_fingerprint);assert.equal(Object.isFrozen(a),true);});
test('A10 same canonical snapshot content ignores opaque snapshot id',()=>{const source=salesAvailabilityObservation({authority_ref:auth(SALES_AUTHORITY),available_from:'2026-01-01',available_to:'2026-09-14'}),a=snapshot([source],'a'),b=snapshot([source],'b');assert.equal(a.snapshot_fingerprint,b.snapshot_fingerprint);});
test('coverage mutation and data status mutation change snapshot fingerprint',()=>{const consolidated=rvmAvailabilityObservation({authority_ref:auth(RVM_AUTHORITY),data_status:'CONSOLIDATED',available_from:'2026-01-01',available_to:'2026-08-31'}),partial=rvmAvailabilityObservation({authority_ref:auth(RVM_AUTHORITY),data_status:'CONSOLIDATED',available_from:'2026-08-15',available_to:'2026-08-31'});assert.notEqual(snapshot([consolidated],'a').snapshot_fingerprint,snapshot([partial],'b').snapshot_fingerprint);const preliminary=rvmAvailabilityObservation({authority_ref:auth(RVM_AUTHORITY),data_status:'PRELIMINARY',snapshot_date:'2026-08-31',available_from:'2026-01-01',available_to:'2026-08-31'});assert.notEqual(snapshot([consolidated],'a').snapshot_fingerprint,snapshot([preliminary],'b').snapshot_fingerprint);});
