import test from 'node:test';
import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { createAuthorityRef, createAvailabilitySnapshot, createUniverseResolution, validateAvailabilitySnapshot, validateUniverseResolution } from '../../lib/protocol/contracts.js';
import { buildObservedResultFixture } from '../../lib/protocol/fixtures/observedResult.js';
import { createUniverseResolutionRequest, createUniverseResolutionRequestFromQuestionContract, validateUniverseResolutionRequest } from '../../lib/protocol/resolution/contracts.js';
import { buildWp04Fixture, PRODUCT_AUTHORITY } from '../../lib/protocol/resolution/fixtures.js';

test('finalized QuestionContract produces a closed UniverseResolutionRequest',()=>{const question=buildObservedResultFixture().question,request=createUniverseResolutionRequestFromQuestionContract(question);assert.equal(validateUniverseResolutionRequest(request),true);assert.equal(request.question_contract_ref,question.question_contract_hash);assert.equal(request.subject.expression,'Foton');assert.equal(request.requested_scope.commercial_universe,'COMPANY');assert.deepEqual([request.requested_period.date_from,request.requested_period.date_to],['2026-08-01','2026-08-31']);});
test('resolution request forbids canonical and physical identity',()=>{const request=clone(createUniverseResolutionRequestFromQuestionContract(buildObservedResultFixture().question));delete request.request_fingerprint;for(const field of ['canonical_id','capability_id']){const changed=clone(request);changed.subject[field]='forbidden';assert.throws(()=>createUniverseResolutionRequest(changed),/UNKNOWN_FIELD|FORBIDDEN_FIELD/);}});
test('resolution request semantic fingerprint ignores opaque request id',()=>{const question=buildObservedResultFixture().question,a=createUniverseResolutionRequestFromQuestionContract(question,{request_id:'a'}),b=createUniverseResolutionRequestFromQuestionContract(question,{request_id:'b'});assert.equal(a.semantic_fingerprint,b.semantic_fingerprint);assert.equal(a.request_fingerprint,b.request_fingerprint);});
test('WP04 detailed UniverseResolution validates and is immutable',async()=>{const {resolution}=await buildWp04Fixture();assert.equal(validateUniverseResolution(resolution),true);assert.equal(Object.isFrozen(resolution),true);assert.equal(resolution.subject.canonical_id,'brand_fixture_foton');assert.equal(resolution.membership.commercial_universe,'COMPANY');});
test('resolved identity requires typed authority',async()=>{const {resolution}=await buildWp04Fixture(),draft=clone(resolution);delete draft.resolution_fingerprint;delete draft.subject.authority_ref.authority_fingerprint;assert.throws(()=>createUniverseResolution(draft),/INVALID_STRING|FINGERPRINT/);});
test('resolved membership requires certified authority refs',async()=>{const {resolution}=await buildWp04Fixture(),draft=clone(resolution);delete draft.resolution_fingerprint;draft.membership.membership_authority_refs=[];draft.authority.membership_refs=[];assert.throws(()=>createUniverseResolution(draft),/MEMBERSHIP_AUTHORITY_REQUIRED/);});
test('typed AuthorityRef is deterministic and immutable',()=>{const draft={...PRODUCT_AUTHORITY,effective_period:{date_from:'2026-08-01',date_to:'2026-08-31'}},a=createAuthorityRef(draft),b=createAuthorityRef(draft);assert.equal(a.authority_fingerprint,b.authority_fingerprint);assert.equal(Object.isFrozen(a),true);});
test('WP01 compact UniverseResolution remains backward compatible',()=>{assert.doesNotThrow(()=>validateUniverseResolution(buildObservedResultFixture().resolution));});
test('WP04 detailed AvailabilitySnapshot validates and is immutable',async()=>{const {availability}=await buildWp04Fixture();assert.equal(validateAvailabilitySnapshot(availability),true);assert.equal(Object.isFrozen(availability),true);assert.match(availability.snapshot_fingerprint,/^sha256:/);});
test('WP01 compact AvailabilitySnapshot remains backward compatible',()=>{assert.doesNotThrow(()=>validateAvailabilitySnapshot(buildObservedResultFixture().availability));});
test('availability snapshot rejects capability selection fields',async()=>{const {availability}=await buildWp04Fixture(),draft=clone(availability);delete draft.snapshot_fingerprint;draft.capability_id='LONGITUDINAL/VENTAS';assert.throws(()=>createAvailabilitySnapshot(draft),/UNKNOWN_FIELD|FORBIDDEN_FIELD/);});
