import test from 'node:test';
import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { buildWp04Fixture, SALES_AUTHORITY, WP04_OBSERVED_AT } from '../../lib/protocol/resolution/fixtures.js';
import { createAvailabilitySnapshotFromQuestionContract, salesAvailabilityObservation } from '../../lib/protocol/resolution/availability.js';
import { createAuthorityRef } from '../../lib/protocol/contracts.js';
import { createCertifiedMembershipAdapter, createLegacyEntityAuthorityAdapter } from '../../lib/protocol/resolution/authorityAdapters.js';
import { createUniverseResolutionRequestFromQuestionContract } from '../../lib/protocol/resolution/contracts.js';
import { resolveUniverseBoundary } from '../../lib/protocol/resolution/resolveUniverse.js';
import { PRODUCT_AUTHORITY } from '../../lib/protocol/resolution/fixtures.js';

async function unresolved(status,candidates=[]){const {question}=await buildWp04Fixture(),request=createUniverseResolutionRequestFromQuestionContract(question);const identity=createLegacyEntityAuthorityAdapter({authority_descriptor:PRODUCT_AUTHORITY,resolver:async()=>({status,candidates})});const membership=createCertifiedMembershipAdapter({provider:async(req)=>({status:'RESOLVED',commercial_universe:req.requested_scope.commercial_universe,organization_scope:req.requested_scope.organization_scope,market_universe:req.requested_scope.market_universe,geography:req.requested_scope.geography,authority_descriptors:[SALES_AUTHORITY]})});return {question,resolution:await resolveUniverseBoundary(request,{identity_adapter:identity,membership_adapter:membership})};}

test('I01 QuestionContract hash is unchanged by UniverseResolution',async()=>{const {question,resolution}=await buildWp04Fixture();assert.equal(question.question_contract_hash,resolution.question_contract_ref);assert.equal(Object.hasOwn(question.subject,'canonical_id'),false);});
test('I02 UniverseResolution cannot add semantic constraints',async()=>{const {resolution}=await buildWp04Fixture();assert.equal(Object.hasOwn(resolution,'explicit_constraints'),false);});
test('I03 UniverseResolution preserves requested period exactly',async()=>{const {request,resolution}=await buildWp04Fixture();assert.deepEqual([resolution.temporal.date_from,resolution.temporal.date_to],[request.requested_period.date_from,request.requested_period.date_to]);});
test('I04 UniverseResolution preserves commercial universe exactly',async()=>{const {request,resolution}=await buildWp04Fixture();assert.equal(resolution.membership.commercial_universe,request.requested_scope.commercial_universe);});
test('I05 AvailabilitySnapshot cannot change QuestionContract',async()=>{const {question}=await buildWp04Fixture(),hash=question.question_contract_hash;createAvailabilitySnapshotFromQuestionContract(question,{observed_at:WP04_OBSERVED_AT,source_observations:[]});assert.equal(question.question_contract_hash,hash);});
test('I06 AvailabilitySnapshot cannot change UniverseResolution',async()=>{const {question,resolution}=await buildWp04Fixture(),fingerprint=resolution.resolution_fingerprint;createAvailabilitySnapshotFromQuestionContract(question,{observed_at:WP04_OBSERVED_AT,source_observations:[]});assert.equal(resolution.resolution_fingerprint,fingerprint);});
test('I07 availability cannot select capability',async()=>{const {availability}=await buildWp04Fixture();for(const source of availability.sources){assert.equal(Object.hasOwn(source,'capability_id'),false);assert.equal(Object.hasOwn(source,'applicable'),false);}});
test('I08 authority ambiguity does not reopen semantic grounding',async()=>{const {question,resolution}=await unresolved('AMBIGUOUS',[{canonical_id:'a',display_name:'Foton A'},{canonical_id:'b',display_name:'Foton B'}]);assert.equal(resolution.subject.resolution_status,'AMBIGUOUS');assert.equal(question.semantic_intent.operation,'OBSERVE');assert.equal(Object.hasOwn(question,'grounding_issues'),false);});
test('I09 NOT_FOUND cannot mutate semantic subject expression',async()=>{const {question,resolution}=await unresolved('NOT_FOUND');assert.equal(resolution.subject.resolution_status,'NOT_FOUND');assert.equal(question.subject.expression,'Foton');assert.equal(Object.hasOwn(question.subject,'canonical_id'),false);});
test('I10 data unavailability does not rewrite question semantics',async()=>{const {question}=await buildWp04Fixture(),before=clone(question);const authority=createAuthorityRef({...SALES_AUTHORITY,effective_period:{date_from:'2026-07-01',date_to:'2026-07-31'}});const availability=createAvailabilitySnapshotFromQuestionContract(question,{observed_at:WP04_OBSERVED_AT,source_observations:[salesAvailabilityObservation({authority_ref:authority,available_from:'2026-07-01',available_to:'2026-07-31'})]});assert.equal(availability.sources[0].coverage.status,'NONE');assert.deepEqual(question,before);});
test('WP04 boundary activates no goals, actions or execution',async()=>{const fixture=await buildWp04Fixture(),text=JSON.stringify(fixture);for(const token of ['goal_instance','action_id','execution_authorization','applicability_decision'])assert.equal(text.includes(token),false,token);});
