import test from 'node:test';
import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { createAction, createGoalInstance } from '../../lib/protocol/contracts.js';
import { buildBroadRuntimeFixture, buildFocusedRuntimeFixture, WP05_CLOCK } from '../../lib/protocol/runtime/fixtures.js';
import { createProtocolState, createSelectActionCommand, selectAction } from '../../lib/protocol/runtime/index.js';

function cmd(state,patch={}){const action=state.actions[0];return createSelectActionCommand({contract_version:'select_action_command.v1',command_id:'command_invariant',protocol_id:state.protocol_id,expected_state_version:state.state_version,action_id:action.action_id,action_fingerprint:action.action_fingerprint,...patch});}

test('same initialization inputs and frozen clock produce identical state hash',async()=>{assert.equal((await buildFocusedRuntimeFixture()).state.state_hash,(await buildFocusedRuntimeFixture()).state.state_hash);});
test('state and action semantic mutations change fingerprints',async()=>{const {state}=await buildFocusedRuntimeFixture(),actionDraft=clone(state.actions[0]);delete actionDraft.action_fingerprint;actionDraft.description='Materially different semantic description.';assert.notEqual(createAction(actionDraft).action_fingerprint,state.actions[0].action_fingerprint);const stateDraft=clone(state);delete stateDraft.state_hash;const goalDraft=clone(stateDraft.goals[0]);delete goalDraft.goal_fingerprint;goalDraft.bindings.measure='OTHER_MEASURE';stateDraft.goals=[createGoalInstance(goalDraft)];stateDraft.open_obligations=[stateDraft.goals[0].goal_id];assert.notEqual(createProtocolState(stateDraft).state_hash,state.state_hash);});
test('opaque Goal, Action and Candidate IDs do not alter semantic fingerprints',async()=>{const focused=(await buildFocusedRuntimeFixture()).state,broad=(await buildBroadRuntimeFixture()).state;const goal=clone(focused.goals[0]);delete goal.goal_fingerprint;goal.goal_id='opaque_other';assert.equal(createGoalInstance(goal).goal_fingerprint,focused.goals[0].goal_fingerprint);const action=clone(focused.actions[0]);delete action.action_fingerprint;action.action_id='opaque_other';action.goal_id='opaque_other';action.protocol_id='opaque_other';assert.equal(createAction(action).action_fingerprint,focused.actions[0].action_fingerprint);const {createInitialGoalCandidate}=await import('../../lib/protocol/runtime/contracts.js'),candidate=clone(broad.initial_goal_candidates[0]);delete candidate.candidate_fingerprint;candidate.candidate_id='opaque_other';assert.equal(createInitialGoalCandidate(candidate).candidate_fingerprint,broad.initial_goal_candidates[0].candidate_fingerprint);});
test('stale state version and stale Action can never mutate current state',async()=>{const {state}=await buildFocusedRuntimeFixture(),before=clone(state);assert.throws(()=>selectAction(state,cmd(state,{expected_state_version:99}),{clock:WP05_CLOCK}),/STALE_STATE_VERSION/);assert.deepEqual(state,before);const next=selectAction(state,cmd(state),{clock:WP05_CLOCK});assert.throws(()=>selectAction(next,cmd(state,{expected_state_version:next.state_version}),{clock:WP05_CLOCK}),/UNKNOWN_ACTION|ACTION_ALREADY_CONSUMED/);});
test('unknown Action and wrong fingerprint are rejected deterministically',async()=>{const {state}=await buildFocusedRuntimeFixture();assert.throws(()=>selectAction(state,cmd(state,{action_id:'unknown'}),{clock:WP05_CLOCK}),/UNKNOWN_ACTION/);assert.throws(()=>selectAction(state,cmd(state,{action_fingerprint:'sha256:wrong'}),{clock:WP05_CLOCK}),/ACTION_FINGERPRINT_MISMATCH/);});
test('Action issued for a previous state version is rejected',async()=>{const {state}=await buildFocusedRuntimeFixture(),draft=clone(state);delete draft.state_hash;draft.state_version=2;draft.previous_state_hash=state.state_hash;draft.actions=state.actions;draft.updated_at='2026-09-15T12:01:00.000Z';const current=createProtocolState(draft);assert.throws(()=>selectAction(current,cmd(current),{clock:WP05_CLOCK}),/STALE_ACTION_STATE_VERSION/);});
test('selection budget is finite, increments once, and cannot be negative',async()=>{const {state}=await buildFocusedRuntimeFixture(),next=selectAction(state,cmd(state),{clock:WP05_CLOCK});assert.equal(next.budget.semantic_selections_used,state.budget.semantic_selections_used+1);const draft=clone(state);delete draft.state_hash;draft.budget.semantic_selections_used=-1;assert.throws(()=>createProtocolState(draft),/INVALID_INTEGER/);});
test('budget exhaustion prevents selection without terminal fabrication',async()=>{const {state}=await buildFocusedRuntimeFixture(),draft=clone(state);delete draft.state_hash;draft.budget={max_semantic_selections:1,semantic_selections_used:1,max_depth:1};const exhausted=createProtocolState(draft);assert.throws(()=>selectAction(exhausted,cmd(exhausted),{clock:WP05_CLOCK}),/SEMANTIC_BUDGET_EXHAUSTED/);assert.notEqual(exhausted.status,'COMPLETE');});
test('original state is recursively immutable and remains unchanged after transition',async()=>{const {state}=await buildFocusedRuntimeFixture(),snapshot=clone(state);selectAction(state,cmd(state),{clock:WP05_CLOCK});assert.deepEqual(state,snapshot);assert.equal(Object.isFrozen(state.goals[0]),true);});
test('previous_state_hash forms a valid one-step chain and versions are strictly monotonic',async()=>{const {state}=await buildFocusedRuntimeFixture(),next=selectAction(state,cmd(state),{clock:WP05_CLOCK});assert.equal(next.state_version,state.state_version+1);assert.equal(next.previous_state_hash,state.state_hash);});
test('mismatched QuestionContract reference is rejected',async()=>{const f=await buildFocusedRuntimeFixture(),draft=clone(f.resolution);delete draft.resolution_fingerprint;draft.question_contract_ref='sha256:mismatch';const {createUniverseResolution}=await import('../../lib/protocol/contracts.js'),resolution=createUniverseResolution(draft),{initializeProtocol}=await import('../../lib/protocol/runtime/reducer.js');assert.throws(()=>initializeProtocol({questionContract:f.question,universeResolution:resolution,availabilitySnapshot:f.availability,clock:WP05_CLOCK}),/QUESTION_RESOLUTION_MISMATCH/);});
test('focused initialization activates only the explicitly expressed proposition',async()=>{const {state}=await buildFocusedRuntimeFixture();assert.deepEqual(state.goals.map(item=>item.goal_type),['OBSERVED_RESULT']);});
test('canonical identity enters Goal from UniverseResolution and never QuestionContract',async()=>{const {question,resolution,state}=await buildFocusedRuntimeFixture();assert.equal(Object.hasOwn(question.subject,'canonical_id'),false);assert.equal(state.goals[0].bindings.subject.canonical_id,resolution.subject.canonical_id);});
test('Action generation succeeds with no capability registry dependency',async()=>{const {state}=await buildFocusedRuntimeFixture();assert.equal(state.actions.length,1);const source=await import('node:fs/promises').then(fs=>fs.readFile(new URL('../../lib/protocol/runtime/actions.js',import.meta.url),'utf8'));assert.equal(source.includes('capabilityRegistry'),false);});
test('selection command cannot select multiple Actions',async()=>{const {state}=await buildFocusedRuntimeFixture(),action=state.actions[0];assert.throws(()=>createSelectActionCommand({contract_version:'select_action_command.v1',command_id:'multi',protocol_id:state.protocol_id,expected_state_version:1,action_id:[action.action_id],action_fingerprint:action.action_fingerprint}),/INVALID_STRING/);});
