import test from 'node:test';
import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { createAction, createGoalInstance, validateAction, validateGoalInstance } from '../../lib/protocol/contracts.js';
import { GoalOrigin, GoalType, ProtocolStatus } from '../../lib/protocol/enums.js';
import { buildBroadRuntimeFixture, buildFocusedRuntimeFixture } from '../../lib/protocol/runtime/fixtures.js';
import { createInitialGoalCandidate, createProtocolState, createSelectActionCommand, validateInitialGoalCandidate, validateProtocolState, validateSelectActionCommand } from '../../lib/protocol/runtime/contracts.js';

test('ProtocolState uses the definitive closed status enum and validates focused state',async()=>{const {state}=await buildFocusedRuntimeFixture();assert.deepEqual(Object.values(ProtocolStatus),['GROUNDING','AWAITING_SELECTION','EXECUTING','ASSESSING','COMPLETE','TERMINAL_PARTIAL']);assert.equal(validateProtocolState(state),true);assert.equal(Object.isFrozen(state),true);});
test('GoalType and GoalOrigin contain semantic WP05 extensions',()=>{assert.equal(GoalType.TEMPORAL_TRAJECTORY,'TEMPORAL_TRAJECTORY');assert.equal(GoalOrigin.USER_SELECTED,'USER_SELECTED');});
test('InitialGoalCandidate is closed, semantic, fingerprinted and immutable',async()=>{const {state}=await buildBroadRuntimeFixture(),candidate=state.initial_goal_candidates[0];assert.equal(validateInitialGoalCandidate(candidate),true);assert.equal(Object.isFrozen(candidate),true);for(const key of ['capability_id','motor','physical_request'])assert.equal(JSON.stringify(candidate).includes(key),false);});
test('SelectActionCommand is exactly-one action and fingerprinted',async()=>{const {state}=await buildFocusedRuntimeFixture(),action=state.actions[0],command=createSelectActionCommand({contract_version:'select_action_command.v1',command_id:'command_1',protocol_id:state.protocol_id,expected_state_version:state.state_version,action_id:action.action_id,action_fingerprint:action.action_fingerprint});assert.equal(validateSelectActionCommand(command),true);assert.equal(Object.isFrozen(command),true);const bad=clone(command);delete bad.command_fingerprint;bad.action_ids=[action.action_id];assert.throws(()=>createSelectActionCommand(bad),/UNKNOWN_FIELD/);});
test('Action target is exactly one Goal or InitialGoalCandidate',async()=>{const {state}=await buildBroadRuntimeFixture(),draft=clone(state.actions[0]);delete draft.action_fingerprint;draft.goal_id='also-a-goal';assert.throws(()=>createAction(draft),/ACTION_TARGET_XOR/);});
test('Action rejects all physical fields explicitly',async()=>{const {state}=await buildFocusedRuntimeFixture();for(const field of ['capability_id','motor','physical_request','private_request','execution_input','sql','table','executor']){const draft=clone(state.actions[0]);delete draft.action_fingerprint;draft[field]='forbidden';assert.throws(()=>createAction(draft),/UNKNOWN_FIELD|FORBIDDEN_FIELD/,field);}const nested=clone(state.actions[0]);delete nested.action_fingerprint;nested.limitations=[{private_request:{secret:true}}];assert.throws(()=>createAction(nested),/FORBIDDEN_FIELD/);});
test('GoalInstance supports USER_SELECTED without physical identity',async()=>{const {state}=await buildBroadRuntimeFixture(),candidate=state.initial_goal_candidates[1],draft={contract_version:'goal_instance.v1',goal_id:'goal_selected',question_contract_ref:state.question_contract_hash,universe_resolution_ref:state.universe_resolution_fingerprint,goal_type:candidate.goal_type,evidence_class:'REQUIRED',origin:'USER_SELECTED',status:'PENDING',bindings:clone(candidate.bindings)},goal=createGoalInstance(draft);assert.equal(validateGoalInstance(goal),true);assert.equal(JSON.stringify(goal).includes('capability'),false);});
test('ProtocolState cannot contain legacy or physical runtime structures',async()=>{const {state}=await buildFocusedRuntimeFixture();for(const field of ['decision_plan','question_family','execution_authorization','evidence_records']){const draft=clone(state);delete draft.state_hash;draft[field]={};assert.throws(()=>createProtocolState(draft),/UNKNOWN_FIELD|FORBIDDEN_FIELD/,field);}});
