import test from 'node:test';
import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { createAvailabilitySnapshot, createUniverseResolution } from '../../lib/protocol/contracts.js';
import { buildFocusedRuntimeFixture, WP05_CLOCK } from '../../lib/protocol/runtime/fixtures.js';
import { createSelectActionCommand, initializeProtocol, selectAction } from '../../lib/protocol/runtime/index.js';

function command(state,overrides={}){const action=state.actions[0];return createSelectActionCommand({contract_version:'select_action_command.v1',command_id:'select_focused',protocol_id:state.protocol_id,expected_state_version:state.state_version,action_id:action.action_id,action_fingerprint:action.action_fingerprint,...overrides});}

test('focused WP05 E2E initializes exactly one OBSERVED_RESULT obligation and semantic Action',async()=>{const {state}=await buildFocusedRuntimeFixture();assert.equal(state.status,'AWAITING_SELECTION');assert.equal(state.goals.length,1);assert.equal(state.open_obligations.length,1);assert.deepEqual({goal_type:state.goals[0].goal_type,evidence_class:state.goals[0].evidence_class,origin:state.goals[0].origin,status:state.goals[0].status},{goal_type:'OBSERVED_RESULT',evidence_class:'REQUIRED',origin:'USER_EXPRESSED',status:'PENDING'});assert.equal(state.actions.length,1);assert.equal(state.actions[0].semantic_label,'OBSERVE_SALES_RESULT');});
test('focused bindings preserve certified subject, COMPANY, CIDEF, August and BRAND exactly',async()=>{const {state}=await buildFocusedRuntimeFixture(),goal=state.goals[0],action=state.actions[0];assert.deepEqual([goal.bindings.subject.canonical_id,goal.bindings.subject.entity_type],['brand_fixture_foton','BRAND']);assert.deepEqual([goal.bindings.commercial_universe,goal.bindings.organization_scope,goal.bindings.period.date_from,goal.bindings.period.date_to,goal.bindings.grain],['COMPANY','CIDEF','2026-08-01','2026-08-31','BRAND']);assert.deepEqual(action.public_bindings,{subject:'Foton',measure:'VIN_SALES',commercial_universe:'COMPANY',organization_scope:'CIDEF',period:goal.bindings.period,grain:'BRAND',comparison:'NONE',explicit_constraints:[]});});
test('focused Action exposes no physical identity and state has no execution/evidence',async()=>{const {state}=await buildFocusedRuntimeFixture(),text=JSON.stringify(state);for(const token of ['LONGITUDINAL/VENTAS','capability_id','motor','execution_authorization','evidence_record'])assert.equal(text.toLowerCase().includes(token.toLowerCase()),false,token);assert.notEqual(state.status,'COMPLETE');});
test('focused semantic selection increments version and chains immutable state',async()=>{const {state}=await buildFocusedRuntimeFixture(),before=clone(state),next=selectAction(state,command(state),{clock:'2026-09-15T12:01:00.000Z'});assert.equal(next.state_version,2);assert.equal(next.previous_state_hash,state.state_hash);assert.deepEqual(state,before);assert.equal(next.selected_action_ref.action_id,state.actions[0].action_id);assert.equal(next.pending_execution_objective.goal_id,state.goals[0].goal_id);});
test('focused semantic selection neither satisfies Goal nor completes or executes',async()=>{const {state}=await buildFocusedRuntimeFixture(),next=selectAction(state,command(state),{clock:WP05_CLOCK}),text=JSON.stringify(next);assert.equal(next.goals[0].status,'PENDING');assert.equal(next.status,'AWAITING_SELECTION');assert.equal(next.terminal.status,'OPEN');for(const key of ['execution_authorization','evidence_record','capability_contract_ref'])assert.equal(text.includes(key),false,key);});
test('unresolved UniverseResolution cannot activate focused Goal',async()=>{const f=await buildFocusedRuntimeFixture(),draft=clone(f.resolution);delete draft.resolution_fingerprint;delete draft.subject.canonical_id;delete draft.subject.canonical_label;draft.subject.resolution_status='NOT_FOUND';const resolution=createUniverseResolution(draft);assert.throws(()=>initializeProtocol({questionContract:f.question,universeResolution:resolution,availabilitySnapshot:f.availability,clock:WP05_CLOCK}),/UNRESOLVED_UNIVERSE_RESOLUTION/);});
test('unavailable period leaves focused Goal period unchanged and only adds certified limitation',async()=>{const f=await buildFocusedRuntimeFixture(),draft=clone(f.availability);delete draft.snapshot_fingerprint;draft.sources=draft.sources.map(item=>{if(item.source_domain!=='SALES')return item;const {available_from,available_to,snapshot_date,...rest}=item;return {...rest,data_status:'UNAVAILABLE',coverage:{status:'NONE',ratio:0},limitations:['SOURCE_UNAVAILABLE']};});const availability=createAvailabilitySnapshot(draft);const state=initializeProtocol({questionContract:f.question,universeResolution:f.resolution,availabilitySnapshot:availability,clock:WP05_CLOCK});assert.deepEqual([state.goals[0].bindings.period.date_from,state.goals[0].bindings.period.date_to],['2026-08-01','2026-08-31']);assert.ok(state.actions[0].limitations.includes('REQUESTED_PERIOD_NOT_FULLY_COVERED'));});
test('commercial universe or period mutation is rejected at initialization',async()=>{const f=await buildFocusedRuntimeFixture();for(const mutation of ['universe','period']){const draft=clone(f.resolution);delete draft.resolution_fingerprint;if(mutation==='universe')draft.membership.commercial_universe='OWN_STORES';else{draft.temporal.date_from='2026-07-01';draft.temporal.date_to='2026-07-31';}const resolution=createUniverseResolution(draft);assert.throws(()=>initializeProtocol({questionContract:f.question,universeResolution:resolution,availabilitySnapshot:f.availability,clock:WP05_CLOCK}),/COMMERCIAL_UNIVERSE_MUTATION|PERIOD_MUTATION/);}});
