import test from 'node:test';
import assert from 'node:assert/strict';
import { buildBroadRuntimeFixture, WP05_CLOCK } from '../../lib/protocol/runtime/fixtures.js';
import { createSelectActionCommand, selectAction } from '../../lib/protocol/runtime/index.js';

function select(state,index=0){const action=state.actions[index];return createSelectActionCommand({contract_version:'select_action_command.v1',command_id:`select_${index}`,protocol_id:state.protocol_id,expected_state_version:state.state_version,action_id:action.action_id,action_fingerprint:action.action_fingerprint});}

test('broad initialization activates zero REQUIRED goals and a bounded deterministic candidate set',async()=>{const a=(await buildBroadRuntimeFixture()).state,b=(await buildBroadRuntimeFixture()).state;assert.equal(a.status,'AWAITING_SELECTION');assert.equal(a.goals.length,0);assert.equal(a.open_obligations.length,0);assert.equal(a.initial_goal_candidates.length,4);assert.deepEqual(a.actions.map(item=>item.goal_type),['OBSERVED_RESULT','TEMPORAL_TRAJECTORY','RELATIVE_PERFORMANCE','MARKET_POSITION']);assert.deepEqual(a.actions.map(item=>item.action_fingerprint),b.actions.map(item=>item.action_fingerprint));});
test('broad candidate Actions represent one semantic direction each and no fixed bundle',async()=>{const {state}=await buildBroadRuntimeFixture();for(const action of state.actions){assert.ok(action.candidate_id);assert.equal(Object.hasOwn(action,'goal_id'),false);assert.equal(action.expected_contribution.length,1);}const text=JSON.stringify(state);for(const token of ['bundle','question_family','capability'])assert.equal(text.includes(token),false,token);});
test('selecting trajectory activates exactly one USER_SELECTED REQUIRED Goal',async()=>{const {state}=await buildBroadRuntimeFixture(),next=selectAction(state,select(state,1),{clock:WP05_CLOCK});assert.equal(next.goals.length,1);assert.deepEqual({type:next.goals[0].goal_type,evidence:next.goals[0].evidence_class,origin:next.goals[0].origin,status:next.goals[0].status},{type:'TEMPORAL_TRAJECTORY',evidence:'REQUIRED',origin:'USER_SELECTED',status:'PENDING'});assert.deepEqual(next.open_obligations,[next.goals[0].goal_id]);});
test('broad sibling candidates never become obligations after one selection',async()=>{const {state}=await buildBroadRuntimeFixture(),chosen=state.actions[2],next=selectAction(state,select(state,2),{clock:WP05_CLOCK});assert.equal(next.goals.length,1);assert.equal(next.goals[0].goal_type,chosen.goal_type);assert.equal(next.initial_goal_candidates.length,0);assert.equal(next.actions.length,0);assert.equal(next.open_obligations.length,1);});
test('broad selection does not choose capability, authorize, execute, satisfy or complete',async()=>{const {state}=await buildBroadRuntimeFixture(),next=selectAction(state,select(state,3),{clock:WP05_CLOCK}),text=JSON.stringify(next).toLowerCase();for(const token of ['capability','execution_authorization','evidence_record','motor'])assert.equal(text.includes(token),false,token);assert.equal(next.goals[0].status,'PENDING');assert.notEqual(next.status,'COMPLETE');});
test('candidate selection is explicit even when a state contains one Action',async()=>{const {state}=await buildBroadRuntimeFixture();assert.equal(state.selected_action_ref.status,'OMITTED');assert.equal(state.budget.semantic_selections_used,0);});
