import test from 'node:test';
import assert from 'node:assert/strict';
import { createAuthorityRef, createAvailabilitySnapshot, createQuestionContract, createUniverseResolution } from '../../lib/protocol/contracts.js';
import { clone } from '../../lib/protocol/primitives.js';
import { buildWp04Fixture } from '../../lib/protocol/resolution/fixtures.js';
import { pricingAvailabilityObservation, rvmAvailabilityObservation } from '../../lib/protocol/resolution/availability.js';
import { createPricingAuthorityAdapter, createRvmUniverseAuthorityAdapter } from '../../lib/protocol/resolution/authorityAdapters.js';
import { createUniverseResolutionRequestFromQuestionContract } from '../../lib/protocol/resolution/contracts.js';
import { buildRvmUniverse } from '../../lib/rvm-universe/buildRvmUniverse.js';
import { initializeProtocol, createSelectActionCommand, selectAction } from '../../lib/protocol/runtime/index.js';
import { assessBroadCandidateViability } from '../../lib/protocol/investigation/runtime.js';
import { authorizeExecution, createAuthorizeExecutionCommand, evaluateNativeApplicability, getCapabilityContract } from '../../lib/protocol/planning/index.js';
import { createExecuteAuthorizationCommand, executeAndAdmitEvidence } from '../../lib/protocol/execution/index.js';
import { projectPricingObservedCondition, projectRvmMarketPosition } from '../../lib/protocol/execution/projector.js';
import { evaluateGoalSufficiencyV2, applySufficiencyEvaluation, evaluateProtocolClosure, applyProtocolClosure, buildSynthesisPacketV2 } from '../../lib/protocol/sufficiency/index.js';
import { TARGET_CAPABILITY_COVERAGE, TARGET_CROSS_SOURCE_READINESS, TARGET_PRICING_AUTHORITY_MATRIX, TARGET_RVM_AUTHORITY_MATRIX } from '../../lib/protocol/certification/coverage.js';

const TIMES={init:'2026-09-15T15:00:00.000Z',viability:'2026-09-15T15:01:00.000Z',select:'2026-09-15T15:02:00.000Z',authorize:'2026-09-15T15:03:00.000Z',execute:'2026-09-15T15:04:00.000Z',evaluate:'2026-09-15T15:05:00.000Z',satisfy:'2026-09-15T15:06:00.000Z',close:'2026-09-15T15:07:00.000Z',packet:'2026-09-15T15:08:00.000Z'};
const withoutHash=(value,key)=>{const draft=clone(value);delete draft[key];return draft;};
const authority=(authority_type,authority_name,snapshot_ref,date_from,date_to)=>createAuthorityRef({authority_type,authority_name,authority_version:'1.0',snapshot_ref,effective_period:{date_from,date_to}});

async function sourceFixture(domain,{rvmSingleMonth=false}={}){
  const base=await buildWp04Fixture(),q=withoutHash(base.question,'question_contract_hash'),r=withoutHash(base.resolution,'resolution_fingerprint');
  if(domain==='RVM'){
    q.question_id='question_rvm_connectivity';q.original_question='¿Cómo va Foton en el mercado?';if(!rvmSingleMonth){q.period.semantic.quantity=3;q.period.materialized.date_from='2026-06-01';}q.scope.commercial_universe='RVM_MARKET';q.scope.market_universe={status:'BOUND',value:'TOTAL_RVM_MARKET',authority_required:true};q.semantic_intent={operation:'ASSESS',breadth:'BROAD',expressed_concepts:['SIGNAL'],explicit_conjunction:false,causality:'NOT_REQUESTED'};q.deferred_choice_axes=['EVIDENCE_PROPOSITION'];q.field_provenance={...q.field_provenance,'semantic_intent.operation':'LINGUISTICALLY_INFERRED','semantic_intent.breadth':'LINGUISTICALLY_INFERRED','semantic_intent.expressed_concepts':'LINGUISTICALLY_INFERRED'};
  }else{
    q.question_id='question_pricing_connectivity';q.original_question='¿Cuál fue la condición comercial publicada de Foton TM3 versión 7176 en agosto de 2026?';q.subject={expression:'Foton TM3 versión 7176',type_constraints:['VERSION'],reference_kind:'DIRECT',authority_resolution_required:true};q.scope.commercial_universe='PUBLISHED_CONDITIONS';q.grain='VERSION';q.semantic_intent={operation:'OBSERVE',breadth:'FOCUSED',expressed_concepts:['COMMERCIAL_CONDITION'],explicit_conjunction:false};
  }
  const question=createQuestionContract(q),from=question.period.materialized.date_from,to=question.period.materialized.date_to;
  r.resolution_id=`resolution_${domain.toLowerCase()}_connectivity`;r.question_contract_ref=question.question_contract_hash;r.subject.expression=question.subject.expression;r.subject.entity_type=domain==='RVM'?'BRAND':'VERSION';r.subject.canonical_id=domain==='RVM'?'71':'7176';r.subject.canonical_label=domain==='RVM'?'Foton':'Foton TM3 7176';r.membership.commercial_universe=question.scope.commercial_universe;r.membership.market_universe=clone(question.scope.market_universe);r.grain={requested:question.grain,resolved:question.grain};r.temporal.date_from=from;r.temporal.date_to=to;r.temporal.effective_from=from;r.temporal.effective_to=to;
  const identity=authority('PRODUCT_MASTER','canonical_product_identity',`${domain.toLowerCase()}-product-2026-09-15`,from,to),membership=authority(domain==='RVM'?'RVM_UNIVERSE':'PRICING_AUTHORITY',domain==='RVM'?'rvm_universe_v01':'price_episode_canonico_v01',`${domain.toLowerCase()}-source-2026-09-15`,from,to),temporal=authority('TEMPORAL_POLICY','calendar_month.closed.v1','2026-09-15',from,to);
  r.subject.authority_ref=identity;r.membership.membership_authority_refs=[membership];r.authority={identity_ref:identity,membership_refs:[membership],temporal_ref:temporal};
  const resolution=createUniverseResolution(r),source=domain==='RVM'?rvmAvailabilityObservation({authority_ref:membership,data_status:'CONSOLIDATED',available_from:from,available_to:to,limitations:[]}):pricingAvailabilityObservation({authority_ref:membership,available_from:from,available_to:to,limitations:['PUBLISHED_COMMERCIAL_CONDITION_ONLY']}),availability=createAvailabilitySnapshot({contract_version:'availability_snapshot.v1',snapshot_id:`availability_${domain.toLowerCase()}_connectivity`,observed_at:'2026-09-15T14:59:00.000Z',question_contract_ref:question.question_contract_hash,requested_period:{date_from:from,date_to:to,period_status:question.period.materialized.period_status},sources:[{...source,coverage:{status:'FULL',ratio:1}}]}),state=initializeProtocol({questionContract:question,universeResolution:resolution,availabilitySnapshot:availability,protocol_id:`protocol_${domain.toLowerCase()}_connectivity`,clock:TIMES.init});
  return {question,resolution,availability,state};
}

function selectCommand(state,goalType){const action=state.actions.find(item=>item.goal_type===goalType);return createSelectActionCommand({contract_version:'select_action_command.v1',command_id:`select_${goalType}`,protocol_id:state.protocol_id,expected_state_version:state.state_version,action_id:action.action_id,action_fingerprint:action.action_fingerprint});}
function authorizeCommand(state){return createAuthorizeExecutionCommand({contract_version:'authorize_execution_command.v1',command_id:'authorize_source',protocol_id:state.protocol_id,expected_state_version:state.state_version,selected_action_ref:{action_id:state.selected_action_ref.action_id,action_fingerprint:state.selected_action_ref.action_fingerprint},pending_objective_fingerprint:state.pending_execution_objective.objective_fingerprint});}
function executeCommand(state,authorization){return createExecuteAuthorizationCommand({contract_version:'execute_authorization_command.v1',command_id:'execute_source',protocol_id:state.protocol_id,expected_state_version:state.state_version,authorization_ref:{authorization_id:authorization.authorization_id,authorization_fingerprint:authorization.authorization_fingerprint,execution_fingerprint:authorization.execution_fingerprint}});}
async function complete(f,goalType,raw){const menu=f.question.semantic_intent.breadth==='BROAD'?assessBroadCandidateViability(f.state,{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:TIMES.viability}):f.state,selected=selectAction(menu,selectCommand(menu,goalType),{clock:TIMES.select}),planned=authorizeExecution(selected,authorizeCommand(selected),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:TIMES.authorize}),executed=await executeAndAdmitEvidence(planned.state,planned.authorization,executeCommand(planned.state,planned.authorization),{applicabilityDecisions:planned.applicability_decisions,availabilitySnapshot:f.availability,motorResolver:async()=>async()=>raw,clock:TIMES.execute});assert.equal(executed.admission.status,'ADMITTED',JSON.stringify(executed.admission));const evaluation=evaluateGoalSufficiencyV2({state:executed.state,goal:executed.state.goals[0],ledger:executed.ledger,questionContract:f.question,universeResolution:f.resolution,availabilitySnapshot:f.availability,evaluated_at:TIMES.evaluate});assert.equal(evaluation.status,'SATISFIED');const satisfied=applySufficiencyEvaluation(executed.state,evaluation,{clock:TIMES.satisfy}),closure=evaluateProtocolClosure({state:satisfied,sufficiencyEvaluations:[evaluation]}),terminal=applyProtocolClosure(satisfied,closure,{clock:TIMES.close}),packet=buildSynthesisPacketV2({questionContract:f.question,protocolState:terminal,sufficiencyEvaluations:[evaluation],evidenceRecords:executed.ledger.records,universeResolution:f.resolution,availabilitySnapshot:f.availability,created_at:TIMES.packet});return {menu,selected,planned,executed,evaluation,terminal,packet};}

function rvmRaw(){return {engine:'competitive_share_trajectory_v01',version:'0.2',status:'ok',sharedContext:{context:'rvm_brand_share_trajectory_v01',version:'0.1',scope:{dateFrom:'2026-06-01',dateTo:'2026-08-31',organizationScope:'CIDEF'},entity:{brandId:71,brandName:'Foton',identityStatus:'RESOLVED'},coverage:{monthsRequested:3,monthsReturned:3,monthsEvaluable:3},monthly:[{period:'2026-06',entityVin:10,marketSize:100,marketShare:.1},{period:'2026-07',entityVin:12,marketSize:120,marketShare:.1},{period:'2026-08',entityVin:15,marketSize:125,marketShare:.12}],change:{fromPeriod:'2026-06',toPeriod:'2026-08',shareChangePp:2,shareChangePct:.2},validation:{identityResolved:true,marketShareReconciles:true,monthsRequested:3,monthsReturned:3,monthsEvaluable:3,completeTemporalCoverage:true,ok:true},warnings:[],metadata:{metric:'MARKET_SHARE',denominatorExplicit:true}}};}
function pricingRaw(){return {engine:'pricing_history_v01',version:'0.1',status:'OK',commercial_condition_semantics:'PUBLISHED_COMMERCIAL_CONDITION',scope:{version_id:7176,brand:'Foton',model:'TM3',version:'7176',date_from:'2026-08-01',date_to:'2026-08-31'},coverage:{episodes_total:1,episodes_ok:1,episodes_conflict:0},history:[{price_episode_id:9001,price_version_id:501,version_id:7176,vigencia_desde:'2026-07-15',vigencia_hasta:'2026-09-14',precio_neto:17990000,precio_lista:19990000,precio_con_iva:21408100,bono_cidef:500000,bono_forum:300000,bono_mes:200000,source_status:'OK',source_files:['pricing-2026-07.xlsx']}],provenance:{episode_authority:'price_episode_canonico_v01',product_identity_authority:'MASTER',commercial_condition_semantics:'PUBLISHED_COMMERCIAL_CONDITION',price_realized_available:false}};}

test('RVM and pricing authority adapters preserve exact source semantics',async()=>{const rvm=await sourceFixture('RVM'),rvmRequest=createUniverseResolutionRequestFromQuestionContract(rvm.question),rvmAdapter=createRvmUniverseAuthorityAdapter({authority_descriptors:[rvm.resolution.authority.membership_refs[0]],build_universe:async()=>({universe:'rvm_universe_v01',data_status:'CONSOLIDATED',organization_scope:'CIDEF',period:{effective_date_to:'2026-08-31'},validation:{valid:true}})}),rvmResult=await rvmAdapter(rvmRequest);assert.equal(rvmResult.status,'RESOLVED');assert.equal(rvmResult.market_universe.value,'TOTAL_RVM_MARKET');const pricing=await sourceFixture('PRICING'),pricingAdapter=createPricingAuthorityAdapter({authority_descriptors:[pricing.resolution.authority.membership_refs[0]]}),pricingResult=await pricingAdapter(createUniverseResolutionRequestFromQuestionContract(pricing.question));assert.equal(pricingResult.status,'RESOLVED');assert.ok(pricingResult.limitations.includes('PUBLISHED_COMMERCIAL_CONDITION_ONLY'));});

test('RVM applicability requires consolidated total-market authority and exact physical request',async()=>{const f=await sourceFixture('RVM'),menu=assessBroadCandidateViability(f.state,{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:TIMES.viability});assert.deepEqual(menu.actions.map(item=>item.goal_type),['TEMPORAL_TRAJECTORY']);const selected=selectAction(menu,selectCommand(menu,'TEMPORAL_TRAJECTORY'),{clock:TIMES.select}),planned=authorizeExecution(selected,authorizeCommand(selected),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:TIMES.authorize});assert.equal(planned.physical_selection.capability_id,'MARKET/SHARE_TRAJECTORY');assert.deepEqual(planned.authorization.physical_request.validated_input,{entity:{brand_id:71},date_from:'2026-06-01',date_to:'2026-08-31',time_grain:'MONTH',organization_scope:'CIDEF',cutoff_mode:'FULL_PERIOD'});const preliminary=withoutHash(f.availability,'snapshot_fingerprint');preliminary.sources[0].data_status='PRELIMINARY';preliminary.sources[0].snapshot_date='2026-08-31';const unavailable=createAvailabilitySnapshot(preliminary),decision=evaluateNativeApplicability({goal:selected.goals[0],capabilityContract:getCapabilityContract('MARKET/SHARE_TRAJECTORY'),universeResolution:f.resolution,availabilitySnapshot:unavailable});assert.equal(decision.status,'NOT_APPLICABLE');assert.ok(decision.reason_codes.includes('DATA_STATUS_UNSUPPORTED'));});

test('one-month RVM broad semantics offer MARKET_POSITION with explicit MARKET comparison',async()=>{const f=await sourceFixture('RVM',{rvmSingleMonth:true}),menu=assessBroadCandidateViability(f.state,{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:TIMES.viability});assert.deepEqual(menu.actions.map(item=>item.goal_type),['MARKET_POSITION']);const selected=selectAction(menu,selectCommand(menu,'MARKET_POSITION'),{clock:TIMES.select});assert.equal(selected.goals[0].goal_type,'MARKET_POSITION');assert.equal(selected.goals[0].comparison,'MARKET');const planned=authorizeExecution(selected,authorizeCommand(selected),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:TIMES.authorize});assert.equal(planned.physical_selection.capability_id,'MARKET/SHARE_POSITION');});

test('RVM consolidated snapshot misuse is rejected by the existing source authority',async()=>{await assert.rejects(()=>buildRvmUniverse({date_from:'2026-08-01',date_to:'2026-08-31',organization_scope:'CIDEF',data_status:'CONSOLIDATED',snapshot_date:'2026-08-31'}),/SNAPSHOT_DATE_ONLY_VALID_FOR_PRELIMINARY/);await assert.rejects(()=>buildRvmUniverse({date_from:'2026-08-01',date_to:'2026-08-31',organization_scope:'CIDEF',data_status:'PRELIMINARY'}),/SNAPSHOT_DATE_REQUIRED_FOR_PRELIMINARY/);});

test('RVM trajectory completes through admitted evidence, sufficiency and evidence-bounded synthesis',async()=>{const f=await sourceFixture('RVM'),out=await complete(f,'TEMPORAL_TRAJECTORY',rvmRaw());assert.equal(out.packet.authorized_claims[0].claim_type,'TRAJECTORY_SERIES');assert.deepEqual(out.packet.authorized_claims[0].value.observations.map(row=>row.amount),[.1,.1,.12]);assert.equal(out.packet.authorized_claims[0].value.market_universe,'TOTAL_RVM_MARKET');assert.equal(out.packet.authorized_claims[0].value.data_status,'CONSOLIDATED');assert.equal(JSON.stringify(out.packet).includes('competitive_share_trajectory_v01'),false);});

test('RVM market-position projector requires and preserves explicit denominator reconciliation',async()=>{const f=await sourceFixture('RVM'),goal=clone(f.state.initial_goal_candidates.find(item=>item.goal_type==='MARKET_POSITION'));goal.bindings.period={...goal.bindings.period,date_from:'2026-08-01',quantity:1};const authorization={authorization_id:'rvm_position',authorization_fingerprint:'sha256:authorization',protocol_id:f.state.protocol_id,goal_ref:'sha256:goal',selected_action_ref:{action_id:'action',action_fingerprint:'sha256:action'},capability:{capability_id:'MARKET/SHARE_POSITION',capability_version:'0.2',capability_contract_fingerprint:'sha256:capability'},semantic_binding:{...goal.bindings,comparison:'MARKET',explicit_constraints:[]},authority_refs:f.resolution.authority,availability_snapshot_ref:f.availability.snapshot_fingerprint,physical_request:{motor_ref:'competitive_share_trajectory_v01',evidence_projector_ref:'protocol.evidence.rvm_market_position.v1'},authorized_claim_types:['MARKET_POSITION_VALUE'],execution_fingerprint:'sha256:execution'},attempt={attempt_fingerprint:'sha256:attempt'},raw=rvmRaw();raw.sharedContext.scope.dateFrom='2026-08-01';raw.sharedContext.monthly=[raw.sharedContext.monthly[2]];const record=projectRvmMarketPosition({authorization,executionAttempt:attempt,rawResult:raw,observed_at:TIMES.execute,admitted_at:TIMES.execute});assert.equal(record.claims[0].value.share,.12);raw.sharedContext.monthly[0].marketShare=.2;assert.throws(()=>projectRvmMarketPosition({authorization,executionAttempt:attempt,rawResult:raw,observed_at:TIMES.execute,admitted_at:TIMES.execute}),/MARKET_SHARE_RECONCILIATION_FAILED/);});

test('pricing completes with exact validity and published components, never realized price',async()=>{const f=await sourceFixture('PRICING'),out=await complete(f,'OBSERVED_RESULT',pricingRaw()),claim=out.packet.authorized_claims[0];assert.equal(out.planned.physical_selection.capability_id,'PRICING/HISTORY_OBSERVED');assert.deepEqual(out.planned.authorization.physical_request.validated_input,{version_id:7176,date_from:'2026-08-01',date_to:'2026-08-31',include_conflicts:false});assert.equal(claim.claim_type,'OBSERVED_COMMERCIAL_CONDITION');assert.deepEqual(claim.value.validity,{date_from:'2026-07-15',date_to:'2026-09-14'});assert.equal(claim.value.published_list_price,19990000);assert.equal(claim.value.bonus_cidef,500000);assert.equal(Object.hasOwn(claim.value,'realized_price'),false);assert.ok(out.packet.limitations.some(item=>item.code==='SOURCE_SEMANTICS'&&item.details.forbidden_interpretations.includes('REALIZED_TRANSACTION_PRICE')));assert.equal(JSON.stringify(out.packet).includes('pricing_history_v01'),false);});

test('pricing rejects wrong version, invalid validity, source conflict and unsupported analytical promotion',async()=>{const f=await sourceFixture('PRICING'),selected=selectAction(f.state,selectCommand(f.state,'OBSERVED_RESULT'),{clock:TIMES.select}),planned=authorizeExecution(selected,authorizeCommand(selected),{universeResolution:f.resolution,availabilitySnapshot:f.availability,clock:TIMES.authorize}),authorization=planned.authorization,attempt={attempt_fingerprint:'sha256:attempt'};for(const mutate of [raw=>{raw.scope.version_id=999;},raw=>{raw.history[0].vigencia_hasta='2026-08-15';},raw=>{raw.history[0].source_status='SOURCE_CONFLICT';}]){const raw=pricingRaw();mutate(raw);assert.throws(()=>projectPricingObservedCondition({authorization,executionAttempt:attempt,rawResult:raw,observed_at:TIMES.execute,admitted_at:TIMES.execute}),/PHYSICAL_BINDING_MISMATCH|AUTHORIZED_RESULT_POINT_MISSING/);}assert.deepEqual(authorization.authorized_claim_types,['OBSERVED_COMMERCIAL_CONDITION']);for(const forbidden of ['REALIZED_TRANSACTION_PRICE','PRICE_ELASTICITY','SALES_IMPACT','CAUSAL_EFFECT'])assert.equal(JSON.stringify(authorization).includes(forbidden),false);});

test('source certification matrices expose connected authority and explicit cross-source blockers',()=>{assert.equal(TARGET_RVM_AUTHORITY_MATRIX.market_denominator.status,'CONNECTED');assert.equal(TARGET_PRICING_AUTHORITY_MATRIX.validity_end.status,'CONNECTED');assert.equal(TARGET_PRICING_AUTHORITY_MATRIX.store_scope.status,'BLOCKED_SOURCE_AUTHORITY');assert.equal(TARGET_CROSS_SOURCE_READINESS.PRICE_SALES_JOIN_READINESS.deterministic_join_possible,'PARTIAL');assert.equal(TARGET_CROSS_SOURCE_READINESS.RVM_SALES_JOIN_READINESS.deterministic_join_possible,'PARTIAL');assert.equal(TARGET_CAPABILITY_COVERAGE.find(row=>row.capability_id==='MARKET/MARKET_HISTORY').classification,'BLOCKED_SOURCE_AUTHORITY');assert.equal(TARGET_CAPABILITY_COVERAGE.find(row=>row.capability_id==='MARKET/COMPETITIVE_RELATION').classification,'BLOCKED_OUTPUT_SEMANTICS');});
