import test from 'node:test';import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { createEvidenceLedger } from '../../lib/protocol/execution/index.js';
import { executeAndAdmitEvidence } from '../../lib/protocol/execution/index.js';
import { evaluateObservedResultSufficiencyV2, validateEvidenceObligation, validateSufficiencyEvaluationV2 } from '../../lib/protocol/sufficiency/index.js';
import { admittedFocused, contextWithRecords, rebuildClaim, rebuildEvidence, SUFFICIENCY_CLOCK } from './sufficiency-helpers.js';
import { authorizedFocused, executeCommand } from './execution-helpers.js';

function evaluate(f,over={}){return evaluateObservedResultSufficiencyV2({state:f.state,goal:f.goal,ledger:f.ledger,questionContract:f.question,universeResolution:f.resolution,availabilitySnapshot:f.availability,evaluated_at:SUFFICIENCY_CLOCK,...over});}
function changed(f,mutate){const record=rebuildEvidence(f.out.evidence,d=>{mutate(d);});return contextWithRecords(f,[record]);}
function bindingMutation(f,mutate){return changed(f,d=>{mutate(d.semantic_binding);const claim=clone(d.claims[0]);delete claim.claim_fingerprint;mutate(claim);d.claims[0]=rebuildClaim(d.claims[0],c=>mutate(c));d.provenance.typed_claim_fingerprints=[d.claims[0].claim_fingerprint];});}

test('OBSERVED_RESULT obligation is semantic, minimal and physically anonymous',async()=>{const f=await admittedFocused(),e=evaluate(f),o=e.proof.obligations[0];assert.equal(validateEvidenceObligation(o),true);assert.equal(o.required_claim_type,'OBSERVED_VALUE');assert.deepEqual(e.proof.expression,{operator:'ALL',operands:[{operator:'OBLIGATION_REF',obligation_id:o.obligation_id}]});assert.equal(/capability|motor|sql|physical/i.test(JSON.stringify(o)),false);});
test('exact admitted evidence deterministically satisfies without arithmetic',async()=>{const f=await admittedFocused(),a=evaluate(f),b=evaluate(f);assert.equal(validateSufficiencyEvaluationV2(a),true);assert.equal(a.status,'SATISFIED');assert.equal(a.evaluation_fingerprint,b.evaluation_fingerprint);assert.deepEqual(a.supporting_evidence_refs,[f.out.evidence.evidence_fingerprint]);assert.equal(JSON.stringify(a).includes(String(f.out.evidence.claims[0].value.amount+f.out.evidence.claims[0].value.amount)),false);});
test('evaluation is pure and evidence ordering independent',async()=>{const f=await admittedFocused(),before={state:clone(f.state),ledger:clone(f.ledger)},copy=rebuildEvidence(f.out.evidence,d=>{d.evidence_id='ordered-copy';d.claims[0]=rebuildClaim(d.claims[0],c=>c.value.amount+=1);d.provenance.typed_claim_fingerprints=[d.claims[0].claim_fingerprint];}),two=contextWithRecords(f,[copy,f.out.evidence]),a=evaluate(two),b=evaluate(contextWithRecords(f,[f.out.evidence,copy]));assert.equal(a.evaluation_fingerprint,b.evaluation_fingerprint);assert.deepEqual({state:f.state,ledger:f.ledger},before);});
test('opaque evidence id does not alter sufficiency while value mutation changes proof fingerprint',async()=>{const f=await admittedFocused(),opaque=contextWithRecords(f,[rebuildEvidence(f.out.evidence,d=>{d.evidence_id='opaque-other';})]),value=changed(f,d=>{d.claims[0]=rebuildClaim(d.claims[0],c=>{c.value.amount+=1;});d.provenance.typed_claim_fingerprints=[d.claims[0].claim_fingerprint];});assert.equal(evaluate(opaque).evaluation_fingerprint,evaluate(f).evaluation_fingerprint);assert.notEqual(evaluate(value).evaluation_fingerprint,evaluate(f).evaluation_fingerprint);});
test('N01/N13 execution or empty ledger cannot satisfy',async()=>{const f=await admittedFocused(),empty={...f,ledger:createEvidenceLedger(f.state.protocol_id),state:(await import('../../lib/protocol/runtime/index.js')).createProtocolState({...clone(f.state),admitted_evidence_refs:[],state_hash:undefined})};assert.equal(evaluate(empty).status,'PENDING');});
for(const [status,error] of [['FAILED_FINAL',Object.assign(new Error('final'),{code:'FINAL'})],['FAILED_RETRYABLE',Object.assign(new Error('temporary'),{code:'TEMPORARY',retryable:true})]])test(`${status} alone remains PENDING, never NOT_EVALUABLE`,async()=>{const f=await authorizedFocused(),out=await executeAndAdmitEvidence(f.state,f.authorization,executeCommand(f.state,f.authorization),{applicabilityDecisions:f.applicabilityDecisions,availabilitySnapshot:f.availability,motorResolver:async()=>async()=>{throw error;},clock:'2026-09-15T12:03:00.000Z'}),evaluation=evaluateObservedResultSufficiencyV2({state:out.state,goal:out.state.goals[0],ledger:out.ledger,questionContract:f.question,universeResolution:f.resolution,availabilitySnapshot:f.availability,evaluated_at:SUFFICIENCY_CLOCK});assert.equal(out.attempt.status,status);assert.equal(evaluation.status,'PENDING');});
test('N02 evidence for another Goal cannot satisfy',async()=>{const f=await admittedFocused(),other=changed(f,d=>{d.goal_refs=['sha256:other'];d.provenance.goal_ref='sha256:other';});assert.equal(evaluate(other).status,'PENDING');});
for(const [name,mutate] of [['subject',b=>b.subject.canonical_id='brand_other'],['period',b=>{b.period.date_from='2026-07-01';b.period.date_to='2026-07-31';}],['universe',b=>b.commercial_universe='OWN_STORES'],['measure',b=>b.measure='OTHER'],['organization',b=>b.organization_scope='OTHER'],['grain',b=>b.grain='MODEL'],['comparison',b=>b.comparison='YOY']])test(`wrong ${name} binding cannot satisfy`,async()=>{const f=await admittedFocused(),bad=bindingMutation(f,mutate);assert.equal(evaluate(bad).status,'PENDING');});
test('wrong authority, insufficient coverage and comparability cannot satisfy',async()=>{const f=await admittedFocused();for(const bad of [changed(f,d=>{d.authority_refs=['sha256:wrong'];d.claims[0]=rebuildClaim(d.claims[0],c=>c.authority_refs=['sha256:wrong']);d.provenance.typed_claim_fingerprints=[d.claims[0].claim_fingerprint];}),changed(f,d=>d.coverage={status:'LIMITED',ratio:.8,threshold_met:true}),changed(f,d=>d.comparability={status:'INSUFFICIENT',mode:'NONE'})])assert.equal(evaluate(bad).status,'PENDING');});
test('N08/N09 stale and superseded evidence cannot satisfy',async()=>{const f=await admittedFocused(),ref=f.out.evidence.evidence_fingerprint;for(const status of ['STALE','SUPERSEDED'])assert.equal(evaluate(f,{evidenceLifecycle:[{evidence_ref:ref,status}]}).status,'PENDING');});
test('N10 conflicting exact evidence remains PENDING',async()=>{const f=await admittedFocused(),other=changed(f,d=>{d.evidence_id='conflict';d.claims[0]=rebuildClaim(d.claims[0],c=>c.value.amount+=1);d.provenance.typed_claim_fingerprints=[d.claims[0].claim_fingerprint];}).ledger.records[0],both=contextWithRecords(f,[f.out.evidence,other]),e=evaluate(both);assert.equal(e.status,'PENDING');assert.deepEqual(e.blocking_reasons,['EVIDENCE_CONFLICT']);});
test('unauthorized claim type is rejected before it can satisfy',async()=>{const f=await admittedFocused(),draft=clone(f.out.evidence.claims[0]);delete draft.claim_fingerprint;draft.claim_type='GROWTH';assert.throws(()=>rebuildClaim(f.out.evidence.claims[0],c=>c.claim_type='GROWTH'),/INVALID_ENUM/);});
