import test from 'node:test';import assert from 'node:assert/strict';
import { clone } from '../../lib/protocol/primitives.js';
import { createSynthesisPacketV2, validatePacketEvidenceBoundary, validateSynthesisPacketV2, applyProtocolClosure, applySufficiencyEvaluation, buildSynthesisPacketV2, evaluateObservedResultSufficiencyV2, evaluateProtocolClosure } from '../../lib/protocol/sufficiency/index.js';
import { admittedFocused, CLOSURE_CLOCK, GOAL_CLOCK, SUFFICIENCY_CLOCK, SYNTHESIS_CLOCK } from './sufficiency-helpers.js';

async function completed(){const f=await admittedFocused(),evaluation=evaluateObservedResultSufficiencyV2({state:f.state,goal:f.goal,ledger:f.ledger,questionContract:f.question,universeResolution:f.resolution,availabilitySnapshot:f.availability,evaluated_at:SUFFICIENCY_CLOCK}),assessed=applySufficiencyEvaluation(f.state,evaluation,{clock:GOAL_CLOCK}),closure=evaluateProtocolClosure({state:assessed,sufficiencyEvaluations:[evaluation]}),state=applyProtocolClosure(assessed,closure,{clock:CLOSURE_CLOCK});return {...f,evaluation,assessed,closure,state};}
function build(f,over={}){return buildSynthesisPacketV2({questionContract:f.question,protocolState:f.state,sufficiencyEvaluations:[f.evaluation],evidenceRecords:[f.out.evidence],universeResolution:f.resolution,availabilitySnapshot:f.availability,created_at:SYNTHESIS_CLOCK,...over});}
function recreate(packet,mutate){const draft=clone(packet);delete draft.packet_fingerprint;mutate(draft);return createSynthesisPacketV2(draft);}

test('N19 nonterminal protocol cannot create packet',async()=>{const f=await admittedFocused();assert.throws(()=>buildSynthesisPacketV2({questionContract:f.question,protocolState:f.state,sufficiencyEvaluations:[],evidenceRecords:[],universeResolution:f.resolution,availabilitySnapshot:f.availability,created_at:SYNTHESIS_CLOCK}),/SYNTHESIS_REQUIRES_COMPLETE_PROTOCOL/);});
test('COMPLETE creates bounded SynthesisPacket with one observed claim',async()=>{const f=await completed(),packet=build(f);assert.equal(validateSynthesisPacketV2(packet),true);assert.equal(packet.status,'COMPLETE');assert.equal(packet.authorized_claims.length,1);assert.equal(packet.authorized_claims[0].claim_type,'OBSERVED_VALUE');assert.deepEqual(packet.evidence_refs,[f.out.evidence.evidence_fingerprint]);assert.equal(validatePacketEvidenceBoundary(packet,[f.out.evidence]),true);});
test('packet carries structured limitations, provenance and closed forbidden inferences',async()=>{const packet=build(await completed());assert.deepEqual(packet.limitations.map(item=>item.code),['SCOPE_EXACT','PERIOD_EXACT','DATA_COVERAGE','COMPARISON_NONE','CLAIM_BOUNDARY']);for(const code of ['NO_GROWTH_INFERENCE','NO_TREND_INFERENCE','NO_RISK_INFERENCE','NO_MARKET_POSITION_INFERENCE','NO_EXPECTATION_INFERENCE','NO_CAUSAL_INFERENCE','NO_COMPARISON_INFERENCE'])assert.ok(packet.forbidden_inferences.includes(code));assert.equal(packet.provenance.data_snapshot_refs.length,1);});
test('packet exposes no physical or legacy payload identity',async()=>{const text=JSON.stringify(build(await completed())).toLowerCase();for(const token of ['capability_id','longitudinal/ventas','motor','physical_request','sql','response_payload','context_payload','execution_authorization'])assert.equal(text.includes(token),false,token);});
test('packet fingerprint is deterministic and ignores created_at',async()=>{const f=await completed(),a=build(f),b=build(f,{created_at:'2026-09-15T13:00:00.000Z'});assert.equal(a.packet_fingerprint,b.packet_fingerprint);});
test('N20/N26 unsupported or causal claim injection is rejected',async()=>{const packet=build(await completed());assert.throws(()=>recreate(packet,d=>d.authorized_claims[0].claim_type='GROWTH'),/INVALID_ENUM/);assert.throws(()=>recreate(packet,d=>d.authorized_claims[0].causal_explanation='because'),/UNKNOWN_FIELD/);});
test('N21/N22 capability identity and raw payload are rejected',async()=>{const packet=build(await completed());for(const mutate of [d=>d.capability_id='x',d=>d.raw_payload={value:1}])assert.throws(()=>recreate(packet,mutate),/UNKNOWN_FIELD|FORBIDDEN_FIELD/);});
test('N23 claim not backed by supporting evidence is rejected',async()=>{const f=await completed(),packet=build(f),mutated=recreate(packet,d=>d.authorized_claims[0].claim_fingerprint='sha256:unsupported');assert.throws(()=>validatePacketEvidenceBoundary(mutated,[f.out.evidence]),/CLAIM_NOT_BACKED_BY_EVIDENCE/);});
test('N24/N25 widened period or universe is rejected against evidence',async()=>{const f=await completed(),packet=build(f);for(const mutate of [d=>d.authorized_claims[0].period.date_from='2026-07-01',d=>d.authorized_claims[0].commercial_universe='ALL']){const mutated=recreate(packet,mutate);assert.throws(()=>validatePacketEvidenceBoundary(mutated,[f.out.evidence]),/SYNTHESIS_CLAIM_WIDENED/);}});
