import { createGoalInstance } from '../contracts.js';
import { BindingOperator, EvidenceClass, GoalType, PHYSICAL_FIELDS, ProgressType, SignalType } from '../enums.js';
import { clone, finalizeWithHash, invariant, rejectKeysDeep, rejectUnknown, requireArray, requireEnum, requireObject, requireString, verifyHash } from '../primitives.js';

const FORBIDDEN=new Set([...PHYSICAL_FIELDS,'question_family','decision_plan','raw','raw_payload','motor_payload','llm','prompt']);
const TIMESTAMP=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
function strings(value,path,{nonEmpty=false}={}){requireArray(value,path,{nonEmpty});value.forEach((item,index)=>requireString(item,`${path}[${index}]`));invariant(new Set(value).size===value.length,'DUPLICATE_VALUE',path);}
function integer(value,path,{minimum=0}={}){invariant(Number.isInteger(value)&&value>=minimum,'INVALID_INTEGER',path);}
function instant(value,path){invariant(TIMESTAMP.test(value||''),'INVALID_TIMESTAMP',path);}
function binding(value,path){requireObject(value,path);const direct=clone(value),comparison=direct.comparison,explicit_constraints=direct.explicit_constraints;delete direct.comparison;delete direct.explicit_constraints;createGoalInstance({contract_version:'goal_instance.v1',goal_id:'binding_validation',question_contract_ref:'binding_validation',universe_resolution_ref:'binding_validation',goal_type:'OBSERVED_RESULT',evidence_class:'REQUIRED',origin:'SYSTEM_DERIVED',status:'PENDING',bindings:direct,comparison,explicit_constraints});}

export function validateSignalRule(value){
  rejectUnknown(value,['rule_id','version','accepted_source_goal_types','required_claim_types','output_signal_type','predicate','payload_schema','provenance_requirements','rule_fingerprint'],'$');requireString(value.rule_id,'$.rule_id');requireString(value.version,'$.version');strings(value.accepted_source_goal_types,'$.accepted_source_goal_types',{nonEmpty:true});value.accepted_source_goal_types.forEach((item,index)=>requireEnum(item,Object.values(GoalType),`$.accepted_source_goal_types[${index}]`));strings(value.required_claim_types,'$.required_claim_types',{nonEmpty:true});value.required_claim_types.forEach((item,index)=>requireEnum(item,['OBSERVED_VALUE'],`$.required_claim_types[${index}]`));requireEnum(value.output_signal_type,Object.values(SignalType),'$.output_signal_type');rejectUnknown(value.predicate,['operator','threshold'],'$.predicate');requireEnum(value.predicate.operator,['NUMERIC_GTE'],'$.predicate.operator');invariant(typeof value.predicate.threshold==='number'&&Number.isFinite(value.predicate.threshold),'INVALID_THRESHOLD','$.predicate.threshold');rejectUnknown(value.payload_schema,['status'],'$.payload_schema');requireEnum(value.payload_schema.status,['MATCHED'],'$.payload_schema.status');rejectUnknown(value.provenance_requirements,['admitted','current'],'$.provenance_requirements');invariant(value.provenance_requirements.admitted===true&&value.provenance_requirements.current===true,'INVALID_PROVENANCE_REQUIREMENT','$.provenance_requirements');rejectKeysDeep(value,FORBIDDEN,'$');verifyHash(value,'rule_fingerprint',['rule_id']);return true;
}
export function createSignalRule(draft){const value=finalizeWithHash(draft,'rule_fingerprint',['rule_id']);validateSignalRule(value);return value;}

export function validateTypedSignal(value){
  rejectUnknown(value,['signal_id','signal_version','protocol_id','signal_type','semantic_binding','source_goal_refs','source_evidence_refs','source_claim_refs','rule','payload','signal_fingerprint','created_at'],'$');for(const key of ['signal_id','protocol_id'])requireString(value[key],`$.${key}`);requireEnum(value.signal_version,['typed_signal.v1'],'$.signal_version');requireEnum(value.signal_type,Object.values(SignalType),'$.signal_type');binding(value.semantic_binding,'$.semantic_binding');for(const key of ['source_goal_refs','source_evidence_refs','source_claim_refs'])strings(value[key],`$.${key}`,{nonEmpty:true});rejectUnknown(value.rule,['rule_id','rule_version'],'$.rule');requireString(value.rule.rule_id,'$.rule.rule_id');requireString(value.rule.rule_version,'$.rule.rule_version');rejectUnknown(value.payload,['status','observed_amount','threshold'],'$.payload');requireEnum(value.payload.status,['MATCHED'],'$.payload.status');for(const key of ['observed_amount','threshold'])invariant(typeof value.payload[key]==='number'&&Number.isFinite(value.payload[key]),'INVALID_SIGNAL_PAYLOAD',`$.payload.${key}`);instant(value.created_at,'$.created_at');rejectKeysDeep(value,FORBIDDEN,'$');verifyHash(value,'signal_fingerprint',['signal_id','protocol_id','created_at']);return true;
}
export function createTypedSignal(draft){const value=finalizeWithHash(draft,'signal_fingerprint',['signal_id','protocol_id','created_at']);validateTypedSignal(value);return value;}

function bindingRule(value,path){rejectUnknown(value,['target','operator','source'],path);requireString(value.target,`${path}.target`);requireEnum(value.operator,Object.values(BindingOperator),`${path}.operator`);requireString(value.source,`${path}.source`);}
export function validateTransitionRule(value){
  rejectUnknown(value,['transition_rule_id','version','source_goal_type','source_signal_type','signal_predicate','preconditions','target_goal_type','target_evidence_class','binding_rules','expected_contribution','progress_type','depth_cost','priority','rule_fingerprint'],'$');for(const key of ['transition_rule_id','version'])requireString(value[key],`$.${key}`);requireEnum(value.source_goal_type,Object.values(GoalType),'$.source_goal_type');requireEnum(value.source_signal_type,Object.values(SignalType),'$.source_signal_type');rejectUnknown(value.signal_predicate,['status_equals'],'$.signal_predicate');requireString(value.signal_predicate.status_equals,'$.signal_predicate.status_equals');strings(value.preconditions,'$.preconditions');requireEnum(value.target_goal_type,Object.values(GoalType),'$.target_goal_type');requireEnum(value.target_evidence_class,[EvidenceClass.CONDITIONAL,EvidenceClass.SUPPLEMENTAL],'$.target_evidence_class');requireArray(value.binding_rules,'$.binding_rules',{nonEmpty:true});value.binding_rules.forEach((item,index)=>bindingRule(item,`$.binding_rules[${index}]`));strings(value.expected_contribution,'$.expected_contribution',{nonEmpty:true});requireEnum(value.progress_type,Object.values(ProgressType),'$.progress_type');integer(value.depth_cost,'$.depth_cost',{minimum:1});integer(value.priority,'$.priority');rejectKeysDeep(value,FORBIDDEN,'$');verifyHash(value,'rule_fingerprint',['transition_rule_id']);return true;
}
export function createTransitionRule(draft){const value=finalizeWithHash(draft,'rule_fingerprint',['transition_rule_id']);validateTransitionRule(value);return value;}

export function validateCandidateGoal(value){
  rejectUnknown(value,['candidate_id','protocol_id','state_version','goal_type','semantic_binding','evidence_class','origin','source_signal_ref','transition_rule_ref','expected_contribution','progress_type','depth','candidate_fingerprint'],'$');for(const key of ['candidate_id','protocol_id','source_signal_ref','transition_rule_ref'])requireString(value[key],`$.${key}`);integer(value.state_version,'$.state_version',{minimum:1});requireEnum(value.goal_type,Object.values(GoalType),'$.goal_type');binding(value.semantic_binding,'$.semantic_binding');requireEnum(value.evidence_class,[EvidenceClass.CONDITIONAL,EvidenceClass.SUPPLEMENTAL],'$.evidence_class');requireEnum(value.origin,['TRANSITION_RULE'],'$.origin');strings(value.expected_contribution,'$.expected_contribution',{nonEmpty:true});requireEnum(value.progress_type,Object.values(ProgressType),'$.progress_type');integer(value.depth,'$.depth',{minimum:1});rejectKeysDeep(value,FORBIDDEN,'$');verifyHash(value,'candidate_fingerprint',['candidate_id','protocol_id','state_version']);return true;
}
export function createCandidateGoal(draft){const value=finalizeWithHash(draft,'candidate_fingerprint',['candidate_id','protocol_id','state_version']);validateCandidateGoal(value);return value;}

export function transitionActivationFingerprint(signal,rule){validateTypedSignal(signal);validateTransitionRule(rule);return finalizeWithHash({signal_fingerprint:signal.signal_fingerprint,transition_rule_fingerprint:rule.rule_fingerprint},'activation_fingerprint').activation_fingerprint;}
