export const QUESTION_FAMILIES = Object.freeze([
  'CURRENT_STATUS',
  'EXPECTATION_AND_CLOSE',
  'TEMPORAL_CONSTRUCTION',
  'COMMERCIAL_HEALTH',
  'COMPETITIVE_PERFORMANCE',
  'RESULT_EXPLANATION',
  'FAIR_COMPARISON',
  'PRODUCT_PLACE_FIT',
  'OPERATIONAL_FLOW',
  'OPPORTUNITY_ASSESSMENT',
  'RISK_ASSESSMENT',
  'ACTION_PRIORITIZATION',
]);

export const EVIDENCE_REQUIREMENTS = Object.freeze([
  'CURRENT_RESULT',
  'HISTORICAL_REFERENCE',
  'MARKET_REFERENCE',
  'CLOSE_EXPECTATION',
  'CHANGE_CONTRIBUTION',
  'CRM_CONTEXT_SIGNAL',
  'COMMERCIAL_OPERATION_SIGNAL',
]);

export const PUBLIC_EVIDENCE_KIND = Object.freeze({
  CURRENT_RESULT:'current_result',
  HISTORICAL_REFERENCE:'historical_reference',
  MARKET_REFERENCE:'market_reference',
  CLOSE_EXPECTATION:'expectation',
  CHANGE_CONTRIBUTION:'change_explanation',
  CRM_CONTEXT_SIGNAL:'demand_context',
  COMMERCIAL_OPERATION_SIGNAL:'commercial_operation_context',
});
